### ISSUE TITLE
Wallet and miner running at the same time

### ISSUE THREAD

**Issue by SG-O** [decred/dcrd#1]
It would be great if the wallet and a miner could be running with the same dcrd instance.

**Comment by jolan** [comment]
Can you please post an example or further explain your request?  I'm not sure I understand.

**Comment by jcvernaleo** [comment]
So as of the latest cgminer commit (decred/cgminer 27fb09dff3) you can use --cert to have cgminer point to the dcrd rpc cert.  With that, I can have a copy of wallet (in the normal config) and a copy of cgminer connect to the same dcrd instance.
If that doesn't fix it for you (or if there was something else you needed), please reopen the issue.
Thanks @jolan  and @SG-O !
