### ISSUE TITLE
Mining with waiting for additional votes

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#103]
Is it possible for the mining code to wait for more of the votes instead of releasing the block right away? The miners dont get full reward without including the tickets, so the incentive is already there. Is it technically possible for a miner to wait for the additional votes. Not sure if their found block would still be valid or if the hash becomes modified with more votes added.

**Comment by cjepson** [comment]
You could, but it increases the likelihood of your block being orphaned and you losing any rewards. Let's say your miner (miner A) is waiting for all 5 votes but they never come, so you work on the parent block. In the meantime, miner B works on the current block and finds a block with 4/5 voters. Even if you mined a new block on parent, miner B's new block would still be a longer chain than yours. The mining code is optimized to be as greedy as possible.

The other problem with such a feature is that it allows PoS miners to more easily manipulate the network, by selectively releasing votes and changing what blocks miners are working on.

**Comment by raedah** [comment]
What I was thinking would be rules like this:
If the time between the previous block and the current block was less then 45 seconds,
then wait an additional 10 seconds per missing vote before broadcasting block.

This way its taking into account the probability that the votes will still show up. If the time between block was less then ~30 seconds, then there is a good chance the votes could show up in the next ~10 seconds. These numbers are just guesstimates, and can be refined.

Some exact math could probably be done to determine exactly what the opportunity cost would be of waiting x seconds, based on how many additional creds are being earned from including the additional votes, vs the probability that another miner will find a block within that time frame, and also the probability that the votes will show up based on a measurement of avg propagation time and the percentage of votes that never show up.

**Comment by cjepson** [comment]
> If the time between the previous block and the current block was less then 45 seconds,
then wait an additional 10 seconds per missing vote before broadcasting block.

Not sure what you mean he. Votes can only be cast if you broadcast the block.

>This way its taking into account the probability that the votes will still show up. If the time between block was less then ~30 seconds, then there is a good chance the votes could show up in the next ~10 seconds. These numbers are just guesstimates, and can be refined.

If you stop mining, your subsidy is 0, whereas if you have 3/5 or 4/5 and you continue to mine, your subsidy would be non-zero. You're competing with other miners on the network. In the time you stop to wait, they may already have mined another block and gotten some subsidy while you for sure got nothing if you weren't mining. The only time I can think of where this may be useful is if the cost of power is more than the reduced subsidy is worth. But people mining like this also open themselves up to attack. Voters may without votes just to get you to not mine, then take over the chain by mining more 3/5 or 4/5 blocks.

On my node it's rare for votes to come in after 10 seconds, but can occasionally happen.
`23:16:13 2016-04-06 [INF] BMGR: Processed 1 block in the last 19.33s (1 tra[80/1883] height 17084, 2016-04-06 23:16:11 -0400 EDT)
23:16:14 2016-04-06 [DBG] MINR: Accepted vote bf1985285a6d226b1175e3fcbc20ef23688355
d248912b2d364113359e5da6b2 for block hash 0000000000002a892703ca07ebec3ec941de1c517c13349bda7d28af5a481445 (height 17084), voting true on the transaction tree
23:16:14 2016-04-06 [DBG] MINR: Accepted vote 667d9416df05f0c926a6d3cc3b461adebd6a8d
49120366ab568d399b9fb0d625 for block hash 0000000000002a892703ca07ebec3ec941de1c517c13349bda7d28af5a481445 (height 17084), voting true on the transaction tree
23:16:15 2016-04-06 [DBG] MINR: Accepted vote 70832b81fb6eaa3d4061aa18e7e9822fed380f
8f8f15cd6baea63e9694949263 for block hash 0000000000002a892703ca07ebec3ec941de1c517c
13349bda7d28af5a481445 (height 17084), voting true on the transaction tree
23:16:16 2016-04-06 [DBG] MINR: Accepted vote 637e3089cb8c1a9c96d91f10cfffa0cd459d13
0ee4b081631a11083cd2eca036 for block hash 0000000000002a892703ca07ebec3ec941de1c517c
13349bda7d28af5a481445 (height 17084), voting true on the transaction tree
23:16:28 2016-04-06 [DBG] MINR: Accepted vote d4b8259e69818977dd47957076b4c67de1ba33
3858f01539f49a7a92b5bebbd5 for block hash 0000000000002a892703ca07ebec3ec941de1c517c13349bda7d28af5a481445 (height 17084), voting true on the transaction tree`

**Comment by raedah** [comment]
Including notes from IRC conversation. Closing this issue until some later date when I can prioritize the investigation of this feature. 

<raedah> have you noticed how blocks not including all 5 votes are particularly an issue when the blocks are found close together?
<@ceejep> Yes, the shorter the time between blocks the higher the probability of orphaning a vote.
<raedah> why?
<@ceejep> Because network propagation of votes by time seen usually approximate a Poisson function.
<@ceejep> And some votes simply take a lot time to get across the network, despite being tiny.
<@ceejep> s/Poisson function/Poisson distribution
<@ceejep> Block generation itself is a pretty interesting, and similar plot if you plot them out by time from the last block.
<raedah> ok, so im not trying to be repetitive, but just getting clarity. If the issue is how long the votes take to propagate, then there is a balance between the reward a miner would get by waiting and including the votes that have not yet propagated, versus the risk that they could lose the entire block reward if someone else mines.
<@ceejep> Correct. As the network infrastructure increases, it would be expected that the risk would diminish.
<@ceejep> You could try to determine was a good wait time to start mining on the next block would be if you haven't yet seen 5/5, but I expect it's dynamic and ever-changing duration of time.
<@ceejep> s/was a/what a
<raedah> so maybe its 10 second gaps between blocks and waiting 2 more seconds, or maybe its 1 minutes between blocks and waiting an extra 20 seconds. With lots of data, I think there maybe answers here on when its actually in a miners best interest over time to try and include more votes by delaying the release of the block for a short time. And I hear you that it could possibly open up an attack vector, worth considering. But so is worth considering getting 
<raedah> more block reward.
<@ceejep> Doing so also exposes you to risks, such as a PoW miner who has some stake votes and doesn't broadcast them in the attempt to make you stop working.
<raedah> if these calculations were dynamic, and it did expose the risk of losing the block to competition, then if these calcs were dynamic, it should autocorrect over time.
<@ceejep> Autocorrect to make you lose money. :) Since the correction is what the attacker is banking on.
<raedah> just probability of getting more votes included in the block  vs.  probability that someone else will mine the block
<raedah> just weighing the risks to get the highest reward
<@ceejep> If you generate the data, I'm curious to see what it looks like. Right now only a small amount of subsidy is missed, though, and it seems ever decreasing with time.
<raedah> i do have a high latency connection, and everytime I see a ticket revoked, I look at the block time gap, and every time its less then 45 seconds.
<raedah> id have to get good measurements on vote propagation times, and fit that with probably a Poisson distribution for PoW block mining with the 5 minute target, and probably take into consideration the block propagation time as well which is how the voters get notified.
