### ISSUE TITLE
GetWork notifications over Websocket

### ISSUE THREAD

**Issue by termoose** [decred/dcrd#1032]
Continuously polling `getwork` for changes (over HTTP or Websocket) is not really desirable and is the only way to get new work for miners at the moment.

I propose having a `notifywork` method on the websocket RPC, similar to [notifyblocks](https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.md#notifyblocks). This starts a subscription on messages that could look something like this (suggestion):
```
{
	"jsonrpc": "1.0",
	"method": "latestwork",
	"params": [{
		"data": "block_header",
		"target": "some_target"
	}]
}
```

The object in the `params` list here is just the object returned from the regular `getwork`.

**Comment by davecgh** [comment]
This is a good idea.  However, it will require some infrastructure changes in terms of allowing notifications of when block templates are available to propagate and result in sending such notifications.

**Comment by dnldd** [comment]
Taking this on
