### ISSUE TITLE
Tilde (~) expands to default local application data directory, not the user's home directory.

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#1040]
On unix these directories are the same, and this is likely why the issue has gone unnoticed for so long.  However, ~ will expand to `%LOCALAPPDATA%` on windows and `$HOME/Library/Application Support` on macos.

This issue affects all programs in this repo (dcrd, dcrctl, etc.).

**Comment by jrick** [comment]
The correct implementation can be yanked from dcrwallet: https://github.com/decred/dcrwallet/blob/a7f0e4017b4976775b68d2d1082a7eca416c94f3/config.go#L189-L236

**Comment by StabbarN** [comment]
Are you sure about mac os? 

`~` in a terminal (or Finder) expands to the user's home directory. 

I doubt it, but perhaps it's different when `~` is used inside an app. I did a quick googling but failed to find any support for that theory.

**Comment by jrick** [comment]
Yes, it's bugged on macos as well.  It may be expanded by your shell, but you can verify that dcrd does not expand it correctly by quoting the strings (`"~/foo"`) or using ~ in your config file.

Application Support is the expected location for application data such as the config file, logs, and the blockchain data.  It won't be moved and that location will remain the same.

**Comment by jrick** [comment]
You can also test the linked PR and let me know if anything unexpected happens.

**Comment by StabbarN** [comment]
I tested it and it seems to work fine.

However, the log says:
```
2018-02-17 10:11:52.853 [INF] DCRD: Home dir: /Users/userName/Library/Application Support/Dcrd
```
so `cfg.HomeDir` is still configured to `Application Support/Dcrd`. It's confusing to have different meaning of "home dir". `~` expands to `/Users/username` but `HomeDir` means `Application Support/Dcrd`. Worth considering renaming `cfg`'s `HomeDir` to `appDataDir`?

**Comment by jrick** [comment]
cfg.HomeDir is incorrectly named, I agree.  In fact, the option is really --appdata but after the change from --homedir to --appdata only the config option name was modified, not the field in the config struct.  What you see in logs is just the log text and that can be updated to remove confusion.
