### ISSUE TITLE
Help Flag outputs to Standard error

### ISSUE THREAD

**Issue by jyap808** [decred/dcrd#105]
It seems like this is by design but isn't "the Unix way":

```
    // HelpFlag adds a default Help Options group to the parser containing
    // -h and --help options. When either -h or --help is specified on the
    // command line, the parser will return the special error of type
    // ErrHelp. When PrintErrors is also specified, then the help message
    // will also be automatically printed to os.Stderr.
```

Running `dcrd --help` outputs to standard error which prevents immediate parsing of the Help output through another program such as `less` or `grep`.  The work around is to forward standard error output to standard out but this is annoying and deviates from normal behavior of other Unix programs.  Proposed change is to have the Help Flag output to standard out.

Also mentioned by others in IRC.

**Comment by chappjc** [comment]
Yes as I said on IRC it's tedious to do 2>&1 just to pipe it to less.  So, +1

**Comment by jcvernaleo** [comment]
Although I also prefer things to be more UNIXy myself (and don't get me started on the lack of man pages with go programs) I believe this is a 'feature' of go-flags which would mean we are stuck with it (since using a different package for parsing options would kind of be a waste).  So I'm going to close this but if someone (@dajohi maybe) can correct me and has a way to do it with go-flags that isn't a huge hack I'm happy to reopen it.

**Comment by chappjc** [comment]
[On this line of config.go](https://github.com/decred/dcrd/blob/1c180c1106868562bc33598262e9223bd8bf4726/config.go#L391), `flags.ErrHelp` means that **`err` from `Parse()` contains help that you need to print**, so you just need to print it to stdout (like in gencerts.go).  For example,

https://github.com/chappjc/dcrd/commit/1ac5a3af99a0c02aa4368b28e054c7d06b0bed6b

```go
	preParser := newConfigParser(&preCfg, &serviceOpts, flags.HelpFlag)
	_, err := preParser.Parse()
	if err != nil {
		e, ok := err.(*flags.Error)
		if ok && e.Type == flags.ErrHelp {
			fmt.Println("You used flags.HelpFlag (or Default).")
			fmt.Fprintln(os.Stdout, err)
			return nil, nil, err
		}
		if !ok || e.Type != flags.ErrHelp {
			fmt.Println("You did NOT use flags.HelpFlag.")
			preParser.WriteHelp(os.Stdout)
		}
	}
```

**Comment by jcvernaleo** [comment]
@chappjc that is what I get for going from memory instead of reading code :)

**Comment by jrick** [comment]
We are still debating whether we want to change this or not but we will come to some decision for 0.6.

**Comment by marcopeereboom** [comment]
Even though you guys clearly are all wrong 💯I realize I have been outvoted.

I won't accept this until all tools get the same treatment.  If we do this all command lines across the entire suite need updating (so this means all tools! including dcrwallet, dcrticketbuyer etc etc).
