### ISSUE TITLE
dcrctl --terminal remove empty lines from history

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#108]
dcrctl --terminal currently saves an empty line in the history when they are entered. This is problematic because when hitting the up arrow to go to the history, nothing appears. Empty lines should be omitted from the scroll back history.

**Comment by dajohi** [comment]
This belongs in https://github.com/golang/crypto/blob/master/ssh/terminal/terminal.go

**Comment by davecgh** [comment]
Since `--terminal` has been removed completely, this no longer applies.
