### ISSUE TITLE
double spend of unmined transaction???

### ISSUE THREAD

**Issue by 5dao** [decred/dcrd#1165]
[ERR] WLLT: Failed to send vote for ticket hash 476dfeb54b86661e06e18cf476aca3b162cf5b7be63d3898bf237b2c76e90d2b: unmined transaction f68108f43c65e0fe7147b3eae0aea874df90029489315609149bee651fd66cff is a double spend of unmined transaction 188d371e4252d3448d5e8648db86b27d6d9b65824623179fdd0d9256547ea880

????

**Comment by jrick** [comment]
Wrong repo and wrong cryptocurrency project.  Use the hybridnetwork issue trackers for hybridnetwork bugs.
