### ISSUE TITLE
 deriving additional addresses violates the unused address gap limit

### ISSUE THREAD

**Issue by CockyCat** [decred/dcrd#1166]
When I used getnewaddress, reported this error:   deriving additional addresses violates the unused address gap limit

  How can I break through the limitations of generating addresses?

**Comment by alexlyp** [comment]
use `dcrctl --wallet getnewaddress default ignore`

**Comment by CockyCat** [comment]
Found a fatal bug

When using the address generated by `dcrctl --wallet getnewaddress default ignore` and then sending transactions to these addresses, these addresses do not receive dcr. But they can be found through the block browser and the sender does deduct Dcr

Please pay attention to this issue, which means that DCR is lost?
