### ISSUE TITLE
dcrctl command getreceivedbyaccount returns wrong value

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/dcrd#1169]
My Testnet account has received a single transaction of 1000dcr so it is the total sum of the amount it ever received. 
However this is what I get when execute the command getreceivedbyaccount:
```
dcrctl --testnet -u user -P pass --wallet getreceivedbyaccount default
3217.60415605
```
This is also wrong for my mainnet account

**Comment by jrick** [comment]
Closing as this should have been opened on the dcrwallet tracker, but this is also not unexpected as it includes received change.
