### ISSUE TITLE
Remove chainec Package

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#1191]
The entire `chainec` package should be removed and the code updated to use the underlying packages directly instead.

The intent of this package seemed to be to provide a generic interface to working with different elliptic curves, however, when looking at the code, there are virtually no cases where this capability is actually useful, it complicates the code, it makes it less efficient, and, perhaps worst of all, in many cases, it creates misleading results.

For example, consider the `hdkeychain` package.  The `ECPubKey` function returns a `chainec.PublicKey` and the `ECPrivKey` function returns a `chainec.PrivateKey`.  This is dangerous because the algorithm, as employed, only works with the `secp256k1` curve, and will *not* work with the `ed25519` curve which the `chainec` package supports.  This is the case because `secp256k1` private keys form an affine space, which is a requirement for the techniques used by the algorithm for generating the hierarchical deterministic keys produced by `hdkeychain`, while they do not in `ed25519`.  As an aside, it *is* possible to modify the HD generation algorithm specifically to work with `ed25519`, however, such modifications are not compatible with the existing `secp256k1` algorithm, and thus would require a package such as `hdkeychain/ed25519` and callers to understand which curve they are working with accordingly.

There are other instances which can lead to similar misleading behavior.  It would be much cleaner, more explicit, and less error prune to ensure that code works specifically with the curves it supports instead.

**Comment by dnldd** [comment]
Would like to take this on, assign me please.

**Comment by davecgh** [comment]
Alright cool.  Since this deals with consensus and is going to be a quite large changeset, I would suggest splitting this work up into several PRs.  For example, I'd start by changing `hdkeychain` to return `secp256k1.PrivateKey` and ` secp256k1.PublicKey` like it does upstream, and updating all of the callers accordingly.  From there, I'd suggest working on another targeted area and update its callers accordingly.

Eventually, once all of the references are removed via the series of targeted PRs, the entire `chainec` package can be removed in a final PR which then has no functional changes.

**Comment by dajohi** [comment]
Closed by 4ef5df3c6da2b12ef97754e84b6e50ea40f3026a
