### ISSUE TITLE
con't install

### ISSUE THREAD

**Issue by XieWeiZM** [decred/dcrd#1192]
he following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "golang.org/x/crypto": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/crypto?go-get=1": Get http://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:80: i/o timeout

ProjectRoot name validation failed

**Comment by davecgh** [comment]
I would suggest removing the entire `$GOPATH/src/github.com/dcrd/vendor` directory and then trying again.

**Comment by XieWeiZM** [comment]
dep: WARNING: Unknown field in manifest: prune @davecgh

**Comment by XieWeiZM** [comment]
[root@wallet-3 dcrd]# dep ensure
dep: WARNING: Unknown field in manifest: prune
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "golang.org/x/crypto": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/crypto?go-get=1": Get http://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:80: i/o timeout

ProjectRoot name validation failed
@davecgh

**Comment by XieWeiZM** [comment]
i use vpn then
[root@wallet-3 dcrd]# dep ensure
dep: WARNING: Unknown field in manifest: prune
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "golang.org/x/crypto": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/crypto?go-get=1": Get http://golang.org/x/crypto?go-get=1: EOF

ProjectRoot name validation failed
@davecgh

**Comment by davecgh** [comment]
Not really sure to be honest, but it's working correctly here.  I just created a new `GOPATH` to test it.  Maybe trying following these exact commands?

```
$ export GOPATH=~/test1192

$ git clone https://github.com/decred/dcrd $GOPATH/src/github.com/decred/dcrd
Cloning into '/home/davec/test1192/src/github.com/decred/dcrd'...
remote: Counting objects: 21971, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 21971 (delta 1), reused 0 (delta 0), pack-reused 21965
Receiving objects: 100% (21971/21971), 23.28 MiB | 7.86 MiB/s, done.
Resolving deltas: 100% (15846/15846), done.

$ cd $GOPATH/src/github.com/decred/dcrd

$ dep ensure -v
dep: WARNING: Unknown field in manifest: prune
Gopkg.lock was already in sync with imports and Gopkg.toml
(1/16) Wrote github.com/dchest/blake256@master
(2/16) Wrote github.com/btcsuite/snappy-go@master
(3/16) Wrote github.com/btcsuite/websocket@master
(4/16) Wrote github.com/btcsuite/winsvc@master
(5/16) Wrote github.com/davecgh/go-spew@master
(6/16) Wrote github.com/jessevdk/go-flags@v1.3.0
(7/16) Wrote github.com/btcsuite/goleveldb@master
(8/16) Wrote github.com/decred/base58@master
(9/16) Wrote github.com/btcsuite/go-socks@master
(10/16) Wrote github.com/jrick/logrotate@master
(11/16) Wrote github.com/agl/ed25519@master
(12/16) Wrote github.com/aead/siphash@master
(13/16) Wrote golang.org/x/sys@master
(14/16) Wrote golang.org/x/crypto@master
(15/16) Wrote github.com/jrick/bitset@master
(16/16) Wrote github.com/btcsuite/btclog@master

$ go install . ./cmd/...

$ $GOPATH/bin/dcrd -V
dcrd version 1.2.0+dev (Go version go1.10.2)
```

**Comment by XieWeiZM** [comment]
[root@wallet-3 dcrd]# dep version
dep:
 version     : v0.3.2
 build date  : 2017-10-19
 git hash    : 8ddfc8a
 go version  : go1.9
 go compiler : gc
 platform    : linux/amd64
my dep verson is this，this is No problem？
@davecgh

**Comment by davecgh** [comment]
It should be fine.  I just checked out that version of `dep` (commit 8ddfc8afb2d520d41997ebddd921b52152706c01) and ran it worked here.  Maybe your network is blocking connections?

**Comment by XieWeiZM** [comment]
@davecgh  
[root@wallet-3 dcrd]# dep ensure -v
dep: WARNING: Unknown field in manifest: prune
Gopkg.lock was already in sync with imports and Gopkg.toml
(1/16) Wrote github.com/btcsuite/winsvc@master
(2/16) Wrote github.com/btcsuite/btclog@master
(3/16) Wrote github.com/btcsuite/websocket@master
(4/16) Wrote github.com/dchest/blake256@master
(5/16) Wrote github.com/aead/siphash@master
(6/16) Wrote github.com/agl/ed25519@master
(7/16) Wrote github.com/jrick/logrotate@master
(8/16) Wrote github.com/btcsuite/go-socks@master
(9/16) Wrote github.com/davecgh/go-spew@master
(10/16) Wrote github.com/jrick/bitset@master
(11/16) Wrote github.com/btcsuite/snappy-go@master
(12/16) Wrote github.com/decred/base58@master
(13/16) Wrote golang.org/x/sys@master
(14/16) Wrote github.com/jessevdk/go-flags@v1.3.0
(15/16) Wrote github.com/btcsuite/goleveldb@master
(16/16) Wrote golang.org/x/crypto@master
[root@wallet-3 dcrd]# go install . ./cmd/...
[root@wallet-3 dcrd]# $GOPATH/bin/dcrd -V
dcrd version 1.2.0+dev (Go version go1.9.3)
[root@wallet-3 dcrd]# 
this network is blocking connections ，thanks
