### ISSUE TITLE
How to accept RPC connections outside the localhost

### ISSUE THREAD

**Issue by DinoStray** [decred/dcrd#1193]
If I want to allow the client/daemon to accept RPC connections outside the localhost, what should I do?
In bitcoind, we have the config parameter like "rpcallowip=xxx".
but I can't find it in btcd.

**Comment by davecgh** [comment]
https://github.com/decred/dcrd/blob/master/docs/configure_rpc_server_listen_interfaces.md

**Comment by DinoStray** [comment]
OK, I got it
