### ISSUE TITLE
How to curl json-rpc

### ISSUE THREAD

**Issue by XieWeiZM** [decred/dcrd#1194]
curl  --user block:block --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params":[] }' http://127.0.0.1:19109 ？

**Comment by XieWeiZM** [comment]
How to use http

**Comment by jrick** [comment]
dcrd json-rpc uses TLS by default, so you would curl `https://127.0.0.1:19109` instead.

**Comment by davecgh** [comment]
This was answered in [this](https://www.reddit.com/r/decred/comments/8bhf1e/how_to_user_curl_with_decred) reddit thread, but I'll reproduce it here for coverage:

> $ curl --silent --cacert "~/.dcrwallet/rpc.cert" --user "USER:PASS" --data-binary '{"jsonrpc": "1.0", "id":1, "method": "getinfo", "params": []}' https://127.0.0.1:9110
>
> {"jsonrpc":"1.0","result":{"version":1020000,"protocolversion":6,"walletversion":9,"balance":#####,"blocks":229105, ...},"error":null,"id":1}

Make sure to replace `USER` and `PASS` with the user and pass of the wallet's RPC server, which you can get from the `~/.dcrwallet/dcrwallet.conf` file.

If you're trying to talk to dcrd, replace `.dcrwallet` with `.dcrd` accordingly.

**Comment by XieWeiZM** [comment]
@davecgh  Is there an example  for java project use wallet's RPC？？

**Comment by davecgh** [comment]
I don't believe there is an example from Java, but the [docs have one for node.js](https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.md#82-example-nodejs-code).  Perhaps that would be a good starting point.

**Comment by XieWeiZM** [comment]
@davecgh thanks
