### ISSUE TITLE
Adding Decred in Yiimp

### ISSUE THREAD

**Issue by goodthebest** [decred/dcrd#1198]
hey folks @davecgh @dnldd 

I've installed Decred successfully that includes dcrd, dcrwallet and dcrctl. I've configured 
**.dcrd/dcrd.conf** 
**.dcrwalelt/dcrwallet.conf**
**.dcrctl/dcrctl.conf**

I managed to use **dcrctl** as CLI such as generating new decred addresses and checking balance all fine. However, when I try to add decred to Yiimp pool, I get 'ERROR' and looking at stratum log, I get
> ERROR getaccountaddress Decred 

I've tried to use port 9110, 9111 and 9109, all giving same error. Is there anything I'm missing? How can I connect decred with Yiimp stratum? I'm open to provide more information such as full .conf files and yiimp settings in detail if this info isn't enough. Please advise

**Comment by davecgh** [comment]
There really isn't much to go on there.  Is there any type of debug mode which perhaps shows the command being issued or the specific error return?

That said a few things here a few things that it could be:

* `getaccountaddress` is a wallet command, so, it definitely has to talk to `dcrwallet` and not `dcrd`.
* The default JSON-RPC port for `dcrwallet` is 9110, so that is likely the one you'll want to use if you haven't changed anything from defaults
* `getaccountaddress` requires an account to be specified.  Typically that will be `default`.  Yiimp might be calling it without any parameters which would result in an error.
* TLS is enabled by default, so you will need to make sure Yiimp is configured to use TLS and use the certificate which will be at `~/.dcrwallet/rpc.cert` by default.

**Comment by davecgh** [comment]
Is this still relevant?  I'd like to close the issue if not.

**Comment by goodthebest** [comment]
@davecgh is not resolve yet I'll post a follow up soon

**Comment by goodthebest** [comment]
@davecgh 
There seems to be an issue with **dcrctl** when I manually run command `getaccountaddress` it returns error, you can see in the screen shot

![image](https://user-images.githubusercontent.com/1715740/40592706-6e2a42d2-6233-11e8-9c4d-cf97f7e4cb42.png)

Looking at stratum log there is also error related to `getaccountaddress`, you can see below
![image](https://user-images.githubusercontent.com/1715740/40592780-1cec9a0e-6234-11e8-854e-9bcfc6cb2c04.png)

**Comment by jrick** [comment]
Is there some reason to use this instead of `getnewaddress`?  I personally would advise against using that RPC entirely.  It was deprecated in Bitcoin Core with the accounts deprecation (https://github.com/bitcoin/bitcoin/commit/3576ab126121f9bfb4d4d6195cbbe7ba30619f77) and could be removed from the API at any time.

**Comment by davecgh** [comment]
If you're trying to get an account for an address (which is a `dcrwallet` thing, btw, so really should be in the [dcrwallet repo](github.com/decred/dcrwallet), you have to specify which account you want to get it for.

```
$ dcrctl --wallet help getaccountaddress
getaccountaddress "account"

DEPRECATED -- Returns the most recent external payment address for an account that has not been seen publicly.
A new address is generated for the account if the most recently generated address has been seen on the blockchain or in mempool.

Arguments:
1. account (string, required) The account of the returned address

Result:
"value" (string) The unused address for 'account'
```

The TLS error is because you aren't configured to connect with TLS.  You need to either configure yiimp to use TLS, or start dcrwallet without it (e.g. `dcrwallet --noservertls`).

**Comment by davecgh** [comment]
Change the yiimp source code when it's talking to Decred to not do that.

**Comment by goodthebest** [comment]
> The TLS error is because you aren't configured to connect with TLS. You need to either configure yiimp  
> to use TLS, or start dcrwallet without it (e.g. dcrwallet --noservertls).

When I run dcrwallet with --noservertls, I get error from yiimp
`ERROR HTTP_UNAUTHORIZED`

and in dcrwallet log
![image](https://user-images.githubusercontent.com/1715740/40593454-bd8f501e-6239-11e8-9b42-9a8765bfe0c9.png)

**Comment by davecgh** [comment]
You don't have yiimp configured with the correct rpc user and password.

**Comment by goodthebest** [comment]
When I run` ./dcrwallet ` without `--noservertls`, it works fine and same user and password go well?

**Comment by goodthebest** [comment]
and with ` ./dcrwallet --noservertls`

![image](https://user-images.githubusercontent.com/1715740/40594005-6f63c02e-623d-11e8-9fac-b6ceba923c82.png)

**Comment by goodthebest** [comment]
@davecgh @jrick 
> Change the yiimp source code when it's talking to Decred to not do that.

even I pre define Decred wallet address I still get `ERROR getaccountaddress DECRED`

![image](https://user-images.githubusercontent.com/1715740/40595082-985cecac-6243-11e8-8e63-6305a0581311.png)

Here is the source code, could you please assist me by adding exception for Decred

```
#
#include "stratum.h"

void coind_error(YAAMP_COIND *coind, const char *s)
{
	coind->auto_ready = false;

	object_delete(coind);
	debuglog("%s error %s\n", coind->name, s);
}

double coind_profitability(YAAMP_COIND *coind)
{
	if(!coind->difficulty) return 0;
	if(coind->pool_ttf > g_stratum_max_ttf) return 0;

//	double prof = 24*60*60*1000 / (coind->difficulty / 1000000 * 0x100000000) * reward * coind->price;
//	double prof = 24*60*60*1000 / coind->difficulty / 4294.967296 * reward * coind->price;

	double prof = 20116.56761169 / coind->difficulty * coind->reward * coind->price;
	if(!strcmp(g_current_algo->name, "sha256")) prof *= 1000;

	if(!coind->isaux && !coind->pos)
	{
		for(CLI li = g_list_coind.first; li; li = li->next)
		{
			YAAMP_COIND *aux = (YAAMP_COIND *)li->data;
			if(!coind_can_mine(aux, true)) continue;

			prof += coind_profitability(aux);
		}
	}

	return prof;
}

double coind_nethash(YAAMP_COIND *coind)
{
	double speed = coind->difficulty * 0x100000000 / 1000000 / max(min(coind->actual_ttf, 60), 30);
//	if(!strcmp(g_current_algo->name, "sha256")) speed *= 1000;

	return speed;
}

void coind_sort()
{
	for(CLI li = g_list_coind.first; li && li->next; li = li->next)
	{
		YAAMP_COIND *coind1 = (YAAMP_COIND *)li->data;
		if(coind1->deleted) continue;

		YAAMP_COIND *coind2 = (YAAMP_COIND *)li->next->data;
		if(coind2->deleted) continue;

		double p1 = coind_profitability(coind1);
		double p2 = coind_profitability(coind2);

		if(p2 > p1)
		{
			g_list_coind.Swap(li, li->next);
			coind_sort();

			return;
		}
	}
}

bool coind_can_mine(YAAMP_COIND *coind, bool isaux)
{
	if(coind->deleted) return false;
	if(!coind->enable) return false;
	if(!coind->auto_ready) return false;
	if(!rpc_connected(&coind->rpc)) return false;
	if(!coind->height) return false;
	if(!coind->difficulty) return false;
	if(coind->isaux != isaux) return false;
//	if(isaux && !coind->aux.chainid) return false;

	return true;
}

///////////////////////////////////////////////////////////////////////////////

bool coind_validate_user_address(YAAMP_COIND *coind, char* const address)
{
	if(!address[0]) return false;

	char params[YAAMP_SMALLBUFSIZE];
	sprintf(params, "[\"%s\"]", address);

	json_value *json = rpc_call(&coind->rpc, "validateaddress", params);
	if(!json) return false;

	json_value *json_result = json_get_object(json, "result");
	if(!json_result) {
		json_value_free(json);
		return false;
	}

	bool isvalid = json_get_bool(json_result, "isvalid");
	if(!isvalid) stratumlog("%s: %s user address %s is not valid.\n", g_stratum_algo, coind->symbol, address);

	json_value_free(json);

	return isvalid;
}

///////////////////////////////////////////////////////////////////////////////

bool coind_validate_address(YAAMP_COIND *coind)
{
	if(!coind->wallet[0]) return false;

	char params[YAAMP_SMALLBUFSIZE];
	sprintf(params, "[\"%s\"]", coind->wallet);

	json_value *json;
	bool getaddressinfo = (strcmp(coind->symbol,"DGB") == 0);
	if(getaddressinfo)
		json = rpc_call(&coind->rpc, "getaddressinfo", params);
	else
		json = rpc_call(&coind->rpc, "validateaddress", params);
	if(!json) return false;

	json_value *json_result = json_get_object(json, "result");
	if(!json_result)
	{
		json_value_free(json);
		return false;
	}

	bool isvalid = getaddressinfo || json_get_bool(json_result, "isvalid");
	if(!isvalid) stratumlog("%s wallet %s is not valid.\n", coind->name, coind->wallet);

	bool ismine = json_get_bool(json_result, "ismine");
	if(!ismine) stratumlog("%s wallet %s is not mine.\n", coind->name, coind->wallet);
	else isvalid = ismine;

	const char *p = json_get_string(json_result, "pubkey");
	strcpy(coind->pubkey, p ? p : "");

	const char *acc = json_get_string(json_result, "account");
	if (acc) strcpy(coind->account, acc);

	if (!base58_decode(coind->wallet, coind->script_pubkey))
		stratumlog("Warning: unable to decode %s %s script pubkey\n", coind->symbol, coind->wallet);

	coind->p2sh_address = json_get_bool(json_result, "isscript");

	// if base58 decode fails
	if (!strlen(coind->script_pubkey)) {
		const char *pk = json_get_string(json_result, "scriptPubKey");
		if (pk && strlen(pk) > 10) {
			strcpy(coind->script_pubkey, &pk[6]);
			coind->script_pubkey[strlen(pk)-6-4] = '\0';
			stratumlog("%s %s extracted script pubkey is %s\n", coind->symbol, coind->wallet, coind->script_pubkey);
		} else {
			stratumlog("%s wallet addr '%s' seems incorrect!'", coind->symbol, coind->wallet);
		}
	}
	json_value_free(json);

	return isvalid && ismine;
}

void coind_init(YAAMP_COIND *coind)
{
	char params[YAAMP_SMALLBUFSIZE];
	char account[YAAMP_SMALLBUFSIZE];

	yaamp_create_mutex(&coind->mutex);

	strcpy(account, coind->account);
	if(!strcmp(coind->rpcencoding, "DCR")) {
		coind->usegetwork = true;
		//sprintf(account, "default");
	}

	bool valid = coind_validate_address(coind);
	if(valid) return;

	sprintf(params, "[\"%s\"]", account);

	json_value *json = rpc_call(&coind->rpc, "getaccountaddress", params);
	if(!json)
	{
		json = rpc_call(&coind->rpc, "getaddressesbyaccount", params);
		if (json && json_is_array(json) && json->u.object.length) {
			debuglog("is array...");
			if (json->u.object.values[0].value->type == json_string)
				json = json->u.object.values[0].value;
		}
		if (!json) {
			stratumlog("ERROR getaccountaddress %s\n", coind->name);
			return;
		}
	}

	if (json->u.object.values[0].value->type == json_string) {
		strcpy(coind->wallet, json->u.object.values[0].value->u.string.ptr);
	}
	else {
		strcpy(coind->wallet, "");
		stratumlog("ERROR getaccountaddress %s\n", coind->name);
	}

	json_value_free(json);

	coind_validate_address(coind);
	if (strlen(coind->wallet)) {
		debuglog(">>>>>>>>>>>>>>>>>>>> using wallet %s %s\n",
			coind->wallet, coind->account);
	}
}

///////////////////////////////////////////////////////////////////////////////

//void coind_signal(YAAMP_COIND *coind)
//{
//	debuglog("coind_signal %s\n", coind->symbol);
//	CommonLock(&coind->mutex);
//	pthread_cond_signal(&coind->cond);
//	CommonUnlock(&coind->mutex);
//}

void coind_terminate(YAAMP_COIND *coind)
{
	debuglog("disconnecting from coind %s\n", coind->symbol);

	rpc_close(&coind->rpc);
#ifdef HAVE_CURL
	if (coind->rpc.curl) rpc_curl_close(&coind->rpc);
#endif

	pthread_mutex_unlock(&coind->mutex);
	pthread_mutex_destroy(&coind->mutex);
//	pthread_cond_destroy(&coind->cond);

	object_delete(coind);

//	pthread_exit(NULL);
}

//void *coind_thread(void *p)
//{
//	YAAMP_COIND *coind = (YAAMP_COIND *)p;
//	debuglog("connecting to coind %s\n", coind->symbol);

//	bool b = rpc_connect(&coind->rpc);
//	if(!b) coind_terminate(coind);

//	coind_init(coind);

//	CommonLock(&coind->mutex);
//	while(!coind->deleted)
//	{
//		job_create_last(coind, true);
//		pthread_cond_wait(&coind->cond, &coind->mutex);
//	}

//	coind_terminate(coind);
//}






```

**Comment by jrick** [comment]
I don't know anything about the yiimp codebase, so no.

This won't be a problem only affecting decred.  When Bitcoin Core releases version 0.18, yiimp will need to be modified for the removal of the getaccountaddress RPC.  You should open an issue upsteam to get that resolved instead.

**Comment by goodthebest** [comment]
@davecgh @jrick ok how about this wallet issue?

When I run` ./dcrwallet ` without `--noservertls`, it works fine and same user and password go well? But get TLS error in dcrwallet log

![image](https://user-images.githubusercontent.com/1715740/40593970-353afb38-623d-11e8-9f70-45268df478da.png)

and with ` ./dcrwallet --noservertls`
![image](https://user-images.githubusercontent.com/1715740/40594005-6f63c02e-623d-11e8-9fac-b6ceba923c82.png)

**Comment by davecgh** [comment]
We've answered this several times now. You are not sending the RPC username and password, so it is failing authentication.

TLS comes before authentication, so in the first case, you're not even getting to the authentication check.  In the second case, because you've disabled TLS, you're failing the authentication check.
