### ISSUE TITLE
Insertion of transactions into the block is ordered incorrectly for stake transactions

### ISSUE THREAD

**Issue by cjepson** [decred/dcrd#120]
The block construction loop is supposed to pop transactions from the priority queue and assumes those transactions are in the correct dependency order. This results in errors like the one below being displayed in MINR=trace.

`15:45:56 2016-04-14 [TRC] MINR: Skipping tx 0c071761a917bb15f16746bb7f3baa54f4efa238
aa541e7dd818e0d08852f557 due to error in CheckTransactionInputs: transaction 0c07176
1a917bb15f16746bb7f3baa54f4efa238aa541e7dd818e0d08852f557 tried to double spend coin
s from transaction 74fa7f0a125f638c5578a761fbd9013e473067ef36c4d03bb222a964d22d1d2f`

**Comment by tuxcanfly** [comment]
Looking into this. Waiting for my testnet node to sync but I guess I can reproduce this by purchasing a ticket with a unconfirmed transaction.

**Comment by tuxcanfly** [comment]
This has been addressed in btcd (https://github.com/btcsuite/btcd/pull/759) Should be fixed in the next upstream sync.

**Comment by marcopeereboom** [comment]
This issue was fixed in btcd and will be picked up on the next sync.

**Comment by davecgh** [comment]
This has been resolved via upstream syncs as mentioned.
