### ISSUE TITLE
Version messages should include routable external addresses without UPnP or --externalip

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#1200]
If dcrd is listening on a globally routable IPv4 or IPv6 address, and is not configured to run behind a tor proxy, the address should be included in version messages during peer handshake.  Currently, version messages do not contain a routable address unless one was manually set with the externalip option or UPnP was enabled.

Since a dcrd node can be listening on multiple routable addresses, we may also want to consider modifying the protocol so multiple local addresses can be advertised to other peers, instead of just one from the version message.  This can improve the peer topography as e.g. IPv4 nodes on the network would also see advertised IPv6 addresses, and can provide these addresses in a getaddr response.

**Comment by davecgh** [comment]
This was implemented by #1522 and a few follow up PRs improving and cleaning it up.
