### ISSUE TITLE
[txscript] Complete removal of opcode by data tests for stake transactions

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#1204]
The `TestRemoveOpcodeByData` tests in `txscript/script_test.go` [here](https://github.com/decred/dcrd/blob/cc6993e61f5c17f5a309d3c002516cf88c7263f9/txscript/script_test.go#L3977-L3994) need to be completed for stake transactions as the linked comments indicate.

**Comment by vctt94** [comment]
Can I help with this issue?

**Comment by davecgh** [comment]
Thanks.  I assigned it to you.
