### ISSUE TITLE
[dcrjson] All extension commands should be combined with normal commands.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#1220]
The [dcrjson](https://github.com/decred/dcrd/tree/master/dcrjson) package was ported from the upstream btcsuite/btcd project (along with the rest of the code) where there is a distinction between the Bitcoin Core API and the extensions added by btcd and consequently has the files separated accordingly.

However, this scenario obviously does not apply to Decred.  Consequently, all of the commands in the extension files (e.g. `btcdextcmds.go`, `btcdextcmds_test.go`, `btcwalletextcmds.go`, `btcwalletextcmds_test.go`, `dcrwalletextcmds.go`, `dcrwalletextcmds_test.go`, etc) should be moved into the associated normal commands file and the extension files removed.

Along the same lines, `dcrdcmd{,_test}.go` should be moved into `chainsvrcmds{,_test}.go`.

**Comment by dnldd** [comment]
I'd like to work on this
