### ISSUE TITLE
How to achieve dcr_listTransactions

### ISSUE THREAD

**Issue by guanhui07** [decred/dcrd#1240]
Returns a list of transaction hashes for a given external or contract account

Parameters

String - the account or contract address

params: [
  "Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx"
]
Returns

DATA - A list of transaction hashes

How to achieve dcr_listTransactions，
This is very useful and much needed

**Comment by davecgh** [comment]
1) Enable the address index with `--addrindex`.
2) Use the [searchrawtransactions](https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.md#searchrawtransactions) JSON-RPC API.

**Comment by davecgh** [comment]
Another option is to install [dcrdata](github.com/decred/dcrdata) locally and use it's [REST API](https://github.com/decred/dcrdata#json-rest-api), specifically the `/address` family.

If you are able to trust 3rd-party services, it can also be accessed via the public explorer: https://explorer.dcrdata.org/address/Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx.
