### ISSUE TITLE
proxy= setting causing 100% cpu usage

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#129]
I was looking at
https://github.com/decred/dcrd/blob/master/sample-dcrd.conf
and noticed that it said "The SOCKS5 proxy above is assumed to be Tor ".
where its referring to above at "; proxy=127.0.0.1:9050".
Previously I was using "onion=127.0.0.1:9051", so I decided to switch to proxy= instead since thats what the sample conf says. I launched dcrd. I walked away for a few minutes and then heard the fans on my laptop kick in full speed. I came back and dcrd screen msgs say "DNS discovery failed on " many times. Okay, so I get that the proxy= line didnt work as described in the sample conf, but why is my cpu usage from dcrd at 100% on all four cores?

Two issues here.
1) proxy= is not working as described in the sample conf
2) Cpu load goes to 100%

**Comment by dajohi** [comment]
proxy= is used when you want all outbound connections to route via the proxy server.  onion= is used when you want .onion peers to route via the proxy server, but everything else directly.

Can you please post the actual logs being produced?

**Comment by raedah** [comment]
@dajohi actual log, as you requested.

18:53:25 2016-04-27 [INF] DCRD: Version 0.0.10-beta
18:53:25 2016-04-27 [INF] DCRD: Loading block database from '/home/x/.dcrd/data/mainnet/blocks_leveldb'
18:53:25 2016-04-27 [INF] BCDB: Address index synced and loaded to height 23194
18:53:25 2016-04-27 [INF] DCRD: Block database loaded with block height 23194
18:53:25 2016-04-27 [INF] DCRD: Loading ticket database from disk
18:53:33 2016-04-27 [INF] DCRD: Ticket DB loaded with top block height 23194
18:53:33 2016-04-27 [INF] BMGR: Generating initial block node index.  This may take a while...
18:53:34 2016-04-27 [INF] BMGR: Block index generation complete
18:53:35 2016-04-27 [INF] RPCS: RPC server listening on 127.0.0.1:9109
18:53:35 2016-04-27 [INF] RPCS: RPC server listening on [::1]:9109
18:53:35 2016-04-27 [INF] AMGR: Loaded 1007 addresses from file '/home/x/.dcrd/data/mainnet/peers.json'
18:53:35 2016-04-27 [INF] DISC: DNS discovery failed on seed mainnet-seed.decred.netpurgatory.com: dial tcp 127.0.0.1:9050: getsockopt: connection refused
18:53:35 2016-04-27 [INF] DISC: DNS discovery failed on seed mainnet-seed.decred.org: dial tcp 127.0.0.1:9050: getsockopt: connection refused
18:53:35 2016-04-27 [INF] DISC: DNS discovery failed on seed mainnet-seed.decred.mindcry.org: dial tcp 127.0.0.1:9050: getsockopt: connection refused
18:53:35 2016-04-27 [INF] DISC: DNS discovery failed on seed mainnet.decredseed.org: dial tcp 127.0.0.1:9050: getsockopt: connection refused

**Comment by alexlyp** [comment]
There is an upcoming merge from btcsuite (https://github.com/btcsuite/btcd/pull/653) that we hope will fix a lot of these issues.  Once that is in, I'll update this issue and others related to connmgr

**Comment by dajohi** [comment]
@raedah does this still occur on 0.2.0?

**Comment by dajohi** [comment]
Oh, it looks like it is unable to connect to the proxy at 127.0.0.1:9050.  It is just looping trying to connect to something.

**Comment by dajohi** [comment]
Going to close this since it looks like it is a connection to proxy issue.

**Comment by raedah** [comment]
@dajohi I tested on Version 0.2.0-beta and am still getting a failure. 

My settings are
```
onion=127.0.0.1:9050
torisolation=1
; proxy=127.0.0.1:9050
```

When I enable the proxy line, I get this failure.

```
15:08:02 2016-08-07 [INF] DISC: 0 addresses found from DNS seed mainnet-seed.decred.org
15:08:34 2016-08-07 [INF] BMGR: Lost peer 92.222.73.115:9108 (outbound)
15:08:34 2016-08-07 [INF] BMGR: Syncing to block height 52505 from peer 93.158.215.188:9108
15:09:05 2016-08-07 [INF] BMGR: Lost peer 93.158.215.188:9108 (outbound)
15:09:05 2016-08-07 [INF] BMGR: Syncing to block height 52505 from peer 185.39.195.83:9108
```
