### ISSUE TITLE
 can't understand createrawtransaction's txid

### ISSUE THREAD

**Issue by guanhui07** [decred/dcrd#1296]
[createrawtransaction](https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.md#createrawtransaction)

what is txid and come from ? i know is a hash , but how to get it.

**Comment by red010b37** [comment]
In btc, you would use the console do `listunspent` that will show you all the UTXO in your wallet including the txids.

But in Decred that functionality has been split out to the dcrwallet. Please see here how to get unspent outputs.

https://github.com/decred/dcrwallet/blob/master/rpc/documentation/api.md#unspentoutputs

**Comment by jrick** [comment]
You are referring to the `listunspent` JSON-RPC.  The linked documentation is for the gRPC server, not JSON-RPC.

**Comment by red010b37** [comment]
Well there you go. Live and learn. Thanks @jrick

**Comment by jrick** [comment]
`createrawtransaction` also works with unseen outputs (and transaction hashes) as well.  The output does not need to be in the `listunspent` result to create the raw transaction, but the network must see the output as an UTXO in order to actually publish and confirm the transaction.

**Comment by guanhui07** [comment]
curl -S  --tlsv1.2         --user "gF0r5BBFTEQxxxx=":"xxxxx"          --cacert "/root/.dcrd/rpc.cert"          --data-binary '{"id":1,"method":"createrawtransaction","params":[[{"Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx":0.49213337}]}'  https://localhost:9109

yes ,  I get the return 
hex-encoded bytes of the serialized transaction  from  JSON-RPC by the  command without param txid  , and  [#decoderawtransaction](https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.md#decoderawtransaction)
get the transaction data,
Then the next process, how to publish and confirm this transaction from JSON-RPC api

**Comment by waliguder** [comment]
@jrick @red010b37 @davecgh Can I create a raw transaction offline with code? Instead of passing dcrwallet because I don't want to synchronize nodes
