### ISSUE TITLE
getblocktemplate is broken in 0.1.0 because minor errors never get reset

### ISSUE THREAD

**Issue by ocminer** [decred/dcrd#130]
If dcrd has any kind of problem with it's internal transactions getblocktemplate fails completely forever with:

 "result":null,"error":{"code":-32603,"message":"unable to find input transaction abe5aa5e8eb8f7d98e457549c369ceb457cc8ca6912e2ddddafba7c0376851f1 for transaction d6b4f0763805debfb9b4be8cbcd2095d1a4269b6a14ff1dfa3a0cf3576b08713"},"id":"123"}

And this never gets reset.

This brakes the current stratum implementation.

**Comment by cjepson** [comment]
Yeah, getblocktemplate isn't production ready code unfortunately. Hope to clean it up soon for issues like this.

**Comment by tpruvot** [comment]
your current stratum use getblocktemplate ? where is the code ?
