### ISSUE TITLE
streamline setup for new users

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#131]
The current setup instructions require the user to specify user/pass pair for the rpc services. New users currently have to do this before they can make any use of their wallet. Most users are not running "multiuser machines", so it doesnt give them any security benefit. There were strong objects in irc to the term "default user/pass". The goal here is to require less steps for new users to get decred running and generate a new address.

**Comment by jolan** [comment]
I agree that the setup process should be made easier for new users.

For a fresh install it would be good to have dcrd generate random RPC credentials and write them to dcrd.conf and then have dcrwallet read dcrd.conf.

This would solve a major usability issue.

**Comment by raedah** [comment]
Another idea is to have the user just need to run one command to get started. Such as, just run dcrctl --terminal, and if dcrd/dcrwallet are not yet running, the user is asked if they would like these started for them. 
'dcrd service not running. Run it now (Y/n) ? '
'dcrwallet service not running. Run it now (Y/n) ? '

**Comment by raedah** [comment]
Noting upstream PR that address some of this.
Add automatic RPC configuration. #609

**Comment by alexlyp** [comment]
Just to update this issue:  our first attempt at streamlining installation/upgrade can be found here: https://github.com/decred/decred-release/tree/master/cmd/dcrinstall

This is our first planned step toward making a 1-click multiplatform installer.  We're open for suggestions on the way dcrinstaller "should" work or we can add different modes/options based on feedback/interest.

**Comment by dajohi** [comment]
Seems to be enough docs on installation.  Reopen a fresh issue if needed.
