### ISSUE TITLE
lost peers (9108 nodes) are never reconnected

### ISSUE THREAD

**Issue by tpruvot** [decred/dcrd#133]
This issue really bug me with some of my servers which don't have a direct connection to internet.

Even with the 9108 port forward, if i lose a peer, drcd never try to reconnect until i manally stop/restart it.

Attempt to manually reconnect to them via "node connect" also fails...
` dcrd-cli node connect stakepool.eu:9108
-8: peer exists as a permanent peer
`

Also, i don't really understand why i don't have any peers with ports different than 9108

Server config:  dcrwallet on another machine than dcrd, with different internet line

**Comment by chappjc** [comment]
This is what we talked about in IRC a little while so.  I confirm this is a problem.  If using `connect`,  you end up with dcrd being really fragile.

**Comment by tpruvot** [comment]
the problem is... if i'm temporary disconnected (here) i've 0 connections... permanently even if the internet connection is back and i waste my time here to do scripts to check that and to restart it...

**Comment by tpruvot** [comment]
The other one is the reverse (upgraded my vps wallet) :
00:35:13 2016-04-23 [INF] BMGR: Lost peer 62.210.253.159:9108 (outbound)

and never reconnected...

**Comment by chappjc** [comment]
Btw, my mainnet public nodes are decred.monkeyland.io, dcr.spool.cc and bt.monkeyland.io.  At least one of these had changed from what I posted in IRC about a week ago.  The last two are also testnet.

**Comment by dajohi** [comment]
@tpruvot does this bug still exist on latest dcrd, which has a new peer pkg.

**Comment by tpruvot** [comment]
it was fixed a few months ago... (not present in 0.1.4/0.1.5)
