### ISSUE TITLE
 DecodeAddress() failed: decoded address is of unknown format

### ISSUE THREAD

**Issue by JFixby** [decred/dcrd#1356]
Example of the address:
https://explorer.dcrdata.org/tx/b473afe8618dedcd261566509cf25d5a2c2bd9c459265b5c0ae3dcdcdc79cc88

[Test reproducing the issue](https://github.com/decred/dcrd/pull/1357/files#diff-1c7de8e42a32b863106dd6bdaef08159): 

```go
package dcrutil

import (
	"testing"
)

// TestDecodeAddress checks DecodeAddress is able to decode a real existing address
// https://explorer.dcrdata.org/tx/b473afe8618dedcd261566509cf25d5a2c2bd9c459265b5c0ae3dcdcdc79cc88
func TestDecodeAddress(t *testing.T) {
	addressToDecode := "b473afe8618dedcd261566509cf25d5a2c2bd9c459265b5c0ae3dcdcdc79cc88"
	_, err := DecodeAddress(addressToDecode)
	if err != nil {
		t.Errorf("DecodeAddress() failed: %v", err)
	}
}
```

Output:
```
=== RUN   TestDecodeAddress
--- FAIL: TestDecodeAddress (0.00s)
	decodeaddress_test.go:13: DecodeAddress() failed: decoded address is of unknown format: invalid format: version and/or checksum bytes missing
FAIL

Process finished with exit code 1
```

**Comment by alexlyp** [comment]
that's a txid not an address

**Comment by davecgh** [comment]
`b473afe8618dedcd261566509cf25d5a2c2bd9c459265b5c0ae3dcdcdc79cc88` is not a valid address.

**Comment by JFixby** [comment]
I'm sorry I was confused because dcrdata makes this call producing an error in logs.

**Comment by davecgh** [comment]
For reference, addresses are base58 and of the form `Ds??????`.  That D and s can be different depending on the type of address, but most common are `Ds` and `Dc`, and `Dk`.

**Comment by JFixby** [comment]
@davecgh thank you.
