### ISSUE TITLE
Variety of unusable commands

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#138]
getmempoolinfo, -32601: Method not found
gettxoutsetinfo, -1: This implementation does not implement wallet commands
getnetworkinfo, -1: Command unimplemented
getchaintips, -1: Command unimplemented
getblockchaininfo, -1: Command unimplemented

**Comment by kargakis** [comment]
I would expect to use getmempoolinfo everytime before making any kind of transaction (normal or ticket buy) assuming it showed me the average fees for both txns and tickets. Is there another way to do this currently?

**Comment by dajohi** [comment]
getmempoolinfo is now in current.  the others will be implemented when we can.  PRs are great too!
