### ISSUE TITLE
Too many packages in https://github.com/decred/dcrd/releases

### ISSUE THREAD

**Issue by lcgogo** [decred/dcrd#1393]
Hi,
I want to see the latest release of dcrd. However, when I open the https://github.com/decred/dcrd/releases I only find the sub module packages and the latest package is moved to the 2nd page automatically. I think it is not a good idea to package each sub module and list them all in release page.
https://github.com/decred/dcrd/releases

**Comment by davecgh** [comment]
Unfortunately, the Go module versioning system requires semantic versions for the tags in order for it to work correct, and github automatically lists semantic tags there without any way to suppress them (as far as I know).

That said, you can see the latest release of the actual software with:
https://github.com/decred/dcrd/releases/latest

As far as release candidates, you'll, unfortunately, have to search through as you've described.
