### ISSUE TITLE
ListTransactions returns a grouping error

### ISSUE THREAD

**Issue by ByronAP** [decred/dcrd#14]
{"result":null,"error":{"code":-4,"message":"Transactions are not yet grouped by account"},"id":1}

**Comment by jrick** [comment]
This should be filed under dcrwallet, but anyways...

You have to use * to specify all accounts instead of one in particular.  When typing the command in a shell prompt, use `'*'`, `"*"`, or '\*' to escape the asterisk so the shell doesn't expand it to all files in your current directory.

**Comment by jcvernaleo** [comment]
@ByronAP did @jrick's advice work for you?

**Comment by alexlyp** [comment]
this should be in dcrwallet, plus i believe the account grouping issues have been fixed.  Closing
