### ISSUE TITLE
Websocket client reconnection failure

### ISSUE THREAD

**Issue by cjepson** [decred/dcrd#146]
Sometimes websocket clients connect to dcrd, fail to reconnect, cycle endlessly through ports, and finally stop attempting to reconnect. This results in websocket clients, such as wallet, never reconnecting and failing.

> 06:52:48 2016-04-30 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:36242
> 06:52:48 2016-04-30 [INF] RPCS: New websocket client 127.0.0.1:36243
> 06:52:48 2016-04-30 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:36243
> 06:52:48 2016-04-30 [INF] RPCS: New websocket client 127.0.0.1:36244

**Comment by raedah** [comment]
here is more info from IRC:
``
<Epsylon3> another stakepool wallet stuck this morning
<Epsylon3> tried "killall -6 dcrd" but no stacktrace
<Epsylon3> dcrwallet has a full log of that :
<Epsylon3> 08:10:42 2016-04-30 [ERR] CHNS: Websocket receive error from 127.0.0.1:9109: read tcp 127.0.0.1:57102->127.0.0.1:9109: read: connection reset by peer
<Epsylon3> 08:10:42 2016-04-30 [ERR] DCRW: Unable to open connection to consensus RPC server: the client has been disconnected
<Epsylon3> 08:10:42 2016-04-30 [INF] DCRW: Attempting RPC client connection to 127.0.0.1:9109
<Epsylon3> 08:10:42 2016-04-30 [INF] CHNS: Established connection to RPC server 127.0.0.1:9109
<Epsylon3> truncated
<Epsylon3> and dcrd had the error, too much websockets... (25)
<Epsylon3> 06:52:48 2016-04-30 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:36242
<Epsylon3> 06:52:48 2016-04-30 [INF] RPCS: New websocket client 127.0.0.1:36243
<Epsylon3> 06:52:48 2016-04-30 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:36243
<Epsylon3> 06:52:48 2016-04-30 [INF] RPCS: New websocket client 127.0.0.1:36244
<Epsylon3> same, truncated...
<Epsylon3> was unable to dcrd-cli stop
<Epsylon3> dcrctl reported stopping... but never stopped...
<Epsylon3> cpu 100% also
<raedah> Epsylon3, check your dcrd.conf,  ; rpcmaxwebsockets=25
<raedah> Epsylon3, still sounds like a bug if it ends with a 100% cpus condition. Whats the issue number? Something simliar, https://github.com/decred/dcrd/issues/129  "proxy= setting causing 100% cpu usage"
* _ingsoc (~ingsoc@unaffiliated/ingsoc/x-8595135) has joined #decred-dev
<Epsylon3> no proxy
<Epsylon3> its the second machine which has this problem
<Epsylon3> stakpool wallet
<Epsylon3> that means sometimes websocket connections are "stuck"
<Epsylon3> and never closed
<Epsylon3> i guess the 100% cpu is the wallet trying to reconnect
<Epsylon3> or any notified app
<Epsylon3> but its only dcrd which is at 100% in this case
<Epsylon3> maybe it was after the stop command, unsure
``

Seems likely related to https://github.com/decred/dcrd/issues/129 , as they both have to do with network connections and both cause 100% cpu load.

**Comment by alexlyp** [comment]
This issue with also be helped by connmgr (btcsuite#653).  Once that PR is merged I will update this issue

**Comment by raedah** [comment]
@alexlyp did that merge happen?

**Comment by alexlyp** [comment]
@raedah Yup that was merged some time ago, as such closing this issue.  We are currently synced with btcd through Aug 19 (mempool refactor)
