### ISSUE TITLE
dcrctl -l lists commands which are not implemented by dcrd/dcrwallet

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#1472]
For example, `importaddress` is listed in this output, but is not implemented by dcrwallet.

This happened because dcrctl is a fork of btcctl, and although these same methods are (or were) not implemented by btcd/btcwallet, support for the methods were added to the rpcclient package for usage with bitcoind, and subsequently supported by btcctl.

It should be safe to remove all unimplemented methods from our rpcclient package, but care should be taken to do this as a v2 module.

**Comment by ggoranov** [comment]
These are the Wallet Server Commands listed by dcrctl but seems not supported by dcrwallet.
```
createrawssgentx [{"amount":n.nnn,"txid":"value","vout":n,"tree":n},...] votebits
createrawssrtx [{"amount":n.nnn,"txid":"value","vout":n,"tree":n},...] (fee)
createrawsstx [{"txid":"value","vout":n,"tree":n,"amt":n},...] amount [{"addr":"value","commitamt":n,"changeaddr":"value","changeamt":n},...]
createvotingaccount "name" "pubkey" (childindex=0)
dropvotingaccount
estimatepriority numblocks
fundrawtransaction "hexstring" "fundaccount" ({"changeaddress":changeaddress,"feerate":feerate,"conftarget":conftarget})
importaddress "address" (rescan=true)
importpubkey "pubkey" (rescan=true)
sendtossgen "fromaccount" "tickethash" "blockhash" height votebits ("comment")
sendtossrtx "fromaccount" "tickethash" ("comment")
sendtosstx "fromaccount" amounts [{"txid":"value","vout":n,"tree":n,"amt":n},...] [{"addr":"value","commitamt":n,"changeaddr":"value","changeamt":n},...] (minconf=1 "comment")
setbalancetomaintain balance
setticketmaxprice max
verifyseed "seed" (account)
```

Some of them are implemented by rpcclient (like importaddress) but other are not (like setbalancetomaintain)

**Comment by ggoranov** [comment]
@jrick 
As a first step I'm going to update `walletsvrcmds.go / walletsvrcmds_test.go` to remove unsupported cmds , if that makes sense for you?

**Comment by jrick** [comment]
Not all of those are wallet methods.  For example, createrawsstx (and others) are implemented by dcrd's JSON-RPC server.

This list also contains several methods which we have plans to implement in dcrwallet.  The methods were added to dcrjson for the required library support, but it seems as if support for the methods in rpcclient was added early.  You'll have to discuss this with @davecgh over whether these should be kept or removed in the cleanup, but if they are removed, keep in mind they will need to be added back eventually.

Here's the list of methods that actually can be removed:

```
importaddress
importpubkey
sendtossgen
sendtossrtx
sendtosstx
setbalancetomaintain
setticketmaxprice
```

**Comment by dnldd** [comment]
`createrawssgen` is also scheduled to be removed in the next version update: https://github.com/decred/dcrd/commit/4a503a0f12e7d08f30d1ec7013463a1a377463d2. I think `createrawssrtx` should be up for removal as well since revocations created are per specific consensus conditions and shouldn't be triggered by RPC. Let's have @davecgh chime in when he's available before you act on this.

**Comment by davecgh** [comment]
I disagree about `createrawssrtx`.  It's true there are specific conditions, but a revocation can be created at any point after a ticket is missed or expired, until it's already been revoked of course.  The problem with `createrawssgen` was that votes are extremely time sensitive and an implementation can't possibly cast a reasonable vote without understanding and examining a block.

As far as the removal of unsupported commands, [these maps](https://github.com/decred/dcrd/blob/b413da23503e06bb1928057e021244fa04ec37fb/rpcserver.go#L171-L304) define what is used by dcrd.

Also, there will be things used in `dcrjson` by [rpcclient](https://github.com/decred/dcrd/tree/b413da23503e06bb1928057e021244fa04ec37fb/rpcclient), so removal of them from `dcrjson` will also require removal of them from there.  That also implies major version bumps for both the `dcrjson` and `rpcclient` modules.

**Comment by davecgh** [comment]
I agree with the list provided @jrick in terms of what can be removed.

**Comment by ggoranov** [comment]
Another subtask for this cleanup would be to update the docs of [dcrctl commands](https://docs.decred.org/getting-started/dcrctl-rpc-commands/). 
I'm not sure at what stage this should be done.

**Comment by davecgh** [comment]
Yes, the docs should be updated as well.  That is a separate repo, however, so I think an issue against that repository should be opened.

**Comment by jrick** [comment]
This is resolved.  Removing these commands from the docs site is a separate issue.
