### ISSUE TITLE
[rpcserver] Implement getblockchaininfo RPC.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#1475]
In order to provide additional details about the current state of the blockchain, a new RPC named `getblockchaininfo` should be implemented.

The command for this RPC is [already defined](https://github.com/decred/dcrd/blob/979d21f6f3695f0081ccc0c55994ecdff39b5a27/dcrjson/chainsvrcmds.go#L352) along with its [result](https://github.com/decred/dcrd/blob/master/dcrjson/chainsvrresults.go#L94-L102), however, it is [not implemented](https://github.com/decred/dcrd/blob/979d21f6f3695f0081ccc0c55994ecdff39b5a27/rpcserver.go#L302) in the dcrd RPC server and the current results don't contain all of the information pertinent to Decred.

The result struct should be modified to add the following fields:
- `initialblockdownload` (`bool`) - Best guess as to whether the initial block download process is underway
- `chainwork` (`string`) - Hexadecimal value that represents the total work in the current best chain
- `maxblocksize` (`uint32`) - The maximum allowed block size

There should probably also be some additional information regarding the state of the various DCPs, but the best way to present that information needs to be thought through.

It should also be noted that the `verificationprogress` field currently has no code to determine it, so a best guess will need to be determined in the RPC server for now.  In the future, this can be significantly improved through modification to the `blockchain` module, but that is beyond the scope of this issue.

Don't forget when working on this the [JSON-RPC API](https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.md) documentation and [RPC server help](https://github.com/decred/dcrd/blob/master/rpcserverhelp.go) needs to be updated accordingly as well as bumping the RPC server version and potentially the `dcrjson` module version depending on what other changes have happened since the last module release.

**Comment by jrick** [comment]
Does `initialblockdownload` indicate whether this is the *first* sync, and the daemon has never been up to date with the network, or if it is behind the network and must catch up (perhaps after being down for maintenance)?

**Comment by davecgh** [comment]
It indicates the latter.  IBD is really more of a "catchup" mode as opposed to necessarily really being the _first_ sync.

**Comment by davecgh** [comment]
@dnldd Is implementing this.

**Comment by davecgh** [comment]
In regards to showing the status of the DCPs, I suspect the following will do:

```JSON
{
...,
deployments: {
	"sdiffalgorithm": {
		"status": "active",
		"since": <blockheight>,
		"starttime": ...,
		"expiretime": ...,
	},
	"maxblocksize": {
		....,
	},
	"anotherdeployment": {
		...,
	},
 }
```

However, the exact fields will probably change depending on the status, such as if it's in progress, versus rejected, versus not started, etc.

**Comment by dmigwi** [comment]
I hope you guys don't plan to do away with the previous height implementation that returned the latest best block to be sync'd by dcrd. This new height implementation and the previous implementation are equally important but for different use case scenarios.

**Comment by davecgh** [comment]
The existing RPCs `getbestblock`, `getblockcount`, and `getbestblockhash` are not going away.

**Comment by jrick** [comment]
@dmigwi which method are you referring to? The peer heights from getpeerinfo?

**Comment by chappjc** [comment]
Not to worry.  That's probably one of the most widely used RPCs, period.

**Comment by dnldd** [comment]
Sample response from simnet tests.

```
ctl getblockchaininfo                                                                                                                                                             
{
	"chain": "simnet",
	"blocks": 463,
	"headers": 463,
	"bestblockhash": "000043c89f6e227c9d90a5460aff98b662e503b9a394818942bdd60709cbb8aa",
	"difficulty": 520127421,
	"verificationprogress": 0,
	"chainwork": "0x23c0e40",
	"initialblockdownload": false,
	"maxblocksize": 1000000,
	"deployments": {
		"lnfeatures": {
			"status": "started",
			"since": 463,
			"starttime": 0,
			"expiretime": 9223372036854775807
		},
		"maxblocksize": {
			"status": "started",
			"since": 463,
			"starttime": 0,
			"expiretime": 9223372036854775807
		},
		"sdiffalgorithm": {
			"status": "started",
			"since": 463,
			"starttime": 0,
			"expiretime": 9223372036854775807
		}
	}
}
```
