### ISSUE TITLE
listsinceblock rpc call not showing 0 confirmations transactions

### ISSUE THREAD

**Issue by santins77** [decred/dcrd#1501]
Since I have updated to version 1.3.0 the behaviour of listsinceblock rpc call has changed and is not showing transactions with 0 confirmations. This change is not documented in the changelog of the version.
When I call listtransactions I can see those transactions so they are already in the blockchain

**Comment by davecgh** [comment]
This is filed against the wrong repository.  `listsinceblock` is a wallet RPC and thus is not provided by `dcrd`.  The correct repository is https://github.com/decred/dcrwallet.

Please refile it there so the wallet team can look into it.
