### ISSUE TITLE
Tag 1.3.0

### ISSUE THREAD

**Issue by alexbarnsley** [decred/dcrd#1510]
Currently the Go `dep` dependency manager picks up 1.2.0 as the latest version which is an outdated version. Please can you tag 1.3.0, thanks.

**Comment by davecgh** [comment]
dcrd no longer uses or supports dep.  It has transitioned to Go modules.  See the [README](https://github.com/decred/dcrd/blob/master/README.md#build-from-source-all-platforms) for build details or the [Go module documentation](https://github.com/golang/go/wiki/Modules).

**Comment by davecgh** [comment]
I'd also like to add that you can find a list of the supported modules along with a hierarchy diagram in the [docs/README](https://github.com/decred/dcrd/tree/master/docs).
