### ISSUE TITLE
Add chainwork to wire.MsgBlock

### ISSUE THREAD

**Issue by buck54321** [decred/dcrd#1523]
The chainwork was recently added (#1498) to the appropriate `dcrjson` types, but not `wire.MsgBlock`. The chainwork values are stored in memory, not as part of the encoded block, so when a `MsgBlock` is created via deserialization, the chainwork value is not immediately available. If all blocks are stored in memory (are they?) via `blockchain.blockNode`s, which have the `workSum` = chainwork already, can chainwork be populated appropriately in calls for `MsgBlock`s?

**Comment by jrick** [comment]
The total work is not part of the block structure.  It is a sum of all of the work of all blocks in a chain.  It must be calculated by software, and can not be trusted as a deserialized field from peers.
