### ISSUE TITLE
version 4 database not supported yet

### ISSUE THREAD

**Issue by kiahmed** [decred/dcrd#1525]
get this when build and tried to run the latest on existing data directory ..any idea what it means? I dont want to lose the blockchain that's been upto date
[ERR] DCRD: Unable to start server on [:9108]: Upgrade from version 4 database not supported yet

**Comment by davecgh** [comment]
It's in a transition right now.  You'll either need to use PR #1520, wait for that PR to land to master (which will probably be tomorrow), or do a full chain reload.

**Comment by kiahmed** [comment]
well, I was only updating to resolve rpc api mismatch wanted 4, it still exposed 3
