### ISSUE TITLE
php use websocket error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

### ISSUE THREAD

**Issue by chenyunecjtu** [decred/dcrd#1535]
$header = [ 'tls' => [
            'local_cert'        => $cert,
//            'peer_fingerprint'  => openssl_x509_fingerprint(file_get_contents($key)),
            'verify_peer'       => false,
            'verify_peer_name'  => false,
            'allow_self_signed' => true,
            'verify_depth'      => 0 ]];

**Comment by davecgh** [comment]
There isn't much information to go in here, such as the specific modules you using and such, but I'm going to guess that whatever you're using either does not support the curve that is required, or it needs to be configured specifically to support it.  For example, with older versions of the [node.js](https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.md#82-example-nodejs-code) connection code, it is necessary to set the `ecdhCurve: 'secp521r1'` option.
