### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [decred/dcrd#1554]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support DCR on our service for a long time and we have been exchanging DCR for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by degeri** [comment]
Hi this is not supposed to be filed under dcrd. Please come chat with us in either slack or matrix. 

https://www.decred.org/community/


Usually a community member will check out the platform and then add to our website. 

Please close this issue.

**Comment by SimpleSwap** [comment]
Ok. Thanks for help. We will contact you there.
