### ISSUE TITLE
Track tickets with non-approved inputs separately in mempool

### ISSUE THREAD

**Issue by matheusd** [decred/dcrd#1555]
Tickets can only be included in blocks if all of their inputs are in approved chains (ie: they have at least 2 confirmations and the second confirmation approved the previous block).

The current ticket purchasing software usually publishes tickets along with a split transaction so that the inputs to the tickets are correctly sized. This causes tickets to enter and remain in the mempool while they are technically unmineable.

Tickets are currently considered for inclusion pretty much all the way through block template generation, when they are then skipped over, which is less than ideal. This also has repercussions to fee estimation, due to skewing the delay from mempool entering to mining of ticket transactions.

Ideally, the mempool should track tickets as a new type of dependent transaction (or maybe as orphans), such that they are not considered for inclusion in block templates and are not considered part of the mempool for reasons of fee estimation.

**Comment by sefbkn** [comment]
Picking this up.
