### ISSUE TITLE
Miner can not get new work(with new height) immediately after found new block. 

### ISSUE THREAD

**Issue by DinoStray** [decred/dcrd#1572]
The miner found a new block, commit the block success.
Then what should the miner do next?
The miner can not get new work, because the new block still wait enough votes.
Before get enough votes, get work still return the old height.

**Comment by liukun** [comment]
It's reasonable, as the committed block at height H may not get enough votes for next height H+1, so miners can still mine another block at height H which may get enough votes then. That is to say if PoS
stopped, PoW will be stuck at the same height.
