### ISSUE TITLE
confusing on vote

### ISSUE THREAD

**Issue by tpkeeper** [decred/dcrd#1640]
![image](https://user-images.githubusercontent.com/7260146/53482744-e877bc80-3aba-11e9-9558-815390646af1.png)
hi, what  the "Last Block" "valid " mean?   voters vote on the parent block?

**Comment by lealife** [comment]
The vote tx validate the last block, and the result is valid

**Comment by jrick** [comment]
That is correct, but in the future, please don't use the issue tracker for general questions.  Instead, you can ask questions in our public chatrooms: https://www.decred.org/community/
