### ISSUE TITLE
chaincfg: Convert Network Definitions To Functions

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#1667]
Since the block one ledger changes described by #1659 constitutes a major API break and therefore will require a new v2 module anyway, the definitions of the default parameters should be changed from variables to functions which return a new instance of the relevant parameters as part of moving to the new version API since that is also a major API break.

The reasoning is as follows:

- The exported package-level globals are subject to mutation which can easily cause subtle and hard to find bugs.  By returning a new instance, that is no longer possible. The caller can keep the instance and pass it to the relevant functions (most code already does this anyway).
- Many of the fields are defined in terms of others, but due to struct being defined at the top level, it's not possible to reference other fields within it.  A function would allow that.
- It will permit the unexported global variables to be defined inside the func thereby reducing the number of package globals.
- It will allow creating a base set of parameters that each one could build on which would likely make it more clear exactly what the differences are between the networks.

**Comment by JFixby** [comment]
Here is a draft PR proposing a possible solution: https://github.com/decred/dcrd/compare/master...JFixby:chaincfg
Please let me know if you like it or not.

**Comment by davecgh** [comment]
Oh man, I feel bad now that I forgot to mark this as assigned to me.  I already have a local branch that takes care of this as well as #1659 (which I did comment on that I was working on), because it all has to be done at the same time due to the major module version bump.  I'll push it as a WIP here in a bit.

Anyway, I'll give you some feedback on your draft since you took the time to work on it and it'll be instructive for any type of future work in the same area:

- Major breaking changes to the API of a module such as here (removing exported funcs or constants, changing the type of the exported function parameters, interface fields, etc), have to follow a specific pattern to ensure existing code continues to compile and introduce a new module version.
- There should not ultimately be an interface in `chaincfg` as that wouldn't give the desired goal of breaking the dependency up since changing the definition of the interface in `chaincfg` would still require everything else that depends on it to bump major if it's part of their API.  The interfaces have to be on the _recipients_ (see #1696) in order to break the dependency as the goal is here.  The typical Go mantra in regards to this is "Return structs, accept interfaces".  There are always exceptions of course, but that is right the vast majority of the time.
- The draft branch is not actually doing what this issue calls for which is to return the params via functions.  Notice it still has `var MainNetParams = &mainNetParams{}` which is effectively the same as what it is now.

Something that your draft branch does that I didn't do in my current WIP branch which we might want to discuss for a v3 of the module is making all fields private and then providing accessor methods.  I'd like to hear some feedback on others that work on the code base what their thoughts are on that as it has pros and cons.

Something to keep in mind is that we can always add new functions to structs (but not to interfaces) without having to bump the major as that doesn't break existing callers.

**Comment by davecgh** [comment]
I should also note that, as discussed in Matrix, part of this change will also be to remove the registration capabilities from `chaincfg` since that also requires a major version bump.

**Comment by davecgh** [comment]
I have pushed the aforementioned WIP PR as #1698.

**Comment by JFixby** [comment]
Copy that. Thank you, Dave.
