### ISSUE TITLE
connmgr: Cannot remove unresponsive outbound peer

### ISSUE THREAD

**Issue by matheusd** [decred/dcrd#1725]
Steps to reproduce:

- Start dcrd with `--nodnsseed --connect 0.0.0.0 --debuglevel "CMGR=debug"`
- Attempt to connect to an unresponsive port `dcrctl addnode 127.0.0.1:2030 add`

There's now no way to remove the pending connection attempt to `127.0.0.1:2030`.

#1724 adds the ability to cancel a pending outbound connection during its retry backoff in the connection manager, however the server does its own peering management which means a corresponding `dcrctl addnode 127.0.0.1 remove` does _not_ work.

While the corresponding connReq will eventually reach the largest retry interval (5 minutes) and while there it will consume very little resources, it would be better to have the ability to completely remove a connection attempt without having to restart the server.

**Comment by RyanBRiley** [comment]
I'd like to take this one if it is still available
