### ISSUE TITLE
sync stop at 342913

### ISSUE THREAD

**Issue by bitcodernull** [decred/dcrd#1737]
May 10 15:19:11 enode2 dcrd[32693]: 2019-05-10 15:19:11.337 [INF] BMGR: Rejected block 0000000000000000187d00f495bc73394a70aad2c8761c6d2ccc584b90cbc967 from 23.105.202.144:9108 (outbound): previous block 00000000000000000a2d564bbe2ecf3fb982d19bb528db0302d903293b99ed33 is known to be invalid

**Comment by davecgh** [comment]
Have you upgraded to the latest version 1.4.0?  The new rules have now activated which means older versions must be upgraded.

**Comment by davecgh** [comment]
I should also note that since the block is now marked as invalid, after upgrading to v1.4.0, you're also going to have to delete the blockchain and redownload it under the new version since upgrading can't undo a block that your database now believed to be invalid.

**Comment by davecgh** [comment]
I'm going to close this because it is surely a case of not having updated.  Block 342914 is the first block that is rejected by old versions and acceped by new versions as a result of voting in the new rules.
