### ISSUE TITLE
One last "processed blocks" message is not printed after sync

### ISSUE THREAD

**Issue by xaur** [decred/dcrd#1746]
After startup, after the sync finishes, last "processed blocks" message is not printed as demonstrated by the log below.

Time deltas are relative to previous log message.

```
+   00s [INF] AMGR: Loaded <n> addresses from file ...
        [INF] BMGR: New valid peer ...
        [INF] BMGR: Syncing to block height 345120 from peer ...
        [INF] BMGR: New valid peer ...
        [INF] CMGR: <n> addresses found from DNS seed ...
+   03s [INF] BMGR: Processed 2 blocks in the last 10s (..., height 344284, ...)
+   10s [INF] BMGR: Processed 133 blocks in the last 10s (..., height 344417, ...)
+   10s [INF] BMGR: Processed 206 blocks in the last 10s (..., height 344623, ...)
+   06s [INF] CHAN: Adding orphan block ...
+   04s [INF] BMGR: Processed 227 blocks in the last 10s (..., height 344850, ...)
```

Now the sync finishes and the fan spins down. dcrd reached block 345120 but there is no "Processed..." message printed within 10 seconds to report about 269 processed blocks and the current height 345120. Next message to print the height will be when another new block is received.

```
+01m34s [INF] <peer messages continue>
+10m50s [INF] BMGR: Processed 270 blocks in the last 12m24s (..., height 345121, ...)
+   20s [INF] BMGR: New valid peer ...
+   30s [INF] BMGR: Processed 1 block in the last 50s (..., height 345122, ...)
```

dcrd v1.4.0 release

**Comment by davecgh** [comment]
Thanks for opening this.  I've noticed this before too.  This would be a good starter issue.

**Comment by PatelProjects** [comment]
Been working on this as my first issue. Would we like to log the standard "Processed..." message or should we add something notifying the user that the sync is complete (like a "Sync Complete" message or something of that sort)?

**Comment by vgtom** [comment]
I guess this issue is still not resolved and I want to take it up as my first issue? Is that OK?
