### ISSUE TITLE
Update TLS curve

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrd#1753]
TLS certs generated by dcrd use P521.

https://github.com/decred/dcrd/blob/5048959fdcf640da10091789871778131f9c27e3/rpcserver.go#L6411

https://github.com/decred/dcrd/blob/5048959fdcf640da10091789871778131f9c27e3/cmd/gencerts/gencerts.go#L65

> P224 and P256 are the only two curves with constant-time implementations in crypto/elliptic

> what i would actually prefer is to switch to X25519

[Quotes are from Matrix](https://matrix.to/#/!HEeJkbPRpAqgAwhXWO:decred.org/$15590515064744gcmhy:decred.org?via=decred.org&via=matrix.org&via=zettaport.com)

**Comment by davecgh** [comment]
I personally would prefer to stick with `P521` since it has much stronger keys versus the weaker `P224` and `P256` supposedly constant time, but not really constant time, curves.
