### ISSUE TITLE
rpcclient: ping pong polling

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrd#1878]
It seems rpcclient relies on gorilla/websocket to tell it when a disconnect has happened.  TBH I'm not exactly sure what the timing is for this. However, greater minds have told me that a reliable ping, pong is needed to ensure disconnects are caught in a timely manner.  There is related discussion and sample code here https://github.com/decred/dcrdata/issues/1541

**Comment by davecgh** [comment]
I believe there is already a TODO in the `rpcclient` code to handle periodic automatic ping/pong, but nobody has taken it on to date.  I agree that it is the correct approach though to help keep the connection alive.
