### ISSUE TITLE
mining: Improve block template generator test coverage

### ISSUE THREAD

**Issue by sefbkn** [decred/dcrd#1884]
The block template generator does not have high test coverage. As a result, making non-trivial changes to the mining strategy without breaking assumptions is more difficult than it could be. There need to be additional tests around `NewBlockTemplate` to anchor existing behavior and related consensus rules. Splitting this work across multiple pull requests should make changes easier to review since there are many scenarios to account for.

This issue partially blocks #1556

**Comment by davecgh** [comment]
Agreed that this would be ideal.  I suspect that splitting out the mining code into the the mining package would significantly help make it more testable.

**Comment by rstaudt2** [comment]
A testing framework was added for this in https://github.com/decred/dcrd/pull/2480, and additional test coverage was added alongside the automatic ticket revocations agenda in https://github.com/decred/dcrd/pull/2720.  As of https://github.com/decred/dcrd/pull/2720, this hits about 70% coverage of `NewBlockTemplate`:
```
go test -run="TestNewBlockTemplate" -coverprofile=cov.out &&
go tool cover -func=cov.out | grep -E "NewBlockTemplate"

github.com/decred/dcrd/internal/mining/mining.go:1169:    NewBlockTemplate    69.8%
```

Still plenty of room for further coverage, but linking work that has already been completed toward this.
