### ISSUE TITLE
altdnsnames argument is not working

### ISSUE THREAD

**Issue by EminBudak** [decred/dcrd#1912]
I want to call remote RPC connection and I removed old certificate then I run with altdnsnames argument. The new certificate has been created but I still cannot call RPC connection it gives an error like that

`
Error: Peer certificate cannot be authenticated with given CA certificates
`

`/opt/decred/dcrd --altdnsnames="xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx"
`

My Decred Release
https://github.com/decred/decred-release/releases/download/v1.4.0/dcrinstall-linux-amd64-v1.4.0

**Comment by davecgh** [comment]
Not sure how I missed this, but I just say it.  The parameter only works when you the certificate is first created.  You'll need to delete the `rpc.cert` and `rpc.key` files so they can be recreteated, then start dcrd with that flag in question so the new certs are generated with the additional names.

**Comment by chappjc** [comment]
The UX is less than ideal though.  An improvement would be to warn or error if the `altdnsnames` flag is given, but the certs already exist.

**Comment by davecgh** [comment]
Agreed it would be nicer to give a warning.

**Comment by chappjc** [comment]
Still, it's easier than using gencerts.  :)

**Comment by davecgh** [comment]
Opened #1971 to add a warning.
