### ISSUE TITLE
getinfo RPC Balance does not match getbalance call

### ISSUE THREAD

**Issue by buzztiaan** [decred/dcrd#2]
$ ./linux-amd64/dcrctl --testnet --wallet getbalance
46.00001001

$ ./linux-amd64/dcrctl --testnet --wallet getinfo | grep balance
  "balance": 0,

**Comment by jcvernaleo** [comment]
So, getbalance defaults to showing spendable only.  getinfo is showing the locked balance.
jcv@yoshi ~ $ dcrctl --wallet getbalance default 1 "spendable"
151.08521973
jcv@yoshi ~ $ dcrctl --wallet getbalance default 1 "locked"
1729.00867405
jcv@yoshi ~ $ dcrctl --wallet getinfo | grep balance
  "balance": 1729.00867405,
But I agree that it would make more sense for getinfo to match what balance defaults to.  I'm fixing it in the code now so next release they will match.

**Comment by jcvernaleo** [comment]
Oh and thanks for catching that!
