### ISSUE TITLE
When config file is specified on command line, but not found it, should be a critical error

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#200]
The following should be a critical error, not a warning.  The daemon instead starts with unintended settings (default, another file?).  If `-C` is used, that file should be used or dcrd should fail to start.  Similar to dcrd https://github.com/decred/dcrwallet/issues/233

```
dcrd -C /home/dcrd/.dcrd/dcrd-mainnet.conf
[WRN] DCRD: open /home/dcrd/.dcrd/dcrd-mainnet.conf: no such file or directory
```

**Comment by chappjc** [comment]
This applies to dcrctl too.  And it gets worse.  See if you can spot the problem:

    dcrctl -c ~/.dcrctl/dcrctl2.conf --wallet getstakeinfo

That's the right .conf, I just used a lowercase "c" instead of "C".  The output says nothing about the incorrect argument:

    Post https://localhost:9110: dial tcp 127.0.0.1:9110: getsockopt: connection refused

So this applies to the `-c, --rpccert` option too.

**Comment by dajohi** [comment]
@chappjc please test with this PR.

**Comment by chappjc** [comment]
It handles a bad dcrd.conf:

    Error parsing config file: open C:\crap.conf: The system cannot find the file specified.

However, you are now **forced** to have a dcrd.conf.  Previously there was nothing wrong with starting with everything configured on the command line.

**Comment by dajohi** [comment]
Pushed a fix.  Try again.

**Comment by chappjc** [comment]
Thanks.  But it will be a couple hours before I can test.
