### ISSUE TITLE
When stakeholders will vote to activate the network 

### ISSUE THREAD

**Issue by ruyichang** [decred/dcrd#2020]
hello, when and which block height do this activate intestnet？
Mainet successful on-chain votes take a minimum of 3 months to fully activat?

**Comment by degeri** [comment]
I suggest you join one of the chat platforms to ask these questions. 

Opening issues to ask these general questions is not cool. Please close this.

**Comment by davecgh** [comment]
I'm not entirely sure what your first question is asking, but I'm guessing you're talking about the header commitments vote.  If so, that is already activated on testnet.

For your second question, yes that's right.  It typically takes around 1 month for the upgrade to happen before voting starts, 1 month for the vote to take place, and 1 month for the lockin period after the vote passes.

Also, for future reference, as @degeri notes, general questions not specifically related to dcrd that aren't issues should be asked via one of the chat platforms such as https://chat.decred.org/ or https://reddit.com/r/decred.
