### ISSUE TITLE
test rpcserver handlers

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrd#2069]
Only one JSON rpcserver handler has a test.  I would assume that adding tests for all handlers to rpcserverhandlers_test.go is appropriate and wanted.

If so, there is the problem of needing an *rpcServer type to satisfy the handlers. While this is not a big deal in some cases, there are handlers like createrawssrtx that need to look up a transaction from the blockchain. My solution to that particular function and others using rpcServer.cfg.Chain would be to use an interface for Chain, which *blockchain.BlockChain satisfies. Then we can use a mock blockchain for tests. Is there a better way to test these that doesn't involve changing the code?

- [x] handleAddNode
- [x] handleCreateRawSStx
- [x] handleCreateRawSSRtx
- [x] handleCreateRawTransaction
- [x] handleDebugLevel
- [x] handleDecodeRawTransaction
- [x] handleDecodeScript
- [x] handleEstimateFee
- [x] handleEstimateSmartFee
- [x] handleEstimateStakeDiff
- [x] handleExistsAddress
- [x] handleExistsAddresses
- [x] handleExistsExpiredTickets
- [x] handleExistsLiveTicket
- [x] handleExistsLiveTickets
- [x] handleExistsMempoolTxs
- [x] handleExistsMissedTickets
- [x] handleGenerate
- [x] handleGetAddedNodeInfo
- [x] handleGetBestBlock
- [x] handleGetBestBlockHash
- [x] handleGetBlock
- [x] handleGetBlockchainInfo
- [x] handleGetBlockCount
- [x] handleGetBlockHash
- [x] handleGetBlockHeader
- [x] handleGetBlockSubsidy
- [x] handleGetCFilter
- [x] handleGetCFilterHeader
- [x] handleGetCFilterV2
- [x] handleGetChainTips
- [x] handleGetCoinSupply
- [x] handleGetConnectionCount
- [x] handleGetCurrentNet
- [x] handleGetDifficulty
- [x] handleGetGenerate
- [x] handleGetHashesPerSec
- [x] handleGetHeaders
- [x] handleGetInfo
- [x] handleGetMempoolInfo
- [x] handleGetMiningInfo
- [x] handleGetNetTotals
- [x] handleGetNetworkHashPS
- [x] handleGetNetworkInfo
- [x] handleGetPeerInfo
- [x] handleGetRawMempool
- [x] handleGetRawTransaction
- [x] handleGetStakeDifficulty
- [x] handleGetStakeVersionInfo
- [x] handleGetStakeVersions
- [x] handleGetTicketPoolValue
- [x] handleGetVoteInfo
- [x] handleGetTxOut
- [x] handleGetTxOutSetInfo
- [x] handleGetWork
- [x] handleHelp
- [x] handleLiveTickets
- [x] handleMissedTickets
- [x] handleNode
- [x] handlePing
- [x] handleRegenTemplate
- [x] handleSearchRawTransactions
- [x] handleSendRawTransaction
- [x] handleSetGenerate
- [x] handleStop
- [x] handleSubmitBlock
- [x] handleTicketFeeInfo
- [x] handleTicketsForAddress
- [x] handleTicketVWAP
- [x] handleTxFeeInfo
- [x] handleValidateAddress
- [x] handleVerifyChain
- [x] handleVerifyMessage
- [x] handleVersion
- [x] handleInvalidateBlock
- [x] handleReconsiderBlock

<details closed>
<summary>🟉 changelog 🟉</summary>

```
2020
05/26 - add checklist, check handleCreateRawTransaction
06/15 - check handleCreateRawSSRtx, handleCreateRawSStx, handleDebugLevel, handleDecodeRawTransaction, handleExistsExpiredTickets, handleExistsLiveTicket, handleExistsLiveTickets, handleExistsMissedTickets, handleGetBestBlock, handleGetBestBlockHash, handleGetBlockCount, handleGetChainTips, handleGetCoinSupply, handleGetTxOutSetInfo
07/02 - check handleAddNode, handleEstimateFee, handleGetAddedNodeInfo, handleGetConnectionCount, handleGetCurrentNet, handleGetInfo, handleGetNetTotals, handleGetNetworkInfo, handleGetPeerInfo, handleNode, handlePing
07/06 - check handleGetBlockchainInfo
07/07 - check handleDecodeScript
07/08 - check handleGetBlock, handleGetBlockHash, handleGetBlockHeader, handleGetBlockSubsidy, handleSubmitBlock
07/16 - check handleEstimateSmartFee
07/20 - check handleEstimateStakeDiff, handleGetStakeVersionInfo, handleGetStakeVersions, handleGetTicketPoolValue
07/23 - check handleLiveTickets, handleMissedTickets, handleValidateAddress
08/03 - check handleExistsAddress, handleExistsAddresses, handleGetCFilter, handleGetCFilterHeader, handleGetCFilterV2
08/06 - check handleGetWork
08/08 - check handleSetGenerate, handleRegenTemplate
08/08 - check handleExistsMempoolTxs
09/01 - check handleGetDifficulty, handleVerifyChain, handleSearchRawTransactions
09/03 - check handleGenerate
10/27 - check handleGetGenerate, handleGetHashesPerSec, handleGetHeaders, handleTicketsForAddress, handleTicketVWAP, handleTicketFeeInfo, handleTxFeeInfo
12/07 - check handleSendRawTransaction, handleVerifyMessage, handleGetVoteInfo, handleGetRawTransaction
12/12 - check handleGetMempoolInfo
12/24 - check handleGetTxOut
12/25 - check handleGetMiningInfo, handleGetNetworkHashPS
2021
01/20 - check handleGetStakeDifficulty, handleHelp, handleStop, handleVersion
02/08 - add handleInvalidateBlock and handleReconsiderBlock
02/25 - check handleGetRawMempool
02/27 - check handleInvalidateBlock
03/10 - check handleReconsiderBlock
```
</details>

**Comment by davecgh** [comment]
Yes, ideally every handler should be tested, and you are right to note that will lead to needing the ability to provide a mock implementation of a `blockchain.BlockChain` instance in some form.  More generally, mock implements will be needed for a variety of aspects, and most of those cases already take an interface.

That said, I wouldn't necessarily limit the interface to one that `BlockChain` already satisfies since I think the interface should really be framed in terms of what the RPC server itself requires.  It is generally pretty trivial to write adaptors (see `rpcadaptors.go` which do this for some of the other interfaces like `rpcserver.ConnManager`) and the idea here is to decouple the RPC server from the concrete chain instance.  We ideally don't want to have to change the RPC server interface when the specific `BlockChain` implementation changes.

Finally, also please keep in mind when designing the interface that the ultimate goal is to move all of the `rpcserver` code into the separate internal package, so it should not depend on any types that only exist in main module and the definition should live in `internal/rpcserver/interface.go` alongside the existing interface definitions.  I believe almost all cases of reliance on internal structures from the main module have already been squashed, but I want to be careful to avoid adding any.

**Comment by rstaudt2** [comment]
Anyone working on this one? If not, I can get started on it

**Comment by davecgh** [comment]
There is not anyone working on this that I'm aware of.

**Comment by rstaudt2** [comment]
Cool, I can work on this then. I started taking a look and this is the approach I am considering (just for transparency, and in case you had something else in mind):
- First create an `rpcserver.Chain` interface that `rpcserver` uses rather than the `BlockChain` directly. The adaptor implementation would initially be just a pass-through to the `BlockChain` ([started this here](https://github.com/decred/dcrd/compare/master...rstaudt2:rpcserver_handlers_test?expand=1))
- Add additional test cases to `rpcservershandlers_test` with a stubbed `rpcserver.Chain` interface
- From there the interface can start to be adjusted to what makes the most sense for the RPC server (as you mentioned "...the interface should really be framed in terms of what the RPC server itself requires"). This will likely require changing quite a bit of the code in rpcserver which is why I am considering taking the prior two steps first.

**Comment by JoeGruffins** [comment]
@rstaudt2 looks like the right direction to me. Of course there's places to nitpick, but I'll wait for the pr.

**Comment by rstaudt2** [comment]
@JoeGruffins Started looking at adding tests for the below handlers (mostly the network/peer related ones).

[Here](https://github.com/decred/dcrd/compare/master...rstaudt2:rpcserver_handlers_test_2?expand=1) is what I started so far. It's rough as I've been just been doing a bit here and there between other things and haven't cleaned anything up - but you may need some of the same/similar mocked interfaces depending on what tests you are adding.

- handleAddNode
- handleEstimateFee
- handleGetAddedNodeInfo
- handleGetConnectionCount
- handleGetCurrentNet
- handleGetInfo
- handleGetNetTotals
- handleGetNetworkInfo
- handleGetPeerInfo
- handleGetWork
- handleNode
- handlePing

**Comment by JoeGruffins** [comment]
Going to do handleDecodeScript. Will work on top of your current pr to avoid any merge conflicts.

**Comment by rstaudt2** [comment]
I'm going to work on these ones next:

- `handleGetBlock`
- `handleGetBlockHash`
- `handleGetBlockHeader`
- `handleGetBlockSubsidy`
- `handleSubmitBlock`

Also, tests for `handleGetBlockchainInfo` were added in https://github.com/decred/dcrd/pull/2237.

**Comment by JoeGruffins** [comment]
Sorry I had missed that pr completely.

I'll take these two next  
 - `handleEstimateSmartFee`
 - `handleEstimateStakeDiff`

**Comment by JoeGruffins** [comment]
I'll do handleExistsAddress and handleExistsAddresses next.

**Comment by dnldd** [comment]
Adding `handleLiveTickets` and `handleMissedTickets`.

**Comment by dnldd** [comment]
Working on `handleGetWork` next.

**Comment by davecgh** [comment]
Please continue any tests on top of #2288 since it makes the rpc server internal and the files moved.

**Comment by rstaudt2** [comment]
I'll work on  `handleGetCFilter`, `handleGetCFilterHeader`, and `handleGetCFilterV2` next.

**Comment by dnldd** [comment]
Working on `handleSetGenerate` and `handleRegenTemplate` next.

**Comment by JoeGruffins** [comment]
Will do `handleExistsMempoolTxs`.

**Comment by rstaudt2** [comment]
I'll work on `handleSearchRawTransactions` next.

**Comment by JoeGruffins** [comment]
Will do `handleGenerate` next.

**Comment by JoeGruffins** [comment]
Will do `handleGetGenerate`.

**Comment by JoeGruffins** [comment]
Also included `handleGetHashesPerSec` in the last one.

Will do `handleGetHeaders` next.

**Comment by JoeGruffins** [comment]
Will do `handleGetMempoolInfo` next.

**Comment by dnldd** [comment]
Working on `handleTicketsForAddress`.

**Comment by dnldd** [comment]
Working on `handleTicketVWAP`.

**Comment by dnldd** [comment]
Working on `handleTxFeeInfo`.

**Comment by dnldd** [comment]
Working on `handleTicketFeeInfo`.

**Comment by dnldd** [comment]
Worrking on `handleSendRawTransaction`.

**Comment by dnldd** [comment]
Working on `handleVerifyMessage`.

**Comment by dnldd** [comment]
Working on `handleGetVoteInfo`.

**Comment by JoeGruffins** [comment]
Will do `handleGetMiningInfo`.

**Comment by rstaudt2** [comment]
Going to add tests for `handleGetTxOut` since I'm making a few changes there as part of updating `UtxoEntry` to represent outputs rather than transactions.

**Comment by JoeGruffins** [comment]
will do `handleGetRawMempool`

**Comment by dnldd** [comment]
working on `handleStop`, `handleHelp`, `handleGetStakeDifficulty` and `handleVersion`

**Comment by JoeGruffins** [comment]
It looks like two more handlers popped up.

**Comment by JoeGruffins** [comment]
Will do `handleInvalidateBlock`.

**Comment by JoeGruffins** [comment]
WIll do `handleReconsiderBlock.`

**Comment by JoeGruffins** [comment]
Ok to close? Looks like we got all the handlers.
<details closed>
<summary>test coverage</summary>

```
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:507:		handleAddNode			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:533:		handleNode			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:638:		handleCreateRawTransaction	91.5%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:748:		handleCreateRawSStx		93.3%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:939:		handleCreateRawSSRtx		88.5%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1069:		handleDebugLevel		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1299:		handleDecodeRawTransaction	94.1%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1338:		handleDecodeScript		92.3%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1401:		handleEstimateFee		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1409:		handleEstimateSmartFee		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1434:		handleEstimateStakeDiff		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1504:		handleExistsAddress		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1532:		handleExistsAddresses		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1600:		handleExistsMissedTickets	100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1629:		handleExistsExpiredTickets	100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1655:		handleExistsLiveTicket		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1670:		handleExistsLiveTickets		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1699:		handleExistsMempoolTxs		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1726:		handleGenerate			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1767:		handleGetAddedNodeInfo		97.6%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1847:		handleGetBestBlock		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1859:		handleGetBestBlockHash		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:1885:		handleGetBlock			93.5%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2026:		handleGetBlockchainInfo		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2119:		handleGetBlockCount		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2125:		handleGetBlockHash		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2140:		handleGetBlockHeader		93.8%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2225:		handleGetBlockSubsidy		71.4%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2268:		handleGetChainTips		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2283:		handleGetCoinSupply		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2288:		handleGetConnectionCount	100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2293:		handleGetCurrentNet		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2298:		handleGetDifficulty		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2304:		handleGetGenerate		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2309:		handleGetHashesPerSec		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2314:		handleGetHeaders		95.8%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2359:		handleGetCFilterV2		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2396:		handleGetInfo			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2417:		handleGetMempoolInfo		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2435:		handleGetMiningInfo		90.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2468:		handleGetNetTotals		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2479:		handleGetNetworkHashPS		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2576:		handleGetNetworkInfo		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2604:		handleGetPeerInfo		93.8%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2649:		handleGetRawMempool		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2730:		handleGetRawTransaction		98.5%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2868:		handleGetStakeDifficulty	100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2905:		handleGetStakeVersionInfo	100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2984:		handleGetStakeVersions		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3026:		handleGetTicketPoolValue	100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3037:		handleGetTreasuryBalance	100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3085:		handleGetTreasurySpendVotes	78.7%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3302:		handleGetVoteInfo		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3427:		handleGetTxOut			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3571:		handleGetTxOutSetInfo		80.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3621:		handleGetWorkRequest		95.1%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3725:		handleGetWorkSubmission		88.1%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3813:		handleGetWork			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3866:		handleHelp			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3902:		handleInvalidateBlock		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3931:		handleLiveTickets		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3947:		handleMissedTickets		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3963:		handlePing			80.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3976:		handleReconsiderBlock		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4028:		handleRegenTemplate		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4328:		handleSearchRawTransactions	97.7%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4608:		handleSendRawTransaction	100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4689:		handleSetGenerate		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4721:		handleStop			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4730:		handleSubmitBlock		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:4992:		handleTicketFeeInfo		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:5073:		handleTicketsForAddress		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:5110:		handleTicketVWAP		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:5168:		handleTxFeeInfo			100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:5253:		handleValidateAddress		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:5302:		handleVerifyChain		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:5318:		handleVerifyMessage		96.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:5381:		handleVersion			100.0%
```

**Comment by davecgh** [comment]
Yep, I think it's good to go now.  Thanks to everyone who contributed!

**Comment by JoeGruffins** [comment]
Done.
