### ISSUE TITLE
Copy/Mirror the dcrd data directory / peers.json with own ip address

### ISSUE THREAD

**Issue by urbandigital** [decred/dcrd#207]
I am fighting hard on testnet. Blocks come in very slow, so i decided to mirror/copy the .dcrd/data directory to another host to speed up the blockchain download. I came up with following error:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x7d7778]

goroutine 649 [running]:
panic(0xc6b540, 0xc82000a0d0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/decred/dcrd/addrmgr.NetAddressKey(0x0, 0x0, 0x0)
        /home/decred/.go/src/github.com/decred/dcrd/addrmgr/addrmanager.go:738 +0x28
main.(*serverPeer).OnVersion(0xc82dc7c700, 0xc825f0e900, 0xc82d986270)
        /home/decred/.go/src/github.com/decred/dcrd/server.go:344 +0x3c1
main.(*serverPeer).OnVersion-fm(0xc825f0e900, 0xc82d986270)
        /home/decred/.go/src/github.com/decred/dcrd/server.go:1514 +0x34
github.com/decred/dcrd/peer.(*Peer).inHandler(0xc825f0e900)
        /home/decred/.go/src/github.com/decred/dcrd/peer/peer.go:1481 +0xc12
created by github.com/decred/dcrd/peer.(*Peer).Start
        /home/decred/.go/src/github.com/decred/dcrd/peer/peer.go:1984 +0x2c9`

As far as i can trace this happens because the peers.json file includes the ip-address of the host i am starting dcrd at. So this is no drastical error, but maybe you want to skip the "own ip address" entrys in the peers.json file.

I had just deleted the peers.json file and all went on smooth!

**Comment by chappjc** [comment]
I download a tar of the chain data folder routinely for this purpose and haven't hit this, probably out of luck.  Good to know!

**Comment by cjepson** [comment]
Fixed in #222

**Comment by alexlyp** [comment]
#222 merged.  Should be fixed
