### ISSUE TITLE
repo agl/ed25519 is unmaintained and there are bugs left 

### ISSUE THREAD

**Issue by yutianwu** [decred/dcrd#2112]
this project depends on `github.com/agl/ed25519`, but that repo is unmaintained now and there are bugs left.

you can refer to https://github.com/agl/ed25519

>This repository is unmaintained. Please see x/crypto/ed25519 for a maintained version.

> Before trying to recover a previous version from git, note that I left a one-bit leak in the Elligator code in for years because I'm literally not looking at the PRs. Uncared for code is not a foundation to build upon.

**Comment by jrick** [comment]
We're aware.  We're also aware that those bugs are in the consensus rules now, and we are stuck with them, which is why we have not made any attempt to change to another library.  If need be, we will fork the code into the dcrd repo.

BTW, if you are looking for another ed25519 package to use, use the one from the standard library.  The one from x/crypto is now just a wrapper for it.

**Comment by yutianwu** [comment]
Is there any security issue if we don't change the library

**Comment by jrick** [comment]
Possibly.  But the library is only used for ed25519 signatures in the scripting system, and to my knowledge these are not commonly used, or used at all (however, we cannot be certain of this -- it is possible that p2sh outputs on the chain today require an ed25519 signature).  The possible weaknesses in these required on-chain signatures haven't been researched extensively, except to notice that there would be an unintentional hard fork had the agl package been replaced by x/crypto or the standard library.

What I can say for certain is that the most used decred wallet software, dcrwallet, does not produce or require these signatures at all, which is definitely a good thing given this situation.  And as dcrwallet maintainer, I won't be adding support for them until ed25519 signatures are safe to use after a consensus upgrade occurs to introduce a fixed signature scheme (if it ever happens).

Ed25519 signatures for TLS are also not affected by this package usage, FWIW.
