### ISSUE TITLE
rpcclient: Offer onClientDisconnected() notification

### ISSUE THREAD

**Issue by matheusd** [decred/dcrd#2227]
For services that run on top of a dcrd instance via an rpcclient connection, it would be useful to receive a onClientDisconnect notification such that the service could stop processing external requests and/or send relevant alerts until the connection to the underlying dcrd instance is restored.

**Comment by davecgh** [comment]
This was discussed in #1877.

See my reasoning there, but I really don't think this is the right way to go.
