### ISSUE TITLE
rpcserver: getblockchaininfo is not queryable on an empty blockchain

### ISSUE THREAD

**Issue by matheusd** [decred/dcrd#2235]
Starting dcrd with an empty chain and `--connect=127.0.0.1:1313` (so it doesn't connect anywhere) then issuing an `getblockchaininfo` fails with "-32603: hash 0000000000000000000000000000000000000000000000000000000000000000 does not exist"

It probably should handle that so that query can be used by clients to assert the current chain state even on an empty dcrd install.

**Comment by davecgh** [comment]
Agreed.  I'm going to guess it's because it attempts to find out the state of the deployment as of the previous hash, which is the zero hash for the genesis block and therefore indeed does not exist.

**Comment by davecgh** [comment]
@rstaudt2 Said he was going to pick this up.

**Comment by davecgh** [comment]
I took a quick look earlier just to double check it's what I thought it was and it does seem to be the case.  I suspect the easiest and most correct way to fix it is to simply start with the agenda information as defined and then only attempt to query the state if `best.PrevHash != zeroHash` in the RPC handler.
