### ISSUE TITLE
Configure mining.go to eventually move into its own package

### ISSUE THREAD

**Issue by cjepson** [decred/dcrd#224]
btcd master has the new TxSource for mining, that will allow mining.go to move into its own testable package. Because of the new stake elements in Decred, functions relating to incorporating votes and the state of the blockchain based on the last votes will need to be moved into their own import Source interface, along the lines of StakeSource or VoteSource.

**Comment by MiguelMoll** [comment]
Would this be related to #497 `mining: Needs further TxSource separation `?

**Comment by davecgh** [comment]
Closed in favor of #497.
