### ISSUE TITLE
sign transaction js lib?

### ISSUE THREAD

**Issue by tpkeeper** [decred/dcrd#2242]
I can't find a js lib to sign dcr transaction,anyone can help me?

**Comment by davecgh** [comment]
I'm not aware of any.  I asked in the developer chat though to see if anyone else if aware of one that I'm not.

**Comment by tpkeeper** [comment]
> I'm not aware of any. I asked in the developer chat though to see if anyone else if aware of one that I'm not.

sorry, I can speak a little english. Maybe What I said above is not appropriate.But I am harmless.

then,I find one js lib `https://github.com/decredjs/decredjs-lib`.
 
maybe this lib can work.

**Comment by davecgh** [comment]
It's not official, but @JoeGruffins has submitted: https://github.com/trezor/trezor-utxo-lib/pull/9

Perhaps you can get what you need from out of that code.
