### ISSUE TITLE
Move rpcserver into a separate internal package.

### ISSUE THREAD

**Issue by rstaudt2** [decred/dcrd#2263]
This issue tracks the progress of moving `rpcserver` into a separate internal package.  This entails moving the following files out of the `main` package and into `internal/rpcserver`:
- `rpcserver.go`
- `rpcserver_test.go`
- `rpcserverhandlers_test.go`
- `rpcserverhelp.go`
- `rpcserverhelp_test.go`
- `rpcwebsocket.go`

The primary prerequisite for this is to remove all of the remaining dependencies that `rpcserver` has on vars/types/functions in the main module.  The remaining dependencies to be removed are as follows:
- [ ] [[dcrd.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/dcrd.go#L22)] `var cfg *config`
- [ ] [[config.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/config.go#L357)] `func normalizeAddress(addr, defaultPort string) string`
- [ ] [[config.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/config.go#L267)] `func supportedSubsystems() []string`
- [ ] [[config.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/config.go#L1287)] `func dcrdLookup(host string) ([]net.IP, error)`
- [ ] [[config.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/config.go#L282)] `func parseAndSetDebugLevels(debugLevel string) error`
- [ ] [[log.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/log.go#L93)] `var subsystemLoggers = map[string]slog.Logger`
- [ ] [[log.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/log.go#L70)] `var rpcsLog slog.Logger`
- [ ] [[log.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/log.go#L160)] `func directionString(inbound bool) string`
- [ ] [[server.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/server.go#L70)] `const maxProtocolVersion uint32`
- [ ] [[server.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/server.go#L88)] `var userAgentVersion string`
- [ ] [[blockmanager.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/blockmanager.go#L242)] `type PeerNotifier interface`
- [ ] [[blockmanager.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/blockmanager.go#L75)] `var zeroHash chainhash.Hash`
- [x] [[cpuminer.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/cpuminer.go#L121)] `type CPUMiner struct` (handled in https://github.com/decred/dcrd/pull/1965)
- [x] [[mining.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/mining.go#L2044)] `type BgBlkTmplGenerator struct` (handled in https://github.com/decred/dcrd/pull/1965)
- [x] [[mining.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/mining.go#L378)] `type BlockTemplate struct` (handled in https://github.com/decred/dcrd/pull/1965)
- [x] [[mining.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/mining.go#L1967)] `type TemplateNtfn struct` (handled in https://github.com/decred/dcrd/pull/1965)
- [x] [[mining.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/mining.go#L1942)] `type TemplateUpdateReason int` (handled in https://github.com/decred/dcrd/pull/1965)
- [x] [[mining.go](https://github.com/decred/dcrd/blob/fddd629fe062a8b028781665a731e36606589455/mining.go#L73)] `const merkleRootPairSize untyped int` (handled in https://github.com/decred/dcrd/pull/1965)

**Comment by rstaudt2** [comment]
@davecgh If you're cool with this (and it aligns with what you were thinking), I can work on it.

**Comment by davecgh** [comment]
Yes, this looks correct to me.  Thanks for putting it together!.

It's worth noting that the mining pieces are already done via #1965.

Also, just an FYI that since we're getting close to the 1.6.0 release, and we need get #2170 in, which is massive, I'm going to be fairly selective on merging PRs to master to those that are test coverage, bug fixes, or related to the release until 1.6.0.

I mention it because it means the PRs related to this are very likely to be delayed a bit in merging as a result, and thus might end up needing a rebase to resolve merge conflicts when the time comes.

I've been marking most of the new PRs that modify code as part of the 1.7.0 milestone.

**Comment by rstaudt2** [comment]
@davecgh Sounds good, thanks for confirming. Makes sense regarding the 1.6.0 release.

**Comment by davecgh** [comment]
Somewhat related are PRs #2274, #2275,  and #2276 which move the `mempool` and `mining` modules to internal packages instead as well as splits out the `cpuminer` code into a separate sub-package under the internal `mining` package.

They don't directly affect the work scoped in this issue, however, they do involve performing a similar task, so might be useful for that purpose.

**Comment by davecgh** [comment]
Update the issue to account for #1965 being merged.
