### ISSUE TITLE
rpcserver: Return types.EstimateSmartFeeResult for EstimateSmartFee.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrd#2268]
An RPC call to `estimatesmartfee` returns a `float64`, but it should return the currently unused `types.EstimateSmartFeeResult`.

https://github.com/decred/dcrd/blob/cdc897dcc204fffe0dad1f8943ba7db3ca1a9f17/rpc/jsonrpc/types/chainsvrresults.go#L29-L40

`estimatesmartfee` should be changed to return the correct type during the next major RPC API version bump.

**Comment by dnldd** [comment]
On it.
