### ISSUE TITLE
JSON-RPC API docs are missing some ws notifications. 

### ISSUE THREAD

**Issue by rstaudt2** [decred/dcrd#2295]
Some of the websocket notifications are not documented in the JSON-RPC API docs:
https://github.com/decred/dcrd/blob/master/docs/json_rpc_api.mediawiki#7-notifications-websocket-specific

For example, the following are missing documentation:
- notifystakedifficulty
- notifynewtickets
- notifyspentandmissedtickets
- notifywinningtickets

**Comment by davecgh** [comment]
Nice catch.  That should definitely be updated.

**Comment by rstaudt2** [comment]
Cool, I can get that updated.
