### ISSUE TITLE
Any timeline to freeze the code?

### ISSUE THREAD

**Issue by sjtusmartboy** [decred/dcrd#2353]
I'm asking this because the time is money since many other DEXs are pushing really hard to launch the project so that they will win in fight for the currency flow. The first will eat flesh, the second eat soup, but the last eat nothing. Also I've noticed that we have been making the DCRDEX project for over a year, so maybe we could accelerate it just a little bit. Thanks !

**Comment by davecgh** [comment]
This is the repository for dcrd, which is a full node for the Decred network that forms the backbone of it.

The DEX project is a separate repository at https://github.com/decred/dcrdex/.

Closing since it doesn't apply to this project.
