### ISSUE TITLE
make dcrctl --terminal work on Windows

### ISSUE THREAD

**Issue by frankbraun** [decred/dcrd#25]
`dcrctl --terminal` currently doesn't work on Windows, because using "golang.org/x/crypto/ssh/terminal" (see [terminal.go](https://github.com/decred/dcrd/blob/42ae03b66378c3a359651bad9695c0ed36fb3794/cmd/dcrctl/terminal.go)) to handle terminals has at least two problems:
- Passing in 0 as fd doesn't work on Windows, because stdin is not 0 there (duh!). One has to use syscall.Stdin.
- I wrote a simple test program [termecho.go](https://github.com/frankbraun/kitchensink/blob/a730714de008ea6d9de126420828c658b3b90b2f/cmd/termecho/termecho.go) which tests "golang.org/x/crypto/ssh/terminal" in the simplest possible form. I fixed the fd problem there, but it seems that the echo is broken on Windows. That is, typed characters are not echoed in the terminal. I have no idea why that is.

I could rewrite the terminal code to use the [liner](https://github.com/peterh/liner) package instead. I used it in another project and so far it seems to work just fine on Windows (including echo). It also gives the terminal mode more features (e.g., searchable history).

An alternative might be the [readline](https://github.com/chzyer/readline) package, but I have no experience with it. And a package inspired by linenoise hopefully will continue to be more minimal than a package inspired by GNU readline.

Any opinions?

**Comment by jcvernaleo** [comment]
From my perspective (I don't use windows) the only things that matter to me are:
1. still works properly on UNIX
2. no cgo
3. compatible license
As long as the solution fits those, I'm happy with it.  @jrick or @davecgh might have stronger windows related opinions.

**Comment by frankbraun** [comment]
The liner package ticks all the boxes. I totally agree that cgo should be avoided. License is X11, so that should be fine. But I'm waiting for opinions from @jrick and @davecgh before I proceed.

**Comment by davecgh** [comment]
I'm of the same opinion as @jcvernaleo as far as the requirements with one additional one:

4. Any new package requires a thorough security audit

**Comment by frankbraun** [comment]
What's the process for that?

**Comment by jrick** [comment]
That liner package does make pretty heavy use of unsafe so some of us (probably 2 or more individuals) should ensure it's not violating memory safety anywhere.

**Comment by frankbraun** [comment]
OK, then I'll take a deeper look into the ssh/terminal package first. Maybe I can figure out why the echo is not working on Windows.

**Comment by jcvernaleo** [comment]
--terminal was removed in #580 (but #649 adds a tool that should take care of one of the uses of it) so closing this.
