### ISSUE TITLE
Decred fork

### ISSUE THREAD

**Issue by Bitaltyn-project** [decred/dcrd#2578]
Hello.
I am trying to fork.
Changed the required parameters
![image](https://user-images.githubusercontent.com/15166908/106366268-b8db2a00-634b-11eb-99c4-f0fe795bd060.png)
created a wallet and pointed it to dcrd.conf  
miningaddr=DsSrQKV6KWudTbxBxTBuCP1b9vTWM5y9XxC
launched
dcrd.exe -u rpcuser -P rpcpass

launched
dcrwallet.exe -u rpcuser -P rpcpass

launched
dcrctl.exe -u rpcuser -P rpcpass generate 50

also i ran dcrd.exe -u rpcuser -P rpcpass on another computer

Why aren't new blocks being created?
Am I missing something?

**Comment by jrick** [comment]
Try asking on your own issue tracker.

**Comment by Bitaltyn-project** [comment]
In my repository?

**Comment by davecgh** [comment]
You won't receive any help creating a fork here, and Decred's design intentionally makes chain forks rather infeasible anyway.

If you're trying to create a testing environment for an application/service building on Decred that you're working on, see the simulation network documentation in the repository.

https://github.com/decred/dcrd/blob/master/docs/simnet_environment.mediawiki
