### ISSUE TITLE
Current master is reporting attempts to remove peers that were never added.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#2581]
Reported by @lolandhold:

> Don't know if it's related, starting a new dcrd from branch `multi_use_siphash_1_2_2` on rpi4 (ARMv7) with go1.15.7.linux-armv6l.tar.gz (I hope v6 was the right version to use) synced the chain fully, but shows this in the logs for each inbound connection.

```
2021-01-31 18:15:58.611 [WRN] SYNC: Attempt to lookup unknown peer 78.47.33.192:43014 (inbound)
Stake: goroutine 58 [running]:
runtime/debug.Stack(0x614230, 0x4be6840, 0x2e84a00)
	/home/dev/MAGIC/go/src/runtime/debug/stack.go:24 +0x78
github.com/decred/dcrd/internal/netsync.lookupPeer(0x2e84a00, 0x4be6840, 0x3)
	/home/dev/dcrd/internal/netsync/manager.go:296 +0x44
github.com/decred/dcrd/internal/netsync.(*SyncManager).handleDonePeerMsg(0x2c18240, 0x2e84a00)
	/home/dev/dcrd/internal/netsync/manager.go:577 +0x2c
github.com/decred/dcrd/internal/netsync.(*SyncManager).eventHandler(0x2c18240, 0x8e0970, 0x4be6d60)
	/home/dev/dcrd/internal/netsync/manager.go:1409 +0x7a0
created by github.com/decred/dcrd/internal/netsync.(*SyncManager).Run
	/home/dev/dcrd/internal/netsync/manager.go:1762 +0xa0
```

This is not related to the siphash update, but is an issue that needs to be resolved nonetheless.

**Comment by davecgh** [comment]
@lolandhold This should be resolved by #2582.  I'm not able to reproduce it on my system, but I can see how it could happen, so if you have a chance, would you verify that PR resolves the issue for you?

**Comment by davecgh** [comment]
I was able to find a way to reliably reproduce this and prove the aforementioned PR does indeed fix it.

**Comment by lolandhold** [comment]
I got no errors after running it for two days.
