### ISSUE TITLE
rpcserver: Add mediantime to getblock and getblockheader verbose results.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrd#2637]
For consumers that want to know the median time, they can calculate it themselves using the last 11 headers, but it would be helpful if that information was readily available in an rpc call.

**Comment by JoeGruffins** [comment]
I would like to work on this.

**Comment by davecgh** [comment]
Sounds like a reasonable idea to me. Specifically, `mediantime` in the `getblock` and `getblockheader` RPCs when in verbose mode.
