### ISSUE TITLE
Extract Decred-specific mempool policy

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#264]
Pull request #263 syncs in the upstream mempool policy structure however it does not add the new Decred-specific variables to it.  That must be done before the mempool can properly be split out into a separate package.

Also, the code in `rpcserver.go` is improperly referencing the mempool policy from the block template generation code, so the variable for `maxSigOpsPerTx` had to be added to it in order to keep the code working.  The comment added as part of the PR explains why:

```
    // NOTE: This is being added while syncing upstream because the code in
    // the RPC server here is referencing the variable even though it most
    // definitely shouldn't be.  It is a policy limit regarding what should
    // be relayed or mined and thus should only apply in the mempool and/or
    // possibly the mining code.
```

**Comment by MiguelMoll** [comment]
Is this issue still valid given https://github.com/decred/dcrd/pull/496  refactored mempool into it's own package?

I see `rpcserver.go` is still referencing `maxSigOpsPerTx `.

Trying to find something "simple" I can help with.  😉

**Comment by davecgh** [comment]
Sorry for the late response.  It still applies.

**Comment by davecgh** [comment]
As it turns out, you are correct that it no longer applies.  I was thinking about the priority code which is handled by PR #1110.
