### ISSUE TITLE
rpcserver: Add `Version` field to `gettxout.scriptPubKey` results.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#2647]
As the title indicates, a `version` field should be added to the result of the `gettxout` RPC under `scriptPubKey`.  The script version is going to become more important in the future when a new version is introduced.

**Comment by JoeGruffins** [comment]
I would love to add this.

**Comment by davecgh** [comment]
Thanks.  Assigned it to you @JoeGruffins.
