### ISSUE TITLE
Tickets voting on treasury spends are falsly reported as missed in some rpc requests.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/dcrd#2668]
https://explorer.dcrdata.org/tx/88329d0f7173559912cc90d4e7815c9516d6004a51ecdfbc773cd3a959510a24
```
dcrctl existsmissedtickets '["f427464a8b0976b2993b6d017eb2168abec23a70a449563dcaf40bf15c80e42c"]'
01
```

**Comment by davecgh** [comment]
I see the issue.  I'll need to consider the best way to fix it though since we probably want to back port it.
