### ISSUE TITLE
Deprecated nodnsseed in sampleconfig

### ISSUE THREAD

**Issue by xaur** [decred/dcrd#2727]
I tried uncommenting `nodnsseed=1` in `dcrd.conf` (which I copied from `sample-dcrd.conf`) and got this warning:

    The --nodnsseed is deprecated: use --noseeders

`dcrd --help` also says it is deprecated and has `--noseeders`. So I tried `noseeders=1` in the config and seems like it worked: config key accepted and no requests to seeders, as expected. Could be just a matter of updating the sample config.

dcrd v1.6.2 (from v1.6.3 release)

**Comment by davecgh** [comment]
Updated via #2728.
