### ISSUE TITLE
dcrd can't update external ip via uPnP regularly

### ISSUE THREAD

**Issue by read0n1y** [decred/dcrd#2751]
### **Network Environment:**
My network Environment Dynamic Internet IP, the Internet IP changes about every 48 Hours regularly, it's controlled by Internet Service Provider. The Gateway  router enabled uPnP function.

### **Condition**
if I wanna build a public node to Decred network, The externalip of dcrd can't update once my Internet IP changed.

### **Guess**
I found the source code from `func (s *server) upnpUpdateThread(ctx context.Context)` in server.go, it just get external ip via uPnP route gateway at dcrd start up. When dcrd is running and the Internet IP changed, The dcrd keeps old Internet IP as External IP.

I think it need to get `GetExternalAddress()` every15 min and update the `localaddress`, Once the Internet IP changed , renew new Internet IP and broadcast to Decred Network.

### **Hope**
such as lnd or some other blockchain project, The function works well. It brings more public node to server the blockchain network. The people who want to contribute their full node can use it easily.

**Comment by chappjc** [comment]
It seems to me that if the IP address changes regularly, it's not very suitable as a public node.  i.e. the crawlers/seeders would **not** want to recommend such a node as a sync node to other peers if it is likely to change rapidly.

**Comment by jrick** [comment]
I agree but to clarify the terminology, it is still fine as a public node.  However, it should only be creating outbound connections, not accepting any inbound ones.

**Comment by read0n1y** [comment]
understand
