### ISSUE TITLE
Track information regarding ruleset used to invalidate a block.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#2766]
Currently, when a block is found to be invalid it is marked as such in the block index both for efficiency purposes and to avoid various forms of malicious behavior.  Naturally, this also means when a new consensus rule is deployed such that new blocks are no longer valid under the old rules, old nodes will, correctly, reject those blocks and mark them invalid.

This is highly desirable behavior, however, it also means that upgrades have to be handled carefully because nodes that don't upgrade in time will correctly, from their point of view, mark those newer blocks invalid, but then, once they actually upgrade, they need to reconsider those blocks under the new rules or they would otherwise be stuck.

This is currently handled by bumping the database version in new releases that contain a consensus rule upgrade and clearing all of the block invalidity flags as a part of that one-time upgrade.  The approach works well, but it is also something that is easy to forget and forces a database upgrade when one might not otherwise be necessary.

Ideally, this behavior should be changed to instead keep track of which consensus ruleset was used to invalidate a block (an internal-only version that is bumped would be fine for this purpose) and automatically handle reconsideration of new consensus rulesets using that information.  This would simplify the requirements for handling upgrades during consensus rule changes to bumping an internal version versus the current need to write database upgrade code each time and also avoid losing information about old blocks that were found to be invalid for reasons other than failing to upgrade in time.

**Comment by rstaudt2** [comment]
I'll take this one on.
