### ISSUE TITLE
Feature Request: gitian signature for binaries released

### ISSUE THREAD

**Issue by zhizhongzhiwai** [decred/dcrd#2775]
[gitian https://gitian.org](https://gitian.org) be better/security choice for signature for binary released.

Gitian is a secure source-control oriented software distribution method. This means you can download trusted binaries that are verified by multiple builders.

Gitian uses a deterministic build process to allow multiple builders to create identical binaries. This allows multiple parties to sign the resulting binaries, guaranteeing that the binaries and tool chain were not tampered with and that the same source was used. It removes the build and distribution process as a single point of failure.

**Comment by jrick** [comment]
we already have reproducible releases (at least for the core cli tooling, unfortunately not for stuff like decrediton), and anyone (developer or not) is free to sign their own release distribution manifests with their own sigs for others to verify.

what's missing is these individual signatures actually being created by many distinct individuals who others trust to varying degrees.  we do verify the reproducibility of the release from many developers, but currently not with any cryptographic authentication.  this is the area we should be most focusing on, imo.

i am skeptical of gitian as it relies on a single preconfigured vm environment to perform all reproducible release builds.  currently, we are already able to reproducibly release across any a wide variety of environments (essentially, anything that is able to run go), which provides far greater confidence builds only being created from a single environment.

**Comment by davecgh** [comment]
We already do deterministic builds via https://github.com/decred/release/.  Each release is independently built and verified by multiple people without the need of a VM or docker container.  The only part of it that isn't done is signing with multiple signatures, but that is something I have previously mentioned I would ultimately like to see happen.

Well, I see @jrick already answered while typing this, so I'll leave it there.
