### ISSUE TITLE
dcrd doesn't always shut down properly.

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrd#279]
This has been observed on windows several times.  The logs do not indicate any failure.  Don't have too much additional information but will collect logs as I run into it more often.

09:47:55 2016-06-30 [INF] RPCS: Finished rescan
09:49:08 2016-06-30 [INF] BMGR: Processed 9 blocks in the last 32m32.49s (128 transactions, height 41506, 2016-06-30 09:48:31 -0500 CDT)
09:53:28 2016-06-30 [ERR] RPCS: Websocket receive error from 127.0.0.1:52438: websocket: close 1006 unexpected EOF
09:53:28 2016-06-30 [INF] RPCS: Disconnected websocket client 127.0.0.1:52438
09:57:45 2016-06-30 [INF] BMGR: Processed 1 block in the last 8m36.65s (23 transactions, height 41507, 2016-06-30 09:57:25 -0500 CDT)
10:12:11 2016-06-30 [INF] BMGR: Processed 1 block in the last 14m25.91s (15 transactions, height 41508, 2016-06-30 10:12:06 -0500 CDT)
10:14:14 2016-06-30 [INF] BMGR: Processed 1 block in the last 2m2.96s (10 transactions, height 41509, 2016-06-30 10:13:14 -0500 CDT)

Hit CTRL-C here.

10:19:39 2016-06-30 [INF] DCRD: Version 0.1.6-beta
10:19:39 2016-06-30 [INF] DCRD: Loading block database from 'C:\Users\marco\AppData\Local\Dcrd\data\mainnet\blocks_leveldb'
10:19:39 2016-06-30 [INF] BCDB: Address index synced and loaded to height 41509
10:19:39 2016-06-30 [INF] DCRD: Block database loaded with block height 41509
10:19:39 2016-06-30 [INF] DCRD: Block ticket database initialized empty
10:19:39 2016-06-30 [INF] DCRD: Db non-empty, resyncing ticket DB
10:38:33 2016-06-30 [INF] BMGR: Generating initial block node index.  This may take a while...
10:38:36 2016-06-30 [INF] BMGR: Block index generation complete

**Comment by marcopeereboom** [comment]
This is an msys issue and can not be fixed.

**Comment by jrick** [comment]
For users who are hitting this: the solution is to run dcrd in a cmd.exe or powershell console window, instead of the msys2 or cygwin shell.
