### ISSUE TITLE
Deadlock on shutdown

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#2800]
Here's the log with a trace after the hang:

https://gist.githubusercontent.com/jrick/eb1693e62cd7bcac602f6ff94fc1b3bd/raw/d4df9ab1d94d40bbb76c0ac6b5697a53a01f187c/gistfile1.txt

@rstaudt2 suggested this may be due to the async indexing.

**Comment by dnldd** [comment]
Retest with https://github.com/decred/dcrd/pull/2806

**Comment by jrick** [comment]
Fixed, closing.
