### ISSUE TITLE
dcrd crashes repeatedly

### ISSUE THREAD

**Issue by gwenphuong** [decred/dcrd#282]
dcrd always crashes right after it starts. Here is the log from nohup.log

https://gist.github.com/gwenphuong/a4f92b55879cbba260b58e5ce9a13221

**Comment by gwenphuong** [comment]
No one else has this? I've tested with dcrd as old 0.0.10, same crash. Maybe it's a db issue. Any suggestion to find the cause?

**Comment by gwenphuong** [comment]
Interestingly, the same crash happens on both raspberry pi2 and amd64.

**Comment by jcvernaleo** [comment]
I definitely run dcrd nodes on amd64 and the raspberry pi (I think the 2, hard to keep track once you have enough of those little arm boxes) without problems.
I would suspect a db problem.  Would it be possible to move your old db and try to sync from scratch:
mv ~/.dcrd/data/mainnet/ ~/.dcrd/data/mainnet-old
and let us know if that works?

**Comment by gwenphuong** [comment]
Definitely still happen when syncing the chain from zero. I've noticed the crash happened right after the drcd adding a orphan block.

https://gist.github.com/gwenphuong/c7b8a2aa2464ade5d5684b06652148dc

**Comment by jcvernaleo** [comment]
Are you using the --noaddridx flag?  There is a known issue with that causing crashes.  Could you try without it?

**Comment by gwenphuong** [comment]
I only use addrindex = True in the config file (besides rpcuser and rpcpassword). Then I use this to start dcrd:

nohup -c "sh

**Comment by gwenphuong** [comment]
I'm starting over without addrindex. Let's see what'll happen.

**Comment by gwenphuong** [comment]
Yep, syncing from zero completed successfully without addrindex enabled.

**Comment by marcopeereboom** [comment]
Is this still an issue?  I recall hearing debate that this option was going to be removed.
