### ISSUE TITLE
Have a question about the code in func SortParentsByVotes

### ISSUE THREAD

**Issue by james-ray** [decred/dcrd#2823]
Hello, I'm new to here, and learning code.

```
// Make sure we don't reorganize the chain needlessly if the top block has
	// the same amount of votes as the current leader after the sort. After this
	// point, all blocks listed in sortedUsefulBlocks definitely also have the
	// minimum number of votes required.
	curVoteMetadata := txSource.VotesForBlocks([]chainhash.Hash{currentTopBlock})
	numTopBlockVotes := uint16(len(curVoteMetadata))
	if filtered[0].NumVotes == numTopBlockVotes && filtered[0].Hash !=
		currentTopBlock {

		// Attempt to find the position of the current block being built
		// from in the list.
		pos := 0
		for i, bwnv := range filtered {
			if bwnv.Hash == currentTopBlock {
				pos = i
				break
			}
		}

		// Swap the top block into the first position. We directly access
		// sortedUsefulBlocks useful blocks here with the assumption that
		// since the values were accumulated from filtered, they should be
		// in the same positions and we shouldn't be able to access anything
		// out of bounds.
		if pos != 0 {
			sortedUsefulBlocks[0], sortedUsefulBlocks[pos] =
				sortedUsefulBlocks[pos], sortedUsefulBlocks[0]
		}
	}

	return sortedUsefulBlocks
```
 the func VotesForBlocks returns a two dimension array, isn't the numTopBlockVotes := uint16(len(curVoteMetadata))  fixed to be 1?
I think this judge  "if filtered[0].NumVotes == numTopBlockVotes"  is meant to compare the votes number of the two blocks.
If the numTopBlockVotes does not reflect the real number of votes of TopBlock,  the reorg will occur needlessly?

**Comment by davecgh** [comment]
Hello and welcome.  You're correct that it isn't taking the correct length there, although it isn't necessarily fixed to 1 either.  It can theoretically be 0 or 1 since there is no guarantee any results are returned.  Therefore, it should be something more like:

```Go
var numTopBlockVotes uint16
if len(curVoteMetadata) == 1 {
	numTopBlockVotes = uint16(len(curVoteMetadata[0]))
}
if ... <rest of existing code>
```

Also, there really should be a test added for that function that tests all of the corner cases properly to make sure the behavior is correct.
