### ISSUE TITLE
Cannot generate simnet blocks after invalidating tip

### ISSUE THREAD

**Issue by matheusd** [decred/dcrd#2837]
Reproducer:

- Run `contrib/dcr_tmux_simnet_setup.sh`
- Mine a block on dcrd1: `./mine`
- Invalidate latest block: `./ctl getbestblockhash |  ./ctl invalidateblock -`
- Attempt to mine new block: `./mine`

Generating hangs forever.

This is due to [this check](https://github.com/decred/dcrd/blob/master/internal/mining/cpuminer/cpuminer.go#L714-L719) in the CPU miner: going back to the block prior to tip makes this check fail, due to attempting to mine based on the same previous header.

One option to fix this would be to somehow reset `discretePrev` after some time has passed, when the `invalidateblock` rpc call is called or when the `regentemplate` is called.

**Comment by davecgh** [comment]
I suspect the best way to handle it would be to add a way to query chain if `discretePrev` is invalidated and ignore it in that case.

**Comment by davecgh** [comment]
I looked at this a bit more and it looks like a solid way to handle it will be to allow the template to be mined anyway in the case the block that was previously mined by the discrete mining process is no longer valid.
