### ISSUE TITLE
Ticket purchasing should have its own RPC API

### ISSUE THREAD

**Issue by cjepson** [decred/dcrd#285]
Currently split transactions and tickets consuming them go sequentially through the RPC, which can waste user funds as fees if the user's tickets are rejected for whatever reason. In the future, there should be a new RPC calls, such as "sendtickets", which transmits all tickets and their dependencies, verifies their current ability to be added to the blockchain and that they're purchased for the intended difficulty, and then inserts them into the mempool and returns TRUE. Otherwise, the relevant error is returned and the funds are restored to wallet without sending any of the transactions. Importantly, this also rejects tickets that have become invalid because the difficulty has changed between their creation and transmission to the daemon.

The message send should be something like: struct { diff int64, []txs wire.MsgTx } as a JSON object.

**Comment by raedah** [comment]
Ideally, split transactions would get mined together with the ticket purchase transaction, and if the ticket purchase transaction expires before getting mined, then the split transaction would expire as well so that funds are not wasted.
Also, currently there is no on screen logging showing the users funds being spent in split transactions. This should be shown to the user.

**Comment by cjepson** [comment]
The split transaction could never be mined with the ticket itself because the split transaction is not yet voted on and could be invalidated in the next block.

**Comment by raedah** [comment]
If a block is invalidated, either by votes or by a block race, then its transactions and its ticket purchases would be removed from the chain with the block itself being removed. The relationship between a split transaction and a dependent ticket purchase is not any different then other standard transactions on the blockchain that are dependently mined in the same block.

**Comment by jrick** [comment]
The issue is that since the splits and the purchases are not mined in the same block, the splits can be mined and validated by voters, while the ticket purchase is never mined.
