### ISSUE TITLE
using dcrec/secp256k1 with ethereum keys 

### ISSUE THREAD

**Issue by fxfactorial** [decred/dcrd#2883]
I'm trying to use in an ethereum transaction context, to recover the public key given sighash, sig. 

sometimes it works (via `dcrdsecp.RecoverCompact(sig, hash)`) but most times it doesn't with the error: ` calculated Rx is larger than curve P`

also sometimes in the true case, the bool returned is true and sometimes its false. 

The input values I used are the same parameters sent to this Ecrecover (which calls cgo calls) https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_signing.go#L497

i think it has something to do with compressed or not public keys, the expectation there of. 

would appreciate if could show a way to use your pure golang impl in the context of that call to Ecrecover

**Comment by chappjc** [comment]
The following code is not in production yet, but perhaps this is of help:  https://github.com/decred/dcrdex/blob/0c75bd4ef78a0cde38eb558dd20b1ffe2a655683/client/asset/eth/eth.go#L828-L844

If `SignCompact` was used to make the signature referencing the uncompressed public keys I believe it should work.

**Comment by davecgh** [comment]
I'll take a look at this here in a bit.  If you don't mind answering the following, it should be enough to get the ball rolling:

1) Which version of the module are you using (e.g github.com/decred/dcrd/dcrec/secpk256k1@v3.0.0, @v4.0.1, etc)?
2) Would you provide a couple of sig/hash/pubkey triples that are not producing the expected results?

**Comment by chappjc** [comment]
Also, are you aware that `go-ethereum/crypto` has a no-cgo version if you build with `CGO_ENABLED=0`?

**Comment by fxfactorial** [comment]
> Also, are you aware that `go-ethereum/crypto` has a no-cgo version if you build with `CGO_ENABLED=0`?

No, wasn't aware thank you. Also, I tried your code sample and it works great. Thank you, can close issue

**Comment by chappjc** [comment]
Glad that worked.  Be sure to use `secp256k1/v4` module though.
