### ISSUE TITLE
Panic on notifying index subscribers (release 1.7.1)

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrd#2913]
```
fatal error: concurrent map iteration and map write
```

[Full trace](http://sprunge.us/Y8Xbg5)

https://github.com/decred/dcrd/blob/e1b2e6011bf679a36ed39494dfcb1dcac30bbc80/blockchain/indexers/common.go#L692-L695

Maybe relevant for #2871

**Comment by jrick** [comment]
this *seems* like a data race, and unrelated to the fact that the map is being modified during iteration in the loop. can you reproduce with the race detector enabled?

**Comment by chappjc** [comment]
Almost certainly the `WaitForSync` call in `handleExistsAddresses`.  Seems like the `Indexer interface` needs a `NotifiySubscribers` to clear out the map while under lock

**Comment by davecgh** [comment]
This is fixed by #2871.  However, unfortunately @dnldd implemented it in such a way that it can't be back ported to the v1.7.1 release, because it required a major module version bump.  It will need to be backported in a way that doesn't break the API.

**Comment by dnldd** [comment]
Noted, working on it 👍
