### ISSUE TITLE
Is there an error in the secp256k1 example?

### ISSUE THREAD

**Issue by marksalpeter** [decred/dcrd#2967]
On [line 72 of secp256k1/example_text.go](https://github.com/decred/dcrd/blob/75f1b4dac2e43133f3281ac63a9ef9eb699200e5/dcrec/secp256k1/example_test.go#L72) it looks like you're defining an empty nonce, and then populating it with a random value. This seems strange to me at first glance.

1. It seems like the aes key itself in this example is already seeded with a random private value (the ephemeral private key) and is never reused, so is nonce actually not necessary in this case? If it's deliberately excluded, a comment about this in the example would be extremely clarifying. 

2. It seems like in this example you're using the first 4 bytes of the message to transmit the length of the public key that follows before the cipher text. If the public keys for secp256k1 are all known to be 33 bytes, why waste the space? Is this an implementation detail of some spec that I'm not aware of? Again, a comment about this decision would be very clarifying.

3. I don't understand how passing `additionalData` in the `Seal` method and the `Open` method effect the output of the cipher text and plain text. In theory this is supposed to append the key to the output, but in practice it seems to do nothing.

So are there errors in this example? If not would it be possible to add some clarifying comments as to why these decisions were made?

Finally, thanks for publishing and maintaining this fantastic package 🙏 🙌

**Comment by jrick** [comment]
the nonce in this example is just zero bytes, not random.  since the key is never reused to encrypt a different message, it doesn't matter what the nonce is, but zero bytes still need to be allocated so the nonce can be provided to aead.Seal.

additional authenticated data is not included in the ciphertext, but it must be provided during the decryption.  message authentication will fail if the authenticated data is not the same as what was used by Seal.

**Comment by jrick** [comment]
and to be clear, by ciphertext i meant what aead.Seal was appending to the ciphertext slice in the example.  that slice also contains the plaintext public key, which is being extracted and used during Open, but Seal does not append any extra data for the additional authenticated data; rather it only modifies the MAC.

**Comment by davecgh** [comment]
1. The API for `cipher.AEAD` requires a nonce of the length `NonceSize()`.  Note that AES-GCM does not require the nonce to be random and allows it to be a counter , but, it absolutely must be unique for each message encrypted with the same key.  As you noted, the AES key is seeded from a randomly-generated ephemeral private key and is never reused.  Hence the example just initializes the nonce as a counter of the correct size required by `NonceSize()` starting at 0.

2. You could technically get way with not including the size for this particular example so long as both the sender and receiver hard code a value of 33 (to prevent canonicalization attacks) and understand the additional data is _always_ the ephemeral public key.  That said, looking at the example, I can see that it's probably not very clear for those not already familiar with AEAD that the additional unencrypted, but authenticated, data is the ephemeral key here and in more general protocols the additional data would likely consist of other information such as perhaps a timestamp to help prevent replay attacks, in which case that assumption of it _always_ being 33 bytes would no longer hold.

3. The additional data is public *unencrypted* data that is sent alongside the cipher text and both are authenticated.  The "cipher text" produced by AEAD is actually composed of the encrypted plain text along with an authentication tag.  Changing the additional data will not modify the encrypted plain text portion, rather, it will modify the authentication tag that is appended to it (the last 16 bytes in practice for these examples).  Perhaps the following small example of a more straightforward use of basic AES-GCM without the ECDHE shared derivation of the symmetric key via `secp256k1` or buffer reuse thrown into the mix will help clarify it:

```Go
package main

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/binary"
	"fmt"
)

func main() {
	// Hard coded shared private key of 1 for simplicity.
	var sharedPrivKey [16]byte
	sharedPrivKey[len(sharedPrivKey)-1] = 1

	// AES-GCM.
	block, err := aes.NewCipher(sharedPrivKey[:])
	if err != nil {
		panic(err)
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		panic(err)
	}

	// Create a nonce of the appropriate size initialized as a counter of 0.
	//
	// Note that this nonce must never be reused to encrypt a different message
	// with the same key pair.
	nonce := make([]byte, aead.NonceSize())
	fmt.Printf("nonce: %x\n", nonce)

	// Encrypt the plain text and generate an authenticate tag for both the
	// resulting cipher text as well as some additional data.
	plaintext := []byte("test message")
	additionalData := []byte("additional data")
	ciphertextPlusAuthTag := aead.Seal(nil, nonce, plaintext, additionalData)
	fmt.Printf("ciphertext plus auth tag: %x\n", ciphertextPlusAuthTag)

	// The message that is sent to the counterparty includes both the ciphertext
	// and the unencrypted additional data.
	var combined []byte
	combined = binary.LittleEndian.AppendUint32(combined, uint32(len(additionalData)))
	combined = append(combined, additionalData...)
	combined = append(combined, ciphertextPlusAuthTag...)
	fmt.Printf("combined message: %x\n", combined)

	// Everything from here on is on the receiver side.  Error handling for the
	// size of the additional data is elided to focus on the aead portion.
	receivedAdditionalDataSize := binary.LittleEndian.Uint32(combined[:4])
	receivedAdditionalData := combined[4 : 4+receivedAdditionalDataSize]
	receivedCiphertext := combined[4+receivedAdditionalDataSize:]
	fmt.Printf("received additional data size: %x\n", receivedAdditionalDataSize)
	fmt.Printf("received additional data: %x\n", receivedAdditionalData)
	fmt.Printf("received cipher text + auth tag: %x\n", receivedCiphertext)

	// Simulate the message being tampered with by changing the additional data.
	badAdditionalData := make([]byte, len(receivedAdditionalData))
	copy(badAdditionalData, receivedAdditionalData)
	badAdditionalData[0] = 0x55
	_, err = aead.Open(nil, nonce, receivedCiphertext, badAdditionalData)
	if err == nil {
		panic("did not get expected auth error")
	}
	fmt.Printf("result of tampering with additional data: %v\n", err)

	// Simulate the message being tampered with by changing the cipher text.
	badCiphertext := make([]byte, len(receivedCiphertext))
	copy(badCiphertext, receivedCiphertext)
	badCiphertext[1] = 0x55
	_, err = aead.Open(nil, nonce, badCiphertext, receivedAdditionalData)
	if err == nil {
		panic("did not get expected auth error")
	}
	fmt.Printf("result of tampering with cipher text: %v\n", err)

	// Authenticate both the cipher text and additional data and decrypt the
	// plain text.
	recoveredPlaintext, err := aead.Open(nil, nonce, receivedCiphertext, receivedAdditionalData)
	if err != nil {
		panic(err)
	}
	fmt.Printf("recovered plaintext: %s\n", recoveredPlaintext)
}
```

Output:
```
nonce: 000000000000000000000000
ciphertext plus auth tag: e1f7a4015c297d5f40c5498c8b9e011f86688aba7ff779924dc49cf3
combined message: 0f0000006164646974696f6e616c2064617461e1f7a4015c297d5f40c5498c8b9e011f86688aba7ff779924dc49cf3
received additional data size: f
received additional data: 6164646974696f6e616c2064617461
received cipher text + auth tag: e1f7a4015c297d5f40c5498c8b9e011f86688aba7ff779924dc49cf3
result of tampering with additional data: cipher: message authentication failed
result of tampering with cipher text: cipher: message authentication failed
recovered plaintext: test message
```

Now, if you take this example and replace the hard coded shared private key with one derived via ECDHE, replace the additional authenticated data with the ephemeral public key, and reuse some buffers to avoid extra allocations, it will hopefully be clear what the example in `secp256k1` is doing.

**Comment by marksalpeter** [comment]
Thank you for clarifying @jrick and thanks to @davecgh for the authenticated data example. I just checked for myself and what you said about the additional authenticated data is true! I had no idea it worked that way 😅.

Thanks again, this is a really excellent package.

**Comment by marksalpeter** [comment]
... Just out of curiosity, you don't happen to have anything for BIP 32 / 39 in here do you?

**Comment by davecgh** [comment]
There is [hdkeychain](https://pkg.go.dev/github.com/decred/dcrd/hdkeychain/v3) that is close to BIP32.

Do note that it was modified slightly in Decred such that the fingerprint uses a different hash function which means the serialized **extended keys** don't match up with BIP32.  However, if you use the [ChildBIP32Std](https://pkg.go.dev/github.com/decred/dcrd/hdkeychain/v3#ExtendedKey.ChildBIP32Std) method it will generate BIP32 compatible underlying private and public keys for a given derivation path.

There isn't anything for BIP39 available.

**Comment by marksalpeter** [comment]
Thanks I'll take a look at hdkeychain. What does decred do for 'recovery phrase' generation if there's no BIP39 equivalent?

**Comment by davecgh** [comment]
It just uses the [PGP word list](https://en.wikipedia.org/wiki/PGP_word_list) to encode a 256-bit seed along with a checksum byte (so 33 words total).  The seed is fed into the aforementioned hdkeychain and then we use BIP44 derivation paths with a coin type of 42.

The dictionary is small so it results in more words (which is indeed a little more cumbersome), but it's invertible and doesn't require NFKD (unlike BIP39) which has historically had a bunch of issues with compatibility and that was particularly true at the time Decred was launched along with the initial wallets which, at that point, were among the first to do recovery based on a single seed.

We'll likely eventually do something a little more clever if there is sufficient demand for it.

**Comment by marksalpeter** [comment]
Thanks for the info @davecgh. The PGP word list might be sufficient for my purposes as well, but fewer words is slightly more appealing imho. I'm going to go ahead and close this. I still think the example would benefit from either a comment explicitly stating that the nonce is intentionally left blank because of single use, but I'll leave that to your discretion. Thanks again for for all of the thoughtful and helpful answers 🙏

**Comment by davecgh** [comment]
> ... I still think the example would benefit from either a comment explicitly stating that the nonce is intentionally left blank because of single use ...

How's this?

```
 	//
	// Since a new ephemeral key is generated for every message ensuring there
	// is no key reuse and AES-GCM permits the nonce to be used as a counter,
	// the nonce is intentionally initialized to all zeros so it acts like the
	// first (and only) use of a counter.
```

**Comment by marksalpeter** [comment]
I like it :)

**Comment by davecgh** [comment]
The aforementioned comment update has been merged to master.
