### ISSUE TITLE
Remove planetdecred seeders from dcrd

### ISSUE THREAD

**Issue by monsa00** [decred/dcrd#2973]
Please remove mainnet-seed.planetdecred.org 54.203.216.110 and testnet-seed.planetdecred.org 54.203.216.110 from dcrd's seed list.

**Comment by davecgh** [comment]
PR #2974 is open to do this.  I'm sure you're already aware, but please do keep in mind that requests won't actually be removed from nodes in the wild until a new release of the software is made.
