### ISSUE TITLE
dcrec/secp256k1: new release to fix boringcrypto issue

### ISSUE THREAD

**Issue by Jorropo** [decred/dcrd#2990]
Hi,
[go-libp2p](https://github.com/libp2p/go-libp2p) is using your `secp256k1` implementation however the latest release (`v4.0.1`) [is broken with the boringcrypto go1.19 experiment](https://github.com/golang/go/issues/54486) which we want to use to replace a [custom cgo openssl wrapper](https://github.com/libp2p/go-openssl).
Turns out this is already fixed this in d567e996ced886eea82ac802b15c03a3d41722ed when implementing direct key generation, this allows to skip the std, skipping boring crypto and it just work.

We like to avoid depending on untagged commits when tagged ones are provided as this is a code smell,
I would like to know when we can expect a new release of the `dcrec/secp256k1` package.

Thx

**Comment by davecgh** [comment]
There wasn't really any reason we hadn't done a release other than there wasn't anything blocking on it and we tend to do most module releases close to full software releases.  However, since you were in need of one with the latest code, I just tagged a release for `dcrec/secp256k1/v4.1.0`.

**Comment by Jorropo** [comment]
Thx
