### ISSUE TITLE
RPC listtransactions is ordered by rand()

### ISSUE THREAD

**Issue by buzztiaan** [decred/dcrd#3]
Please sort transactions by time

**Comment by buzztiaan** [comment]
so , oldest tx gets reported first, newest tx is on bottom of listtransactions

and use time of blockchain to sort them, not confirmations

**Comment by jrick** [comment]
You'll have to give a convincing argument as to why transactions should be sorted by block header times and not blocks themselves.  Block headers timestamps can go backwards in time.

That code is untouched from btcwallet, so if any changes are made should be made there and then imported to dcrwallet after mainnet release during a sync.

**Comment by buzztiaan** [comment]
i was assuming the RPC was ment to be compatible with the 73486823623 daemons out there doing the exact same thing :D

**Comment by jrick** [comment]
I just reviewed bitcoin core's source.  It appears their wallet sorts based on the order the tx was first seen.  This is not the same as organizing by a timestamp.  Every tx entry in the db is given a position index which is incremented for every new tx added.

**Comment by jrick** [comment]
I should also say that I'm not too happy with the prospect of making a database change in btcwallet just to support this behavior.  In my mind, sorting by the blockchain order is the only order that actually matters.  I've also been moving my development efforts away from the legacy json-rpc server to a totally new rpc server with a home-grown API, which dcrwallet will hopefully adopt in the future as well.

**Comment by buzztiaan** [comment]
as long as the end result matches the output from other daemons, i'm all for it <3

**Comment by ocminer** [comment]
Is it planned to change the behavior to standard way like in other daemon ? I'm doing some crazy work in php/nomp to get the sorting correct, i'd love to drop that.

**Comment by buzztiaan** [comment]
this wont ever get better, sad coin , death by devs
