### ISSUE TITLE
add a new checkpoint

### ISSUE THREAD

**Issue by jolan** [decred/dcrd#304]
We should be doing this every release but it keeps being forgotten.

**Comment by marcopeereboom** [comment]
I agree.  Please handle this on next release.

**Comment by alexlyp** [comment]
Can we add checkpoints for testnet as well?

**Comment by jolan** [comment]
I will do testnet too since it's very painful to sync at the moment.

**Comment by jcvernaleo** [comment]
@jolan try waiting for the sync on a raspberry pi then we can talk about painful :)
