### ISSUE TITLE
Unable to override home directory

### ISSUE THREAD

**Issue by centromere** [decred/dcrd#3150]
When building/testing in a containerized environment (such as Nix), the default home directory (`/var/empty`) is inaccessible. This prevents the unit tests from functioning:

```
dcrd> ++ go test -p 12 ./. -args --appdata /private/tmp/nix-build-dcrd-1.8.0.drv-1/tmp.G5ZHoVaIR3
dcrd> 2023-06-28 20:49:03.438 [INF] RPCS: Generating TLS certificates...
dcrd> 2023-06-28 20:49:03.457 [INF] RPCS: Done generating TLS certificates
dcrd> 2023-06-28 20:49:03.457 [INF] RPCS: Generating TLS certificates...
dcrd> 2023-06-28 20:49:03.464 [INF] RPCS: Done generating TLS certificates
dcrd> Error creating a default config file: mkdir /var/empty: file exists
dcrd> --- FAIL: TestLoadConfig (0.00s)
dcrd>     config_test.go:30: Failed to load dcrd config: loadConfig: failed to create home directory: mkdir /var/empty: file exists
dcrd> Error creating a default config file: mkdir /var/empty: file exists
dcrd> --- FAIL: TestDefaultAltDNSNames (0.00s)
dcrd>     config_test.go:41: Failed to load dcrd config: loadConfig: failed to create home directory: mkdir /var/empty: file exists
dcrd> Error creating a default config file: mkdir /var/empty: file exists
dcrd> --- FAIL: TestAltDNSNamesWithEnv (0.00s)
dcrd>     config_test.go:56: Failed to load dcrd config: loadConfig: failed to create home directory: mkdir /var/empty: file exists
dcrd> Error creating a default config file: mkdir /var/empty: file exists
dcrd> --- FAIL: TestAltDNSNamesWithArg (0.00s)
dcrd>     config_test.go:74: Failed to load dcrd config: loadConfig: failed to create home directory: mkdir /var/empty: file exists
dcrd> FAIL
dcrd> FAIL      github.com/decred/dcrd  0.190s
dcrd> FAIL
```

The logic in [`appDataDir`](https://github.com/decred/dcrd/blob/cc33b719bca49c8e9e8a048b8c6bef9418dd9e9d/dcrutil/appdata.go#L22) will only consult the `HOME` environment variable if the lookup from `/etc/passwd` fails. This prevents me from overriding the value at runtime. If the `HOME` environment variable was consulted first, running the unit tests in a sandbox would be much easier.

**Comment by jrick** [comment]
We could special case /var/empty being read from the user info, and fallback to using HOME in that case. Thoughts @davecgh?

**Comment by jrick** [comment]
Although, I'm confused why it is even trying to write to the default home directory if a different --appdata was explicitly provided.  I don't think that's intuitive at all, seems like a bug.

**Comment by jrick** [comment]
I think config/flag parsing isn't occurring when main's tests are being run.  We could probably start doing that just for flags (but for testing i wouldn't want it to use any config file it might find)

**Comment by jrick** [comment]
This test should make the --appdata flag work (by changing the default that loadConfig chooses).  It only implements that flag, not all of them (would be far too invasive of a patch to try and make it do all of main's flag parsing).

@centromere can you confirm if this works?

```
diff /home/jrick/src/dcrd
commit - bc1f3613591180ab4e3a79914f32294a472195b9
path + /home/jrick/src/dcrd
blob - 45d9784386fa3ed778cfbf6e5623124ca9381430
file + config_test.go
--- config_test.go
+++ config_test.go
@@ -5,12 +5,28 @@ import (
 package main
 
 import (
+	"flag"
 	"os"
 	"path/filepath"
 	"strings"
 	"testing"
 )
 
+func TestMain(m *testing.M) {
+	appdata := flag.String("appdata", "", "change default tests appdata directory")
+	flag.Parse()
+
+	if *appdata != "" {
+		defaultHomeDir = *appdata
+	}
+
+	// trim -test.* flags from the command line arguments list to allow
+	// go-flags tests to succeed.
+	os.Args = os.Args[:1]
+
+	os.Exit(m.Run())
+}
+
 // In order to test command line arguments and environment variables, append
 // the flags to the os.Args variable like so:
 //   os.Args = append(os.Args, "--altdnsnames=\"hostname1,hostname2\"")
@@ -80,9 +96,3 @@ func TestAltDNSNamesWithArg(t *testing.T) {
 	}
 	os.Args = old
 }
-
-// init parses the -test.* flags from the command line arguments list and then
-// removes them to allow go-flags tests to succeed.
-func init() {
-	os.Args = os.Args[:1]
-}
```

**Comment by jrick** [comment]
(if that works, the PR will use --testappdata or something else instead, so it wouldn't conflict if we wrote a test for the appdata go-flags option)

**Comment by davecgh** [comment]
I see a couple of things here.

The first is that the flags aren't being parsed properly when those specific tests are run.  I will address that shortly in a way that doesn't muck with the flags globally which should resolve this issue.

For the second, while it isn't the root cause of this issue, I think it's probably worth revisiting the order that the `AppData` func searches to bias towards the environment variable first so it's easier to override in containers in general.

**Comment by jrick** [comment]
Well, there is always going to be some "mucking" of the flags already, since go test already uses the stdlib flags package to parse test flags that it gets passed.  Using `flag` like this (note: without `ExitOnError`) will stop parsing at the first unrecognized flag or argument.  That probably also means that we could get rid of the slice operation to remove the first element.

**Comment by jrick** [comment]
This works better:

```
diff /home/jrick/src/dcrd
commit - bc1f3613591180ab4e3a79914f32294a472195b9
path + /home/jrick/src/dcrd
blob - 45d9784386fa3ed778cfbf6e5623124ca9381430
file + config_test.go
--- config_test.go
+++ config_test.go
@@ -5,12 +5,25 @@ import (
 package main
 
 import (
+	"flag"
 	"os"
 	"path/filepath"
 	"strings"
 	"testing"
 )
 
+func TestMain(m *testing.M) {
+	arg0 := os.Args[0]
+
+	flag.Parse()
+
+	// trim -test.* flags from the command line arguments list to allow
+	// go-flags tests to succeed.
+	os.Args = append([]string{arg0}, flag.Args()...)
+
+	os.Exit(m.Run())
+}
+
 // In order to test command line arguments and environment variables, append
 // the flags to the os.Args variable like so:
 //   os.Args = append(os.Args, "--altdnsnames=\"hostname1,hostname2\"")
@@ -80,9 +93,3 @@ func TestAltDNSNamesWithArg(t *testing.T) {
 	}
 	os.Args = old
 }
-
-// init parses the -test.* flags from the command line arguments list and then
-// removes them to allow go-flags tests to succeed.
-func init() {
-	os.Args = os.Args[:1]
-}
```

```
$ go test . -args -- --appdata=/tmp/dcrdappdata 
ok  	github.com/decred/dcrd	0.048s
$ stat /tmp/dcrdappdata
1027 129600 drwx------ 3 jrick wheel 521696 512 "Jun 28 18:40:56 2023" "Jun 28 18:40:56 2023" "Jun 28 18:40:56 2023" 16384 4 0 /tmp/dcrdappdata
```

**Comment by davecgh** [comment]
That looks better than the original version, but it's still incorrect because it then strips everything after the `--`.  You can see this by e.g. adding a `fmt.Println(os.Args)` to `TestLoadConfig` and invoking with your example command.

What I was planning to do is just create a little test helper that only the tests dealing with `loadConfig` invoke rather than doing it globally in `TestMain` or `init`.

Something like:

```Go
func runWitoutTestFlags(fn func()) {
	oldArgs := os.Args
	newArgs := make([]string, 0, len(os.Args))
	for _, arg := range os.Args {
		if !strings.HasPrefix(arg, "-test.") {
			newArgs = append(newArgs, arg)
		}
	}
	if len(newArgs) > 1 && newArgs[1] == "--" {
		newArgs = append(newArgs[:1], newArgs[2:]...)
	}
	os.Args = newArgs
	fn()
	os.Args = oldArgs
}
```

**Comment by jrick** [comment]
i'm not sure what you mean.

```
$ go test -v -run TestLoadConfig . -args -- --appdata=/tmp/dcrdappdata
=== RUN   TestLoadConfig
[/tmp/go-build2623271271/b001/dcrd.test --appdata=/tmp/dcrdappdata]
--- PASS: TestLoadConfig (0.00s)
PASS
ok  	github.com/decred/dcrd	0.008s
```

**Comment by davecgh** [comment]
On windows with your diff:

```
go test -v -run TestLoadConfig . -args -- --appdata=%TEMP%\dcrdappdata
[C:\Users\davec\AppData\Local\Temp\go-build195321261\b001\dcrd.test.exe]
PASS
```

**Comment by jrick** [comment]
?

```
PS C:\Users\jrick\src\dcrd> go test -v -run TestLoadConfig . -args -- --appdata=/tmp/dcrdappdata
=== RUN   TestLoadConfig
[C:\Users\jrick\AppData\Local\Temp\go-build2351895450\b001\dcrd.test.exe --appdata=/tmp/dcrdappdata]
--- PASS: TestLoadConfig (0.02s)
PASS
ok      github.com/decred/dcrd  0.325s
```

**Comment by jrick** [comment]
same thing in cmd.exe with cmd.exe syntax instead of powershell.

**Comment by davecgh** [comment]
Meh, I forgot to remove the `init` when going back and forth on the latest, so it was being stripped.  That works.  Feel free to PR it.

I still think those tests should be reworked altogether and combined, but this works to resolve the issue quickly in the mean time.

**Comment by davecgh** [comment]
I was looking at changing `AppDataDir` over to use the `HOME` environment variable first, and it's an easy enough change.

However, I worry that it might end up causing some existing users to suddenly "lose" their database due to it potentially living somewhere else.  For almost all cases `HOME` will be the same value, but not all.

Instead, what do you think about supporting the `DCRD_APPDATA` environment variable (which gets overridden by `--appdata` if specified) in the same way `DCRD_ALT_DNSNAMES` and `--altdnsnames` behave?

That way containers can easily override it via an environment variable which is typically the preferred approach.

**Comment by centromere** [comment]
Hi @davecgh, that seems reasonable.

**Comment by jrick** [comment]
tossing in my support for the appdata environment variable as well

**Comment by davecgh** [comment]
Support for setting the directory via the `DCRD_APPDATA` environment variable has been merged.

```bash
$ DCRD_APPDATA=/tmp/foo/dcrd go test
2023-06-28 22:56:17.870 [INF] RPCS: Generating TLS certificates...
2023-06-28 22:56:17.898 [INF] RPCS: Done generating TLS certificates
2023-06-28 22:56:17.908 [INF] RPCS: Generating TLS certificates...
2023-06-28 22:56:17.918 [INF] RPCS: Done generating TLS certificates
PASS
ok      github.com/decred/dcrd  0.354s
$ $ ls /tmp/foo
dcrd.conf  logs/
```
