### ISSUE TITLE
Request to change r and s in secp256k1 ecdsa signature to exported variable R and S

### ISSUE THREAD

**Issue by minizilla** [decred/dcrd#3187]
The title says it all.

**Comment by davecgh** [comment]
I'm not opposed to exposing them via methods (e.g. `func (*Signature) R() secp256k1.ModNScalar`).  Is that sufficient?

I'd prefer not to expose the fields directly because that would prevent the internal format from being changed in the future if needed (for example, .

**Comment by minizilla** [comment]
Yeah that is sufficient.

**Comment by minizilla** [comment]
Can you let me do the PR?

**Comment by davecgh** [comment]
Sure.  I was going to bang it out, but all yours.

**Comment by lazynina** [comment]
Is it possible to cut a new release of github.com/decred/dcrd/dcrec/secp256k1/v4 with these updates? I'd like to be able to use this new functionality? @davecgh

**Comment by davecgh** [comment]
> Is it possible to cut a new release of github.com/decred/dcrd/dcrec/secp256k1/v4 with these updates? I'd like to be able to use this new functionality?

I've opened PR #3227 to prepare a new release.  Once that is approved and merged, I'll cut a `v4.3.0` release.
