### ISSUE TITLE
Reported errors from mining pool

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrd#324]
[ERR] MINR: failed to check template while duplicating a parent: couldn't find node 0000000000000355df9d413d9b222351c2e1c4aee5f30339e7ddd15fdc509e91 in best chain

[ERR] RPCS: Failed to create new block template: couldn't find node 00000000000008e762b5eab8f4607c442e7c523cb7e072b9e7922dc9e4148c1e in best chain

[ERR] RPCS: Failed to create new block template: failed to do final check for check connect block when making new block template: couldn't find node 
0000000000000f56a0fb9ae05813e03a9f3bca14f34e9a3e1d6908528eb00ad8 in best chain

[ERR] RPCS: Failed to create new block template: failed to do final check for check connect block when making new block template: unable to find input transaction a520091f47a83fc0bc0c21c9dfecffccfa4c4b667daf8b1e2e9b9a958475ee54 referenced from transaction be8c46a620990ac8289132fcd48aee17ee604e2c6c0b405dfc879c764b0aaa88

Was reported on 0.2.0 dcrd with common options.  Reported from coinmine.pl

**Comment by alexlyp** [comment]
`14:29:01 2016-08-24 [INF] CHAN: REORGANIZE: Block 00000000030702c86ce5c975f748d0ce2b9cc51f79080903e07dbf43af8d63ca is causing a reorganize.
14:29:02 2016-08-24 [INF] CHAN: REORGANIZE: Chain forks at 00000000027ed24ed72f669e1bf091563255c7b05bae224e576ba9795e8e60a3, height 147645
14:29:02 2016-08-24 [INF] CHAN: REORGANIZE: Old best chain head was 000000000037989c138244ae4ec57dcba01917bba42ddc330304fbe1292876f0, height 147646
14:29:02 2016-08-24 [INF] CHAN: REORGANIZE: New best chain head is 00000000030702c86ce5c975f748d0ce2b9cc51f79080903e07dbf43af8d63ca, height 147647
14:29:02 2016-08-24 [INF] BMGR: Processed 2 blocks in the last 1m7.79s (7 transactions, height 147647, 2016-08-24 14:28:57 +0000 UTC)
14:29:02 2016-08-24 [WRN] BMGR: error found while trying to check incoming block for hidden votes: template did not have the same parent as the incoming block
14:29:02 2016-08-24 [DBG] MINR: Too few voters found on any HEAD block, recycling a parent block to mine on
14:29:02 2016-08-24 [DBG] MINR: Cached mining templates are no longer current, resetting
14:29:02 2016-08-24 [ERR] MINR: failed to check template while duplicating a parent: couldn't find node 000000000037989c138244ae4ec57dcba01917bba42ddc330304fbe1292876f0 in best chain
14:29:02 2016-08-24 [ERR] RPCS: Failed to create new block template: couldn't find node 000000000037989c138244ae4ec57dcba01917bba42ddc330304fbe1292876f0 in best chain
14:29:02 2016-08-24 [DBG] MINR: Too few voters found on any HEAD block, recycling a parent block to mine on`

We have seen this in our testnet mining rig.  Appears to be possible race during reorgs.  Should be using the new chain head instead of the reorged out one.

**Comment by feeleep75** [comment]
Just checked and same issue exist in 0.3.0:
```
19:16:06 2016-08-26 [INF] CHAN: FORK: Block 00000000000004d45fa33c7edf435759f3a934be0ab347b7bc8075b61a542d9a (height 57916) forks the chain at height 57915/block 00000000000002ea67a4a20a57beeb2a9aaf9b4eaa789595fb8e6567e04cc325, but does not cause a reorganize
19:16:11 2016-08-26 [INF] CHAN: REORGANIZE: Chain forks at 00000000000002ea67a4a20a57beeb2a9aaf9b4eaa789595fb8e6567e04cc325, height 57915
19:16:11 2016-08-26 [INF] CHAN: REORGANIZE: Old best chain head was 000000000000097b865fe6c174caa15986f77ac2efa02e58bfabc226dd275891, height 57916
19:16:11 2016-08-26 [INF] CHAN: REORGANIZE: New best chain head is 00000000000004d45fa33c7edf435759f3a934be0ab347b7bc8075b61a542d9a, height 57916
19:16:11 2016-08-26 [WRN] MINR: incongruent number of voters in mempool vs mempool.voters; not enough voters found
19:16:11 2016-08-26 [ERR] MINR: failed to check template while duplicating a parent: couldn't find node 000000000000097b865fe6c174caa15986f77ac2efa02e58bfabc226dd275891 in best chain
19:16:11 2016-08-26 [ERR] RPCS: Failed to create new block template: couldn't find node 000000000000097b865fe6c174caa15986f77ac2efa02e58bfabc226dd275891 in best chain
19:16:18 2016-08-26 [INF] CHAN: REORGANIZE: Block 0000000000000288e4c46047a89f6a0b8ec468bf23cf97be49a116d4acf1a014 is causing a reorganize.
19:16:18 2016-08-26 [INF] CHAN: REORGANIZE: Chain forks at 00000000000002ea67a4a20a57beeb2a9aaf9b4eaa789595fb8e6567e04cc325, height 57915
19:16:18 2016-08-26 [INF] CHAN: REORGANIZE: Old best chain head was 00000000000004d45fa33c7edf435759f3a934be0ab347b7bc8075b61a542d9a, height 57916
19:16:18 2016-08-26 [INF] CHAN: REORGANIZE: New best chain head is 0000000000000288e4c46047a89f6a0b8ec468bf23cf97be49a116d4acf1a014, height 57917
19:16:19 2016-08-26 [INF] RPCS: Block submitted via getwork accepted: 0000000000000288e4c46047a89f6a0b8ec468bf23cf97be49a116d4acf1a014
19:16:19 2016-08-26 [ERR] MINR: failed to check template while duplicating a parent: couldn't find node 00000000000004d45fa33c7edf435759f3a934be0ab347b7bc8075b61a542d9a in best chain
19:16:19 2016-08-26 [ERR] RPCS: Failed to create new block template: couldn't find node 00000000000004d45fa33c7edf435759f3a934be0ab347b7bc8075b61a542d9a in best chain
```

**Comment by alexlyp** [comment]
@feeleep75 this has been shown to fix the problem on testnet, it is currently on master.  We will be including this in our next release that is planned on next Monday (0.4.0) will try and keep you updated
