### ISSUE TITLE
DecodeHeaders has a large number of allocs

### ISSUE THREAD

**Issue by cjepson** [decred/dcrd#357]
The following is reported for branch #355 with go test -bench=. -benchmem=true:

`BenchmarkDecodeHeaders-8                     300           6548673 ns/op          593793 B/op           12002 allocs/op`

Comparatively, dcrd uses almost no allocs when decoding headers. Changing from readElements to write directly to the preallocated memory using a serializer should fix this.

**Comment by jpz** [comment]
Yes, there's a bit discrepancy between btcd and dcrd here, 24 allocs per operation it appears.

I'm happy to have a look at this as I see it's been open a year.  However I don't want to get in the way of other btcd -> dcrd merges that may be in the pipeline.

**Dcrd**
```
$ go test -bench=BenchmarkDecodeHeaders -benchmem=true
goos: darwin
goarch: amd64
pkg: github.com/decred/dcrd/wire
BenchmarkDecodeHeaders-8   	     500	   3876189 ns/op	  561793 B/op	   12002 allocs/op
PASS
ok  	github.com/decred/dcrd/wire	2.498s
```

**Btcd**
```
$ go test -bench=BenchmarkDecodeHeaders -benchmem=true
goos: darwin
goarch: amd64
pkg: github.com/btcsuite/btcd/wire
BenchmarkDecodeHeaders-8   	    2000	   1008441 ns/op	  229376 B/op	       2 allocs/op
PASS
ok  	github.com/btcsuite/btcd/wire	3.045s
```
