### ISSUE TITLE
Error descriptions should be lowercase

### ISSUE THREAD

**Issue by cjepson** [decred/dcrd#363]
A number of error strings in blockchain begin with their first letter capitalized.  This should be lower case.

**Comment by atriviss** [comment]
why @cjepson

**Comment by jolan** [comment]
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

**Comment by jcmincke** [comment]
This item needs some clarifications:

1. Should test code be corrected as well?
2. Should files under dcrd/vendor directory be corrected?
3. Are common uppercase acronyms (RPC, DER, HTTP, JSON, WAN) left in uppercase?
4. What about Decred's specific acronyms/terms such as in the following code snippets:
```
ErrInvalidIsNo      = errors.New("one and only one IsNo rule violation") ...
ErrInvalidBothFlags = errors.New("IsNo and IsAbstain may not be both " ...
ErrStackNoIf = errors.New("OP_ELSE or OP_ENDIF with no matching OP_IF") ...
```
5. Function/variable/type names appearing in error messages : do we lowercase them or not.
To me, that would lower readability as in:
```
str := "%s: the rpcmaxwebsocketconcurrentrequests option may " +
      "not be less than 0 -- parsed [%d]"

str := "%s: invalid minrelaytxfee: %v"
```
6. Should the name "Decred" also be in lower case?
