### ISSUE TITLE
wire.BlockHeader.BlockSha should be renamed BlockHash

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#365]
It's not a SHA.

~~Will also open an issue for btcd since changing this is in line with its change over to the more abstract `chainhash` package.~~ already done it seems. just need to sync.

**Comment by jrick** [comment]
And it's not just BlockSha either, there are a lot of methods in this package that are incorrectly named using Sha.

**Comment by davecgh** [comment]
There is an upstream btcd PR that eradicates all mentions of sha.  Whenever it gets merged, it will take care of a lot of them, but Decred has a lot of new code for the stake system which obviously won't be covered by that PR and will need to be handled as well.

**Comment by jrick** [comment]
If there were even more usages of sha in the code, I was unaware of them.  The renames from sha to hash in the wire package are already available on master btcd.  I'm not sure why they weren't pulled in a merge.

**Comment by davecgh** [comment]
This was completely in PR #729.
