### ISSUE TITLE
getseed strange error

### ISSUE THREAD

**Issue by avongluck-r1soft** [decred/dcrd#37]
getseed from the wallet is showing a strange error:

$ ./dcrctl --wallet -u HAHAHAHA -P NOTAPASS --notls getseed
-4: manager is locked

That looks like an error message is being cut off...

**Comment by davecgh** [comment]
It looks right to me.  I agree it's certainly a poor error message and not a very descriptive error, but it means the address manager for the wallet is locked.  You need to unlock the wallet with `./dcrctl --wallet walletpassphrase your_private_encryption_passphrase timeout-in-seconds.

That said, I'm quite disappointed to see this RPC available at all.  I **really** don't think the seed should be available via RPC, even if protected by the private passphrase.

**Comment by cjepson** [comment]
I disagree that it shouldn't exist. I think all RPC commands should be funcs hooked in config.go to either an actual handling func or a function that returns a disabled RPC call exception. I plan to work on that in the next few days after more of stake pool is ironed out. Agree that it should be hard disabled for compilation by default.

**Comment by jcvernaleo** [comment]
I have to disagree with @davecgh if you have access to the wallet AND have the passphrase then it is already game over and you can just send the funds elsewhere anyway.  I see no security gain by disallowing showing the seed at that point.  But as you pointed out, the error is correct.  It could be displayed in a more user friendly way for sure (as could most of the rpc interface) but it does provide the relevant information.

**Comment by davecgh** [comment]
That is not the case I'm talking about at all.  If you are staking, you need to have the wallet unlocked.  Once the wallet is unlocked, any process, at any time, can issue an RPC.  This is an incredibly dangerous RPC.

**Comment by jcvernaleo** [comment]
So the presence or absence of that RPC call is kind of off topic for this issue (and @cjepson is changing that soon anyway).  Since there is no action needed related to the error (the message is not cutoff), I'm closing the issue.
