### ISSUE TITLE
config var for default connection timeout

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#383]
"no answer for 5m0s -- disconnecting"
https://github.com/decred/dcrd/blob/master/peer/peer.go#L53

On an uplink that intermittently will drop all connections, 5m is really too long because thats easily the length of a whole block cycle, and a stake vote could get missed. I would like this to be a user config setting, and I would probably set it to 30 seconds for myself.

Or maybe it just makes sense to reduce the default const to 30 sec like the other const timeouts.

**Comment by marcopeereboom** [comment]
Can you do a diff?

**Comment by dajohi** [comment]
I'll do this.  It needs https://github.com/btcsuite/go-socks/pulls/3

**Comment by jcmincke** [comment]
There are several possibilities for checking the validity of idle timeout against stallTickInterval, stallResponseTimeout or any other data, private to the peer package.

1. Do the check in config.go (as in my PR https://github.com/decred/dcrd/pull/854), hard coding the values of stallTickInterval, stallResponseTimeout.
This is not the best approach for there is a duplication of information in both config.go and peer.go.

2. Make stallTickInterval and stallResponseTimeout config vars as well. So config.go would have all the data it needs to do the validation but that also means that config.go somewhat 'knows' some logic which should remain private to peer.go

3. Make stallTickInterval and stallResponseTimeout config vars but call a validation function defined in package peer. But that would make config.go depend on peer.go.

4. Don't do validation in config.go but inside peer.go upon usage. I.e. in newPeerBase() but that might come a bit too late.

Are there decred's specific standards for handling these kinds of situations?
