### ISSUE TITLE
ticketfeeinfo includes block in both windows

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#388]
In this example, the startheight of the new window overlaps with the endheight of the previous window. They both show 67680, which puts the block in two windows. 

> ticketfeeinfo 0 2
> {
>   "feeinfomempool": {
>     "number": 2574,
>     "min": 0.01010101,
>     "max": 0.91216216,
>     "mean": 0.02518287,
>     "median": 0.01013513,
>     "stddev": 0.03929079
>   },
>   "feeinfoblocks": null,
>   "feeinfowindows": [
>     {
>       "startheight": 67680,
>       "endheight": 67810,
>       "number": 2579,
>       "min": 0.05151515,
>       "max": 0.98141263,
>       "mean": 0.2100907,
>       "median": 0.12267657,
>       "stddev": 0.20460539
>     },
>     {
>       "startheight": 67536,
>       "endheight": 67680,
>       "number": 258,
>       "min": 0.01010101,
>       "max": 0.01466932,
>       "mean": 0.01268549,
>       "median": 0.0130505,
>       "stddev": 0.00102283
>     }
>   ]
> }

**Comment by chappjc** [comment]
I assumed this was [start, end).

**Comment by davecgh** [comment]
Right, the end is exclusive.  Is there anything to be done here?
