### ISSUE TITLE
blockchain: errorCodeStrings map is missing some entries

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#391]
This results in the error not printing with it's name.  I didn't go through them all, but one missing entry is `ErrCoinbaseHeight`.  As a result attempting to print that error gives `Unknown ErrorCode (33)` instead of `ErrCoinbaseHeight` as expected.

I would highly suggest it follows the model used elsewhere in the code base where there is a test failure when the number of map entries does not match the number of error definitions.

**Comment by jrick** [comment]
use [stringer](https://godoc.org/golang.org/x/tools/cmd/stringer)!

**Comment by davecgh** [comment]
That still wouldn't catch the case of new error codes being added without regenerating the definitions, so in either case there should be a test that fails when they're out of sync imo.
