### ISSUE TITLE
ticket output creation and ticket purchases should be mined together

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#394]
The first block of a stake period is getting 0 tickets mined.

https://mainnet.decred.org/block/00000000000005a06546fd4ae6d7be31e8e4055c48f72b86623e0ae0bd49a5ef

All the ticket output creation txs are mined in this block, but no actual ticket purchases. Since a ticket purchase is just a dependent transaction, it should be no problem to include it in the same block.

**Comment by marcopeereboom** [comment]
The outputs are not confirmed until the next block, by proof of stake miners. they can not be immediately spent in the same block until they are confirmed, but that can not happen until the block is mined.  The way to fix this would be to make a new ticket buying mode in wallet that slightly overpays and creates a number of outputs based on the max estimated ticket difficulty before the new difficulty block is mined, and then spends those outputs immediate and gives change back to the wallet.

**Comment by raedah** [comment]
Are you saying that decred doesnt support the mining of parent and child transactions in the same block? Or is this a technical limitation because of the stake purchases existing on a segregated chain?
