### ISSUE TITLE
server: Fails to parse IPv6 addresses with zone id

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#41]
There is an issue on Mac OSX where it fails to parse the localhost IPv6 because it has a zone ID in it.

> 21:02:12 2016-02-09 [ERR] DCRD: Unable to start server on [:9108]: 'fe80::1%lo0' is not a valid IP address

This was fixed in upstream btcd via https://github.com/btcsuite/btcd/pull/538.  That fix should be cherry-pick to dcrd to prevent this.

**Comment by jcvernaleo** [comment]
Thanks.  Fixed with commit  f92e75a (cherry-picked from btcsuite/btcd).
