### ISSUE TITLE
show connection stats

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#428]
When dcrd displays msgs such as

11:00:19 2016-10-19 [INF] BMGR: Lost peer 107.172.25.91:9108 (outbound)
11:00:19 2016-10-19 [INF] BMGR: New valid peer 46.102.244.61:9108 (outbound) (/dcrwire:0.2.0/dcrd:0.4.0/)

it would be nice if it gave information about how many peers are up. So I can tell if 7 of 8 peers are connected, or if 0 of 8 peers are connected.

**Comment by dajohi** [comment]
Is
```$ dcrctl getpeerinfo```
or
```$ dcrctl getconnectioncount```
what you are looking for?

**Comment by raedah** [comment]
yeah that works thanks
