### ISSUE TITLE
Late block notifier

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrd#443]
It is possible that this should go in a different repo but for now this seems like a reasonable place.

It would be helpful (particularly for testnet) to have a program that just listens for blocks and sends an email or other notification if no block is seen for longer than a certain amount of time (30m maybe).  This would help problems earlier.

There may be other indicators of network health that could be added later.

I have a simple program that listens for blocks that could probably be hacked to form the basis for this.

Initially discussed this idea with @alexlyp on irc.

**Comment by davecgh** [comment]
This is handled via dcrdata these days.  No longer applies.
