### ISSUE TITLE
dcrctl exposes the RPC password in the process list

### ISSUE THREAD

**Issue by jyap808** [decred/dcrd#47]
Running this command
```dcrctl -u user -P password --terminal```

The plain text password is displayed.

**Comment by jcvernaleo** [comment]
You can specify the username and password in the config file instead which will not show anything in the process list.
jcv@koopa ~ $ cat ~/.dcrctl/dcrctl.conf 
[Application Options]

rpcuser=USER
rpcpass=PASSWORD
