### ISSUE TITLE
datadir not used for RPC cert+key

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#52]
When using the `--datadir` switch with `dcrd`, the expectation is that the rpc.cert/.key files will be accessed from there, where the block db is also located.  However, rpc.cert ends up in the default location `$LOCALAPPDATA\Dcrd\rpc.cert` (or wherever depending on OS depending on `dcrutil.AppDataDir()`).

This is not consistent with the behavior of `dcrwallet`, where the cert/key files are read and written to according to the `--datadir` argument:
https://github.com/decred/dcrwallet/blob/master/config.go#L358

There is no similar logic for dcrd.  The folder is always `dcrutil.AppDataDir("dcrd", false)`, the default.

**Comment by jcvernaleo** [comment]
@chappjc Nice catch.  It looks like this is behavior we inherited from btcd so I'll do a PR with a fix there and then get it in dcrd.

**Comment by davecgh** [comment]
I agree that ideally the behavior should be consistent, but I disagree that `dcrd` should be changed.  

The RPC cert/key are not in any way tied to the block chain data.  There are specific options (`--rpccert` and `--rpckey`) to deal with changing their paths.

In addition to having nothing to do with data (which is referring to block chain data and associated indexes, stake pool, etc), moving them with the data directory would mean they are no longer in the default location for `dcrwallet` and `dcrctl` to find which means they would also have to overridden there as well making things more complicated.

I wasn't aware that btcwallet/dcrwallet had that behavior, but as just described, I think that behavior is incorrect.

**Comment by chappjc** [comment]
Then why is the default to put the block chain data and the RPC cert/key in the same folder?  Simplicity, presumably.

If `dcrwallet` is changed to match `dcrd`, _that_ would add new complexity as you'd have to specify cert locations when starting `dcrd`.  I already expect to specify these locations when using `dcrctl` and `dcrwallet` if I've specified a non-default datadir for either daemon.

I believe that if you are using `--datadir`, you almost certainly want to put the cert+key somewhere other than the default folder. When I use `dcrwallet --datadir [custom_wallet_dir] ...` it nicely finds the wallet's cert+key where I want it, away from the default folder, and that's also where I point `dcrctl` for the cert when issuing wallet commands.  If `dcrwallet` changes, an extra switch is required to specify the wallet's cert+key location.

When it comes to `dcrctl`, I already have to use `-c, --rpccert` when issuing a command to the wallet .  I don't think it's too much to ask to use `dcrwallet --cafile` to point to your custom `dcrd` datadir.

**Comment by jrick** [comment]
The issue here is that wallet's --datadir doesn't match dcrd's --datadir.  wallet's represents ~/.dcrwallet/, while dcrd's represents ~/.dcrd/data/ (on unix obviously) which is used for blockchain data, not all application data.

**Comment by davecgh** [comment]
The only reason you have to specify -c on dcrctl is precisely because `dcrwallet` is doing the wrong thing and moving the RPC cert/key away from the home directory when `--datadir` is specified.  As the name implies, `--datadir` should move the wallet **data**, not the RPC server credentials that have nothing to do with the wallet's database.

**Comment by chappjc** [comment]
OK, the RPC server creds are not "data".  Noted.

I guess I'll just start using `dcrd --rpccert=... --rpckey=... --datadir= ...` to prepare for the change.

**Comment by alexlyp** [comment]
Sounds like this was resolved with #109 
Closing
