### ISSUE TITLE
getwork not returning valid result - number of SSGen tx in block ... was not the 4 voters..

### ISSUE THREAD

**Issue by ocminer** [decred/dcrd#53]
I'm starting to have issues with the getwork call not giving valid results, the log is then full of this:

10:20:11 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:11 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:12 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:12 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block e789dce2d7d74e8bcb9a02766c5de563e80d0b48991eec15cb610564f1224f6f was not the 4 voters expected from the header!
10:20:12 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block 80e2b2090715798b59966f0a9410e131f8dfc29922b0869837d8a2e4a33e9c04 was not the 4 voters expected from the header!
10:20:12 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block 80e2b2090715798b59966f0a9410e131f8dfc29922b0869837d8a2e4a33e9c04 was not the 4 voters expected from the header!
10:20:12 2016-02-24 [ERR] MINR: failed to check template: Error in stake consensus: The number of SSGen tx in block 80e2b2090715798b59966f0a9410e131f8dfc29922b0869837d8a2e4a33e9c04 was not the 4 voters expected from the header!
10:20:12 2016-02-24 [ERR] RPCS: Failed to create new block template: Error in stake consensus: The number of SSGen tx in block 80e2b2090715798b59966f0a9410e131f8dfc29922b0869837d8a2e4a33e9c04 was not the 4 voters expected from the header!

It catches up eventually after a few seconds and then getwork is returning valid data again - in the time between my mining pool is literally in "zombie mode" because there is no valid work to work on..

**Comment by cjepson** [comment]
Known bug from testnet days. I'll see about actually squashing it this week. It looks like the template somehow gets updated for the number of voters without actually changing the number in the header. You could probably fix it with a hack by incrementing voters when this error is caught, but I'd like to figure out why it's happening in the first place.

**Comment by chappjc** [comment]
It's disruptive to the miners.  I've had to set the retry parameters to something lower than default (30 seconds with ccminer).

**Comment by cjepson** [comment]
Can you give any more information about when it happens? Jolan said it's only after a block comes in for him, so I have a few functions to audit that might be the root cause.

**Comment by cjepson** [comment]
Got this down to a single function. Should be a fix for it soon.

**Comment by cjepson** [comment]
Fix being tested on my branch cjepson:cj_260216debugmining.
