### ISSUE TITLE
Allow disabling file-based logging

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#543]
My use case: I have created a service on my operating system for dcrd.  This makes it easier to administer and allows it to be automatically started upon boot and even restarted after a crash.  It also automatically saves logs from the application's stdout, making the logging to $appdata/logs/ redundant.  I would like to turn it off, but there does not appear to be any way of currently doing so.

Opening this for dcrd but this same issue equally applies to dcrwallet, btcd, and btcwallet as well.

**Comment by marcopeereboom** [comment]
I wouldn't mind having a flag to make logging go only to console.  That what you are thinking of with this issue?

**Comment by jrick** [comment]
yes, or --logdir='' to disable it (right now, it replaces this with the default value instead of turning off the file logging)

**Comment by marcopeereboom** [comment]
You mean --logdir="" ?

**Comment by jrick** [comment]
same thing (I know it doesn't look like it but those were two single quotes)

**Comment by marcopeereboom** [comment]
@davecgh do you have an opinion on this?  If not I'll go do this for both btcd and dcrd.

**Comment by davecgh** [comment]
I'm not opposed to the idea.

**Comment by jrick** [comment]
Last i looked --logdir="" would not work because when it is the empty string it is replaced with the default location.  We can't make the default flag to be the actual directory because it is relative to the --appdata directory, and changing that would mean that the log directory doesn't change with it, unless we have a mechanism to detect explicitly set flags (when a flag is relative to something else, and was not explicitly set, then it can be set to a new default).

For now, i've been running with local patches that just turn off all file logging.

**Comment by davecgh** [comment]
`--nofilelogging`

**Comment by jrick** [comment]
Trying not to make the mile-long help text even longer :)
