### ISSUE TITLE
Check 0.7.0 performance on RasberryPi ( or any arm more generally)

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrd#544]
So we can start to track/benchmark our releases on some of the less utilized architectures

**Comment by jcvernaleo** [comment]
I did all testing on a raspberry pi 2 B (so not the current fastest model 3, but not the one right before that) running the latest Raspbian.
Mainnet IBD:
```
10:10:55 2017-01-10 [INF] DCRD: Version 0.7.0-beta
19:37:38 2017-01-10 [INF] BMGR: Processed 8 blocks in the last 10.5s (16 transactions, 55 stake transactions, height 97365, 2017-01-10 18:12:21 -0500 EST)
```
9h27m

Testnet IBD took about 11h.

**Comment by jcvernaleo** [comment]
I have other arm devices I could test (beaglebone black, chromebook, other random things) but the raspberry pi is probably the most common in the wild so I think this test should be sufficient.  Can always reopen if desired.
