### ISSUE TITLE
Default autogenerated certificate should include local IPs

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#551]
It's rather ridiculous that the generated cert does not include all local IP addresses by default and instead defaults only to adding loopback and the machine hostname.  This is a huge inconvenience when trying to run dcrd and clients on different machines on the same network.

If that's not possible, we can at least inspect the RPC listen addresses in the config file and generate a cert that includes all of those.

**Comment by jrick** [comment]
I suppose there is one possible concern here and that is leaking some info about your internal network if you expose the RPC server outside your network.  Any client will then be able to see what your local IP address is of the box that you are running dcrd on.

**Comment by marcopeereboom** [comment]
I think that is the general consensus for not adding it.

What are we going to do with this issue?

**Comment by jcvernaleo** [comment]
I always have to add my local ip address to the certs I make so doing this would save me a step but as it is something I do really infrequently, I could live with it either way.

Most people probably have local ips in the 192.168.1.1/255 range anyway so I'm not sure how much info would really be leaking.

**Comment by jrick** [comment]
I "worked around" this issue by doing things the right way and just using the system hostname when accessing the machine rather than the IP.  Fine by me to close it.
