### ISSUE TITLE
Add example service files for various operating systems

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#561]
It would be useful to provide example service files that make it easier to set up dcrd to run as a service.  

* systemd
* BSD rc.d
* illumos SMF

systemd currently stands out as the one init system we really should provide examples for due to its popularity.

**Comment by jrick** [comment]
Here's a quick systemd service file I came up with and tested on Fedora:

```
[Unit]
Description=Decred Full Node

[Service]
Type=simple
User=dcrd
Group=dcrd
WorkingDirectory=/var/dcrd
ExecStart=/opt/decred/bin/dcrd --appdata=/var/dcrd
Restart=on-abnormal

[Install]
WantedBy=multi-user.target
```

Do we have a preferred location for this example to go?

**Comment by jcvernaleo** [comment]
I'd be fine with a scripts/ directory.  Or it could go in release/  Either way I'm all good.
