### ISSUE TITLE
solaris/Illumos support

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrd#567]
Looks like dcrctl has a similar issue to what @jrick fixed in decred/dcrwallet#557
```
Building: solaris amd64
# github.com/decred/dcrd/cmd/dcrctl
../../../../go/src/github.com/decred/dcrd/cmd/dcrctl/terminal.go:178: undefined: terminal.MakeRaw
../../../../go/src/github.com/decred/dcrd/cmd/dcrctl/terminal.go:194: undefined: terminal.Restore
../../../../go/src/github.com/decred/dcrd/cmd/dcrctl/terminal.go:206: undefined: terminal.MakeRaw
../../../../go/src/github.com/decred/dcrd/cmd/dcrctl/terminal.go:216: undefined: terminal.MakeRaw
```

**Comment by jrick** [comment]
This will be trickier to do than just a dep update because on the latest code those functions are still missing.  We would have to hide them behind a conditional build tag.

Would be a good idea to disable the support on Windows as well since it just does not work there.

**Comment by jrick** [comment]
No longer an issue since the --terminal feature was removed in #580.
