### ISSUE TITLE
Automatically purchased ticket appears to have not broadcast

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrd#57]
Myagui from #decred reports that an automatically purchased stake ticket has gone missing.

204aef600d8148f202bd87b8a388f8063f77ccbf133632af02983b3b02de6f1d

It returns no information for getrawtransaction on their local dcrd and I was also unable to see it on mine.

They have attempted multiple restarts, but the tx remains in their listtransactions.

Appears that an address related to that tx is also causing issues for insight:
https://mainnet.decred.org/address/DsiMartDhqV8BRDSkgA7gAY8FbazgX5djrX

That could be related to the MIA tx

**Comment by cjepson** [comment]
Fixed in most recent dcrwallet master.
