### ISSUE TITLE
dcrctl fails when default dcrd config file is missing

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#619]
In this case the default is missing because I'm running dcrd as a different user:

```
[admin@dcrd-test0 ~]$ /opt/decred/bin/dcrctl --testnet -c ~decred/.dcrd/rpc.cert getblockcount
Error creating a default config file: open /home/admin/.dcrd/dcrd.conf: no such file or directory
```

**Comment by chappjc** [comment]
I thought this was "fixed".
https://github.com/decred/dcrd/issues/303

**Comment by jrick** [comment]
me too. me too...

**Comment by jrick** [comment]
apparently this is not a hard failure, just a warning.

It only looks like a hard failure because the real failure isn't being displayed for another reason.
