### ISSUE TITLE
Try to avoid duplex connections to peers

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#641]
Pulling out of discussion in #631.

I noticed that dcrd is making outbound connections to peers with the same IP address that have already inbounded me.  While this can be a reasonable situation (e.g. multiple peers behind NAT) the more likely scenario is that it is just creating a duplex connection unnecessarily.  I think it would be useful to first determine the remote address and port of the inbound peer.  If this matches the same address and port as we were about to make an outbound connection to, the connection attempt can be stopped, since we are already connected to that same peer (even if there are others behind NAT).

**Comment by davecgh** [comment]
Posting some follow up comments as well for completeness:

----
From @chappjc:

@jrick No this is not unlikely. This is the case when I am at home. Only one is ever setup with port forwarding and externalip, while any others I limit to just outbund, but they share the same public/routable IP.

I think this is also likely to happen in dorms, houses with several nerds, etc.

----
From @jrick:

It wouldn't be happening in dorms. You need firewall access to configure the port forwarding

Besides @chappjc I'm not saying to never connect to the same ip, just check if any of the nodes you are already connected to already is listening on the same port as what you are about to connect to.

----
From @chappjc:

Good point about dorms. But another example is VPN with port forwarding.

I understand your suggestion though.

**Comment by githubsands** [comment]
@davecgh hey dave can you assign me to this issue

**Comment by jrick** [comment]
I made the mistake of assuming that the port of the inbound peer would be the same port that we try to connect to, which wouldn't be the case.  Comparing ports is not feasible.  The best we could do to try and avoid this particular situation would be to skip the port and only compare the IP address, however this means we would not support creating outbound connections to peers behind the same NAT as a different inbound peer with the same routable IP address.
