### ISSUE TITLE
rpc: implement getblocksubsidy for possible future devfees changes

### ISSUE THREAD

**Issue by tpruvot** [decred/dcrd#677]
ZEC (and its clones) have an important new rpc command to describe the mining consensus rules called getblocksubsidy.

In theory the required mining info is displayed in getblocktemplate but this command allow to bypass the rpc call, which can be very slow with a good quantity of txs.

 getblocksubsidy
> { "miner" : 10.00000000, "founders" : 2.50000000 }

help getblocksubsidy
> getblocksubsidy height
> Returns block subsidy reward, taking into account the mining slow start and the founders reward, of block at index provided.
> Arguments:
> height (numeric, optional) The block height. If not provided, defaults to the current height of the chain.

**Comment by davecgh** [comment]
So, I think this is a reasonable request, however, I think it would be slightly different output since it is a 3-way split in Decred.

Another consideration is that the actual amounts vary based on the number of votes included in the block, so the RPC would need to accept a number of votes to be completely accurate.

**Comment by tpruvot** [comment]
looks good to me, there will be indeed two different calls, one for history and one for the current state (without args) i dont think numvotes is required with a height

**Comment by tpruvot** [comment]
maybe its better to do two of them, getblocksubsidy <height> and getcurrentblocksubsidy <numvotes>

**Comment by dajohi** [comment]
#679 is what the dcrjson would be.

**Comment by tpruvot** [comment]
nice work, thanks to take care of that
