### ISSUE TITLE
Websocket JSON-RPC server does not execute requests concurrently

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#683]
Need a port of [this change](https://github.com/btcsuite/btcd/commit/d0a9c03844a4a7f4c27e24fdc856333d17ec2f6f) from btcd.

**Comment by jrick** [comment]
@davecgh please let me know if you want this change to just be ported over by itself or if it should be picked up in an upstream merge.  Ideally (for me) this would be ported/merged sometime tomorrow.

**Comment by davecgh** [comment]
I'm ok with it being ported early.  I will be doing more upstream merges in the future, but it could take a while since the entire mining infrastructure has to be reworked first.
