### ISSUE TITLE
Reverse time and date in logs?

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#692]
I'm not sure why the time comes first.  I think date followed by time would make more sense.

**Comment by davecgh** [comment]
I agree they should be reversed.  Concept ACK.

**Comment by jcvernaleo** [comment]
I agree as well.  Didn't notice this issue before but I have stated my agreement on zkc I think.

**Comment by jrick** [comment]
my logger implementation already reversed the fields: https://github.com/jrick/btclog/blob/noseelog/log.go#L144

Any interest in reversing them in the seelog implementation right now as well or just leave it?

**Comment by jcvernaleo** [comment]
For me it would depend on the timeline for your logger.  If it is coming soon then I can live with seelogger being backwards a bit longer.  If it is still uncertain, then I say we fix what we have now.

**Comment by jrick** [comment]
i think it's ready ;)

the blocking issue is that there is no equivalent to the file rolling that seelog is doing right now.

I found a package i liked that implemented it but it had no license so i can't use it yet.  I asked the author if they would license it but no response so far.

Waiting a few days for a response before i make my own file rolling implementation.

**Comment by jrick** [comment]
logrotate was just released under the 2-clause BSD so i can begin integrating that now.

**Comment by jcvernaleo** [comment]
Great.

**Comment by jrick** [comment]
This was implemented by the new logger.
