### ISSUE TITLE
EstimateStakeDiff no longer works with testnet

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#702]
...since on testnet the retarget interval (144) is greater than ticket maturity (16), testnet is not usable for testing clients that use this function.

**Comment by chappjc** [comment]
e.g. https://github.com/decred/dcrwallet/pull/747

**Comment by davecgh** [comment]
This is known and the code even contains a [comment stating the same](https://github.com/decred/dcrd/blob/3428a4011fc64efb125a5c926addefcc5dc46a40/blockchain/difficulty.go#L1346-L1356).

**Comment by chappjc** [comment]
Just though there should be an issue, although I suppose this isn't likely to be forgotten.

**Comment by davecgh** [comment]
Please test with #1115 which resolves this.
