### ISSUE TITLE
mining: Rework and sync mining code to upstream

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#709]
The proof-of-work mining code in Decred has made a significant departure from the upstream codebase in a less than ideal fashion.

The result of this is that `getblocktemplate` isn't working properly, the code is way less efficient than it should be, block templates sometimes fail to be generated and claim it's due to a race (which is inaccurate), it does not include several of the enhancements that have been made upstream since they are difficult to sync as a result of the divergence, the current handling of votes is greedy which virtually guarantees the slowest two votes won't be included in the initial block template and thus often leads to missed votes, and it generally just needs a solid housecleaning. 

The code needs a fairly significant overhaul to bring it back inline with the quality of the upstream code and then to be synced to the upstream code in order to pull in its improvements.

**Comment by teknico** [comment]
I'm porting over the btcd changes referenced in https://github.com/btcsuite/btcd/pull/814:

- https://github.com/btcsuite/btcd/pull/809 -> #910
- https://github.com/btcsuite/btcd/pull/810 -> #911
- https://github.com/btcsuite/btcd/pull/813 -> #908

Now working on https://github.com/btcsuite/btcd/pull/811 , then I'll tackle https://github.com/btcsuite/btcd/pull/814 itself and https://github.com/btcsuite/btcd/pull/824.

**Comment by teknico** [comment]
More porting:

- https://github.com/btcsuite/btcd/pull/811 -> #912
- https://github.com/btcsuite/btcd/pull/813 -> #908
- https://github.com/btcsuite/btcd/pull/814 -> #914

The latter is not complete, see description there. I need some guidance to complete this work.

**Comment by teknico** [comment]
Unsubscribed, feel free to close, thanks.

**Comment by davecgh** [comment]
This no longer applies.  The entire mining infrastructure has been reworked to support asynchronous templates and websocket-based async notifications.
