### ISSUE TITLE
dcrctl should be able to print out the json it sends and receives

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrd#727]
Inspired by decred/dcrtime having that option.

I've hacked this feature in a few times while working on other things with temporary prints but I'd prefer to just have it in once and for all.

**Comment by jrick** [comment]
Technically it already does show the json response as is (with some added indents, but it's still json output) so i don't think anything more is necessary there.

**Comment by jrick** [comment]
Oh, well it prints the json of the result object, but not the entire response.  Carry on then :)

**Comment by jcvernaleo** [comment]
It prints a piece of the json, not the whole thing.

**Comment by jcvernaleo** [comment]
And you just said that, github was too slow updating :)
