### ISSUE TITLE
failed to send split transaction: -32603: orphan transaction ..... references outputs of unknown or fully-spent transaction  ....

### ISSUE THREAD

**Issue by gravityz3r0** [decred/dcrd#729]
Not sure if this issue has been opened elsewhere (can't find it anywhere), but i have been getting this error quite consistently since i have updated to 1.0.0 and above whenever i am trying to purchase a ticket. I am not able to re-produce this at will and it seems to be happening only randomly. -walletrescan sometimes fixes this issue but not all the time. Today is one of those day where walletrescan doesn't fix the issue. I am doing purchases on my computer with VPS hot wallet as my ticket address.

I'm running the latest dcrd 1.0.3. This is my "getbalance", the ticketprice at this point of time is 37.99DCR : 

"balances": [
    {
      "accountname": "default",
      "immaturecoinbaserewards": 0,
      "immaturestakegeneration": 351.46859061,
      "lockedbytickets": 0,
      "spendable": 45.38170222,
      "total": 396.85029283,
      "votingauthority": 0
    },

-4: failed to send split transaction: -32603: orphan transaction 41dd65af65747eaef298676687f8026dac4099b2b72b47324c988647abebee7c references outputs of unknown or fully-spent transaction 226b9a2361ab482119e3ba43af03568629761e446b7e90672cd12f5bdf1bb64c

**Comment by jrick** [comment]
This is a wallet issue not a dcrd issue.

I also believe this has been fixed in the latest dcrwallet changes.  If you continue to see it either in a dcrwallet built from the latest master or in the next release, please open a new issue in the dcrwallet repo.
