### ISSUE TITLE
Source code missing

### ISSUE THREAD

**Issue by ironiridis** [decred/dcrd#8]
According to decred.org:

> Free and Open-Source Software

Where is the source code for dcrd?

**Comment by ironiridis** [comment]
See [the related issue for dcrwallet](https://github.com/decred/dcrwallet/issues/16).

**Comment by davecgh** [comment]
It was announced [on the forums](https://forum.decred.org/threads/mainnet-launch-date.380/) that "The software will be made free and open-source at 12:00 PM CST February 7th, 2016 "

**Comment by jcvernaleo** [comment]
As @davecgh pointed out, the source code is coming.  The binary release was more of a preview to get things into people's hands as soon as we could rather than a real release but code will be there for the real release.
