### ISSUE TITLE
Sample config file missing or docs link broken

### ISSUE THREAD

**Issue by johnerfx** [decred/dcrd#803]
URL in [documentation](https://docs.decred.org/faq/configuration/) ( [github source](https://github.com/decred/dcrdocs/blame/master/docs/faq/configuration.md#L32) )links to a file that does not exist:
[sample config file](https://github.com/decred/dcrd/blob/master/sample-dcrd.conf)

**Comment by davecgh** [comment]
Thanks for the report.  I've opened [an issue in the dcrdocs repo](https://github.com/decred/dcrdocs/issues/337) for the docs to be updated.
