### ISSUE TITLE
Relax dust rules for revocations

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#805]
User has encountered a problem revoking a missed ticket because the pool commitment is so small that the first output of the revocation is dust.  As these transactions must traverse the network so they can be mined to unlock the coins locked by the ticket, the dust rules should be relaxed so they are not rejected as nonstandard transactions.  Standardness checks are first and foremost to prevent creating strange transactions, but as revocations have a forced form due to consensus rules, not all of the checks make sense.

**Comment by davecgh** [comment]
Agreed.  A validly formed revocation of a ticket that is eligible for revocation should has the dust rules relaxed for the standard form.
