### ISSUE TITLE
[OpenBSD] 1.1.0 binary can't load libpthread.so

### ISSUE THREAD

**Issue by peterzen** [decred/dcrd#869]
```
$ dcrd
ld.so: dcrd: can't load library 'libpthread.so.24.0'
Killed
$ uname -a
OpenBSD **** 6.1 GENERIC.MP#20 amd64
```

**Comment by davecgh** [comment]
I assume this is with a released version.  This is almost positively caused by an ABI change in OpenBSD 6.1 whereas the cross compiled version released is for an earlier version.

@dajohi Can you confirm?

**Comment by peterzen** [comment]
The issue is indeed with the 1.1.0 binary release.

**Comment by davecgh** [comment]
Any update on the status of this?

**Comment by davecgh** [comment]
I'm going to close this since we're up to 1.1.2 now and thus it's built on a new version of OpenBSD.
