### ISSUE TITLE
tx inputs for stakebase are ignored

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#870]
The edits in PR https://github.com/decred/dcrd/pull/859 modify make `createVinListPrevOut` to handle Vin[0] for SSGen transactions as a special "stakebase" like coinbase, but instead of continuing to handle the other inputs normally, it returns without including the additional inputs which do exist for stakebase, unlike coinbase.

https://github.com/decred/dcrd/blob/1301102033b736d718e651bc17506b26929a5df6/rpcserver.go#L1222-L1254

**Comment by chappjc** [comment]
@davecgh Please assign me, unless @dnldd or someone else is itching to take this.

**Comment by davecgh** [comment]
Fixed by #871.
