### ISSUE TITLE
error run dcrd (TLS handshake error from [::1]:42888: tls: oversized record received with length 21536)

### ISSUE THREAD

**Issue by d1mf** [decred/dcrd#875]
2017/10/09 16:21:12 http: TLS handshake error from [::1]:42888: tls: oversized record received with length 21536
2017/10/09 16:21:28 http: TLS handshake error from [::1]:42912: tls: oversized record received with length 21536
2017/10/09 16:21:31 http: TLS handshake error from [::1]:42914: tls: oversized record received with length 21536
2017/10/09 16:21:32 http: TLS handshake error from [::1]:42918: tls: oversized record received with length 21536
2017/10/09 16:21:33 http: TLS handshake error from [::1]:42922: tls: oversized record received with length 21536
2017/10/09 16:21:42 http: TLS handshake error from [::1]:42942: tls: oversized record received with length 21536
2017/10/09 16:22:03 http: TLS handshake error from [::1]:42962: tls: oversized record received with length 21536
2017/10/09 16:22:04 http: TLS handshake error from [::1]:42966: tls: oversized record received with length 21536
2017/10/09 16:22:12 http: TLS handshake error from [::1]:42980: tls: oversized record received with length 21536
2017/10/09 16:22:34 http: TLS handshake error from [::1]:43014: tls: oversized record received with length 21536
2017/10/09 16:22:35 http: TLS handshake error from [::1]:43018: tls: oversized record received with length 21536
2017/10/09 16:22:42 http: TLS handshake error from [::1]:43036: tls: oversized record received with length 21536
2017/10/09 16:22:54 http: TLS handshake error from [::1]:43044: tls: oversized record received with length 21536
2017/10/09 16:23:05 http: TLS handshake error from [::1]:43060: tls: oversized record received with length 21536
2017/10/09 16:23:06 http: TLS handshake error from [::1]:43064: tls: oversized record received with length 21536
2017/10/09 16:23:13 http: TLS handshake error from [::1]:43078: tls: oversized record received with length 21536
2017/10/09 16:23:36 http: TLS handshake error from [::1]:43104: tls: oversized record received with length 21536
2017/10/09 16:23:37 http: TLS handshake error from [::1]:43108: tls: oversized record received with length 21536
2017/10/09 16:23:43 http: TLS handshake error from [::1]:43130: tls: oversized record received with length 21536
2017/10/09 16:24:07 http: TLS handshake error from [::1]:43158: tls: oversized record received with length 21536
2017/10/09 16:24:08 http: TLS handshake error from [::1]:43162: tls: oversized record received with length 21536
2017/10/09 16:24:13 http: TLS handshake error from [::1]:43178: tls: oversized record received with length 21536
2017/10/09 16:24:17 http: TLS handshake error from [::1]:43186: tls: oversized record received with length 21536
2017/10/09 16:24:38 http: TLS handshake error from [::1]:43206: tls: oversized record received with length 21536
2017/10/09 16:24:39 http: TLS handshake error from [::1]:43210: tls: oversized record received with length 21536

**Comment by jrick** [comment]
This looks like your client is trying to connect without TLS.

**Comment by d1mf** [comment]
that is, I need to use https instead of http in the web interface?

**Comment by jrick** [comment]
"web interface"?  what are you trying to do?

**Comment by d1mf** [comment]
http://decred.cloudns.pro/

I need  install decred pool (POW)

**Comment by dajohi** [comment]
not an issue.
