### ISSUE TITLE
go get README instructions

### ISSUE THREAD

**Issue by sdboyer** [decred/dcrd#882]
hi folks - just wanted to drop a note about this in your README instructions:

> Unfortunately, the use of dep prevents a handy tool such as go get from automatically downloading, building, and installing the source in a single command. Instead, the latest project and dependency sources must be first obtained manually with git and dep, and then go is used to build and install the project.

if you commit your `vendor` directory, dcrd becomes `go get`-able again. if you're trying to avoid bloating the main repository, you could follow [cockroachdb's pattern](github.com/cockroachdb/cockroach) of make the entire `vendor` directory a git submodule - dep will play nicely with that.

**Comment by jrick** [comment]
I don't think we've considered the submodule idea yet, but thanks for pointing that out.  You are correct that we are not committing vendor to avoid bloating the already large repo.
