### ISSUE TITLE
rpcclient: Add round-robin redundancy.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#884]
_From @dajohi on May 26, 2017 18:33_

Add a pool of servers for round-robin redundancy

_Copied from original issue: decred/dcrrpcclient#74_

**Comment by maicalal** [comment]
@davecgh / @dajohi, if you can add some more details, I can pick it next ?

**Comment by davecgh** [comment]
The intention is for the [RPC client](https://github.com/decred/dcrd/tree/master/rpcclient) to support specifying multiple servers and perform the requests in a round-robin fashion between them for load balancing and fault tolerance purposes.

If you have any other specific questions feel free to ask.  I'm not sure what other details to provide over and above what I've just described.

**Comment by jolan** [comment]
You can probably get some ideas from https://github.com/grpc/grpc-go/tree/master/balancer/roundrobin

**Comment by maicalal** [comment]
Thanks @davecgh and @jolan , working on it ...

**Comment by davecgh** [comment]
For anyone scouring tickets, PR #1078 addresses this.

**Comment by davecgh** [comment]
This never really got any traction, since, as it turns out, all primary consumers wanted to control the connection management themselves. One of them in particular, the wallet, decided to move away from rpcclient altogether. Consequently, while I really am not happy about closing this without merging after all this effort and time, none of the consumers want it, and it would just end up being code that has to be maintained for no benefit. Closing.
