### ISSUE TITLE
rpcclient: Add GetBlockTemplate RPC API

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#885]
_From @nntaoli on April 27, 2017 6:35_

_Copied from original issue: decred/dcrrpcclient#61_

**Comment by chappjc** [comment]
didn't @dajohi do this some time ago?

**Comment by davecgh** [comment]
Yes, he did.  I used an automated issue mover from the dcrrpcclient repo which is now part of dcrd and it appears the issue wasn't closed when the code was added.

**Comment by detailyang** [comment]
when it will be released ? We need `getblocktemplate` to support mining:)
