### ISSUE TITLE
dcrctl doesnt support the delete key

### ISSUE THREAD

**Issue by raedah** [decred/dcrd#89]
when in the --terminal mode

adding to this, Home and End do not work either for getting to the beginning and end of the line.

**Comment by alexlyp** [comment]
yah delete appears to be non-responsive, but home and end seem to work for me

**Comment by raedah** [comment]
On linux, I tested home and end using 'urxvt' and 'mate-terminal' and they did not work.

**Comment by dajohi** [comment]
Pretty sure this is an issue with https://github.com/golang/crypto/blob/master/ssh/terminal/terminal.go

**Comment by raedah** [comment]
closing because terminal mode was removed
