### ISSUE TITLE
Fix tests in address_test and bloom/filter_test

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#893]
_From @alexlyp on March 22, 2016 20:5_

There are a few tests that were commented out due to our testing methods not quite handling the situations correctly.  The hybrid and uncompressed pubkey address parsing for both mainnet and testnet, all tests pass for them except the last one for created address.  
`
                   created address does not match expected result
                   got 0264c44653d6567eff5753c5d24a682ddc2b2cadfe1b0c6433b16374dace6778f0,
                   expected 0464c44653d6567eff5753c5d24a682ddc2b2cadfe1b0c6433b16374dace6778f0b87ca4279b565d2130ce59f75bfbb2b88da794143d7cfd3e80808a1fa3203904
`

That 0264 is the compressed pubkey and the 0464 is the supplied uncompressed.  So the test appears to be successful, but not sure why it is returning incorrect info.

Another test in filter_test was commented out due to us currently not having a pay to pubkey transaction to use for the test data.  I will attempt to create one that can be used in this circumstance.

_Copied from original issue: decred/dcrutil#5_

**Comment by davecgh** [comment]
_From @dnldd on September 10, 2017 18:35_

@davecgh I think this issue should be closed.

**Comment by davecgh** [comment]
I don't believe it should.  The library should still be capable of handling hybrid addresses and that needs to be tested.

**Comment by fgimenez** [comment]
Is this issue still valid? I see the tests uncommented https://github.com/decred/dcrd/blob/master/dcrutil/address_test.go#L240, https://github.com/decred/dcrd/blob/master/dcrutil/address_test.go#L270 and https://github.com/decred/dcrd/blob/master/dcrutil/address_test.go#L300 (if those are the relevant tests, pls correct me if I'm wrong), looks like the change was done here https://github.com/decred/dcrutil/pull/54

**Comment by davecgh** [comment]
Thanks for pointing it out.  It was indeed addressed as you note.
