### ISSUE TITLE
secp256k1 package needs cleanup

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#923]
The `secp256k1` package was ported over from the upstream btcsuite/btcec package which was initially intended to work with multiple curves, however, over time, due to optimizations, it really only works with the `secp256k1` curve.

Decred made an attempt to separate this into a unique package named accordingly, however, it still has a lot of remnants that don't make sense when you're dealing with a specific curve such as accepting the curve as the first parameter.

In addition, due to the dcrec package changes, it's quite cumbersome to work with due to poor interface design.  Cleaning all of this up will need to be a multistep process, however, this issue is just focusing on the first step of the process which is to make the `secp256k1` a proper standalone package.

**Comment by davecgh** [comment]
The first part of this is resolved by #934.

**Comment by tarun1475** [comment]
I am interested to work upon this issue. Kindly guide me what i  need to do ?
