### ISSUE TITLE
rpcclient relies on bug in json.Unmarshal that is fixed in go1.10

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#942]
[go1.10 fixes a bug](https://go-review.googlesource.com/c/go/+/82135) in encoding/json.Unmarshal that allowed it to allocate an unexported field, but `(*rpcclient.Client).handleMessage` relied on this behaviour to unmarshal into `inMessage`.  As a result, we can no longer embedded pointers to unexported struct types, and then Unmarshal into a struct with such an embedded pointer without first allocating the embedded type.

https://github.com/decred/dcrd/blob/a90bdc33d43802e09c24974b40107cfbc4562494/rpcclient/infrastructure.go#L274-L278

When built with go1.10, dcrwallet gets the following error on startup:

> [WRN] SYNC: Remote server sent invalid message: json: cannot set embedded pointer to unexported struct: rpcclient.rawResponse

This change in go1.10 may very well affect other places in the decred code, but this one comes up first.

**Comment by chappjc** [comment]
Addressed by https://github.com/decred/dcrd/pull/941, but there could be other places where json.Unmarshall will give an error at runtime.

**Comment by markusrichter** [comment]
Interesting issue. I looked at all occurences of `json.Unmarshal` in the codebase, it looks like you already fixed the only occurrence of the problem. I suggest to close the issue.
