### ISSUE TITLE
validateaddress issue

### ISSUE THREAD

**Issue by feeleep75** [decred/dcrd#962]
Hi,

I noticed that dcrd running on mainnet returns true when validating testnet address, however when validating through wallet rpc it returns correct value:

```
dcrctl validateaddress Tsbc73tACMfCNCmaPkHUpM7jboqoJUv9xmG
{
  "isvalid": true,
  "address": "Tsbc73tACMfCNCmaPkHUpM7jboqoJUv9xmG"
}
dcrctl --wallet validateaddress Tsbc73tACMfCNCmaPkHUpM7jboqoJUv9xmG
{
  "isvalid": false
}
```

**Comment by dnldd** [comment]
just confirmed this, working on a fix.

**Comment by davecgh** [comment]
This is a bit questionable to be honest.  The address `Tsbc73tACMfCNCmaPkHUpM7jboqoJUv9xmG` is in fact a perfectly valid address, it's just not meant for the main network.  Claiming it's invalid is arguably incorrect.

I think this should be handled the same way it is in pretty much all of the other handlers that involve addresses.  Namely, in the case it's an address for another network, it returns an error stating it's for the wrong network as opposed to an ambiguous result.

**Comment by davecgh** [comment]
Alright, after discussing this further with the team, the majority want the behavior to match what wallet currently does.  That is to say for there to be no error in the case of the wrong network, just returning `"isvalid": false` in that case.
