### ISSUE TITLE
peer: mruInventoryMap and mruNonceMap implement LRU caches, not MRU

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#967]
We do want the LRU behavior, so this just requires some file renames and fixing the identifier names and comments.

**Comment by davecgh** [comment]
I agree that they are LRU caches, but the MRU is referring to the maps themselves containing the most recently used entries.

If they were named `mruIventoryCache` and `mruNonceCache`, it would be wrong, but that isn't what they're named.

**Comment by davecgh** [comment]
To follow up, I don't have any particular objections to them being renamed to `lruInventoryCache` and `lruNonceCache` if people think it would avoid confusion, so long as all of the comments and file names are updated accordingly.  The only thing I would say there is it seems like a lot of churn for little benefit.

**Comment by randomshinichi** [comment]
May I do this? That's assuming you still want this... I'm new to the codebase and I think this might take me on a nice tour.

**Comment by davecgh** [comment]
As discussed in dev channel, @randomshinichi will be taking this.
