### ISSUE TITLE
Add specialized rebroadcast handling for RPC server stake transactions

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#975]
Whenever a transaction is sent via the `sendrawtransaction` RPC, it gets added to a rebroadcast handler to ensure the transaction will periodically be rebroadcast until it eventually makes it into a block.  This behavior is ideal for non-stake transactions, however stake transactions require special rebroadcast handling because they do not remain valid in all situations.

Consequently, PR #973 disabled rebroadcast handling for all stake transactions to prevent the pathological behavior of continuing to periodically rebroadcast stake transactions which are no longer valid until the server process is reset.

Ideally, as the [comment](https://github.com/decred/dcrd/blob/97f043a6b768b4d7d31d07cea06810cacc47c0e3/rpcserver.go#L5017-L5024) added in the aforementioned PR indicates, the rebroadcast logic would properly handle ticket purchase and ticket revocation rebroadcasting.

I believe the following points adequately cover the desired behavior:

* A vote is only valid for a specific block, and if it is not cast quickly enough, it will end up being missed anyways, so it makes little sense to try to rebroadcast it some random time in the future and therefore should not be added at all
* Ticket purchases should be periodically rebroadcast until they show up in a block so long as they have not expired and the ticket price has not changed since they were originally issued
* Ticket revocations should be periodically rebroadcast until they show up in a block so long as the associated ticket has not been resurrected (from either a missed or expired state) due to a chain reorg.

**Comment by dnldd** [comment]
@davecgh would like to take this on, could you assign me to it.

**Comment by davecgh** [comment]
Thanks.  Done.
